### ISSUE TITLE
Please test this plugin and report here!

### ISSUE THREAD

**Issue by pwlin** [pwlin/cordova-plugin-file-opener2#1]
Please test this plugin initially and tell me if something doesn't work. Thanks very much.

**Comment by Igor-likhomanov** [comment]
@pwlin, ok!

I created two gists with services to manage this stuff. 
And fileSrvc  is not tested (in my app everything was little different)

1) fileSrvc to download files for cordova-plugin-file-opener2
https://gist.github.com/Igor-likhomanov/94adfb2daed65ed6f18c

so, to download file to right path we need to:
```
fileSrvc.download('http://someurl.com/hi.pdf', function(err, nativeURL){
 /* open file here.. we get nativeURL to open*/
})
```

"Magic" is here:

```
if (iosDevice !== null) {
    downloadPath = fileSystem.root.toURL() + fileInternal;
} else {
    downloadPath = cordova.file.externalDataDirectory + fileInternal;
}
```

2) fileOpenerSrvc for cordova-plugin-file-opener2
https://gist.github.com/Igor-likhomanov/1246ef5b87eba17645e2

This will open the file with right mime type by nativeURL:

```
fileSrvc.download('http://someurl.com/hi.pdf', function(err, nativeURL){

   fileOpenerSrvc.open(
      nativeURL, 
      successCallback, 
      errorCallback
   );

})
```

If it's not work - I will create better example!

**Comment by t4deu** [comment]
Hello @pwlin, I'm trying to setup a download and open feature with file-transfer and the opener2 on IOS and ANDROID devices.

On android it's working fine, but on the IOS, the downloaded file isn't opening. When clicking to open the file, a modal with available readers are displayed. I select a PDF reader, but nothing happens.

The file-opener fail callback is executed, but a undefined error is passed on the parameters.(Same occurs sometimes on android, but the file opens successfully)
```
   var open = function(path, successCallback, errorCallback) {
        var ext = getExt(path);
        var type = getMimeByExt(ext);
        successCallback = function(){
          alert('success');
        };
        errorCallback = function(e){
          alert('Error status: ' + e.status + ' - Error message: ' + e.message);
        };
        if(type === false) {
            alert('error: unknown file type');
            return;
        }
        try {
            alert('open path:'+ path + ' type: '+ type);            
            cordova.plugins.fileOpener2.open(       
                path, // You can also use a Cordova-style file uri: cdvfile://localhost/persistent/Download/starwars.pdf        
                type,       
                {       
                    error: successCallback,     
                    success: errorCallback  
                }       
            );      
        } catch (e) {
            alert('error: ' + JSON.stringify(e));
        }
    }
```
I using the great sample code of @Igor-likhomanov, the phonegap version is 3.6.3, and the plugin version is 1.0.11

The source is here: https://github.com/t4deu/file-opener-test

Please, can anyone help me on this?

**Comment by Igor-likhomanov** [comment]
Hallo @t4deu ,

Could you please show what "alert('open path:'+ path + ' type: '+ type);" outputs?

I'm using phonegap cloud, so in config.xml I have 
```
<preference name="iosPersistentFileLocation" value="Library" />
```

and here:
```
cordova.plugins.fileOpener2.open(       
  path, 
  type,       
    {       
        error: successCallback,     
        success: errorCallback  
    }       
);      
```
error  ===> successCallback 
success  ===>  errorCallback  

Should be so? :)

**Comment by pwlin** [comment]
@Igor-likhomanov thank you very much for posting your examples, I am sure it will be useful to other users. 

@t4deu  I wish I could help you with iOS issues but unfortunately at the moment i don't own any iDevices to troubleshoot the stuff on. I hope @Igor-likhomanov or some other users here can help you. I will test the plugin as soon as I get my hands on an iphone again. My sincere apologies.

**Comment by Langstra** [comment]
I am trying to open a file of which I know for sure it is on the file system. I just downloaded it there with the file-transfer plugin. I get the result and use toURL() to get the location. Howevery fileopener2 says it cannot find the file.
I also used this:
```
$window.resolveLocalFileSystemURL(directory, function (fileSystem) {
              if (fileSystem.isFile === true) {
                q.resolve(fileSystem);
              } else {
                q.reject({code: 13, message: "input is not a file"});
              }
            }
```
This resolves, which means the file is on the filesystem. After this I use toURL() on the result. But still fileopener2 says the file does not exist.

The toURL function return this:
```
file:///storage/emulated/0/Android/data/com.test.app/files/123456789/test/Offerte.pdf
```

**Comment by pwlin** [comment]
@Langstra have to tried to hard code the file path in `open` function to see if it works?

    cordova.plugins.fileOpener2.open("/storage/emulated/0/Android/data/com.test.app/files/123456789/test/Offerte.pdf", "application/pdf", ...........)

**Comment by Langstra** [comment]
What I had to do was this: 
```
decodeURI(result.toURL().substr(7))
```
After I received the FileEntry from the filesystem. It seems that the file:/// is killing, as well as encoded spaces and other special characters.

**Comment by pwlin** [comment]
@Langstra 
Don't use `decodeURI()`, use [`decodeURICompoment()`] (http://stackoverflow.com/questions/747641/what-is-the-difference-between-decodeuricomponent-and-decodeuri) instead. It will automatically decode all special characters.

**Comment by JerryBels** [comment]
Hello,

I upload the PDF file with my app, as an asset in a "pdf" folder. It's there - when trying to open it directly via url the network shows a 200 OK for "file:///android_asset/www/pdf/mypdf.pdf"

But when trying with fileopener2 : 

    cordova.plugins.fileOpener2.open( 'pdf/mypdf.pdf'

It doesn't work. I tried a lot, like '../pdf/mypdf.pdf', '/pdf/mypdf.pdf', "file:///android_asset/www/pdf/mypdf.pdf", ...... Nothing.

Please help ?

Thanks !

( Android 5.1 - Nexus 5 )

**Comment by Langstra** [comment]
The way I worked it out was by getting the file from the filesystem.
Getting the url of the file. Remove the first 7 characters and then open it
with fileOpener2.

$cordovaFileOpener2.open(
    decodeURIComponent(result.toURL().substr(7)), extention).then(
        function() {
            $ionicLoading.hide();
        },
    function(e) {
        console.log(fileURL);
        console.log('Error status: ' + e.status + ' - Error message: ' +
e.message);
    }
);

Met vriendelijke groet,

Wybren Kortstra

**Comment by puchmu** [comment]
Hello,
I am using your plugin and it works perfectly now for me on Android and on iOS.
I faced an issue that on iOS I only saw the "open with"-dialog,  but when I clicked one nothing happened.
After some debugging I found out that the URL must not contain any whitespaces, otherwise it will not open.
I just wanted to mention this just in case someone faces the same problem.

**Comment by alex3165** [comment]
Hello,

On Android, when I open a pdf file with fileOpener2 then I press on back button to go back on my application it reload the app and I lose my navigation stack. Is there a way to avoid it ?

thanks.

**Comment by niyazafazl** [comment]
Hello,

Im also facing the problem with FileOpener2 plugin in Android, 
I was trying cordova.plugins.fileOpener2.open() with the file path as /pdf/mypdf.pdf', '/pdf/mypdf.pdf', "file:///android_asset/www/pdf/mypdf.pdf', /sdcard/Download/pdf/mypdf.pdf'
Still showing the error: File not found.

Please advice how I could resolve this. 
I need to fix this very urgent. Please help me on this.

Thanks

**Comment by Jorrex** [comment]
Not really an issue, but something it took me a while to figure out. Your examples uses `cordova.fileOpener2.open({...})` but you have changed it to `cordova.fileOpener2a.open({...})`. Because of that, I couldn't figure out why I couldn't open a file.

Maybe you could update your README.md? To prevent further confusions.
