### ISSUE TITLE
VSDX file could not be opened

### ISSUE THREAD

**Issue by mobility-dc** [pwlin/cordova-plugin-file-opener2#100]
Hi All,

Currently we are creating an apps to open several types of file using this plugin. The files that we want to open are word, excel, pdf, power point, and visio.

This plugin is working fine for word, excel, pdf, and power point files.
For visio, we can open the file with VSD extension, but we could not open the file with extension VSDX, since there is no VSDX type in the MIME file list here (http://svn.apache.org/viewvc/httpd/httpd/trunk/docs/conf/mime.types?view=co)

If you have time, kindly need your help to give some advise on this matter.

Many Thanks,

David

**Comment by pwlin** [comment]
Can you use the same mime-type of VSD extension to open VSDX files?
