### ISSUE TITLE
An error of 'exposed beyond app through Intent.getData()' in Android 7.0

### ISSUE THREAD

**Issue by zengyufang** [pwlin/cordova-plugin-file-opener2#101]
if(this.platform.is('android')){
     this.storageDirectory = cordova.file.externalDataDirectory;
 }

const fileTransfer = new Transfer()
let targetPath = this.storageDirectory + 'qyxingv.0.0.3.apk';

fileTransfer.download(this.apkUrl, targetPath).then(
                      (result) => { 
                        uploading.dismiss();
                        let alert2 = this.alertCtrl.create({
                          title: '下载完成',
                          message: '是否安装',
                          buttons: [
                            {
                              text: '是',
                              handler: () => {
                                FileOpener.open(targetPath, 'application/vnd.android.package-archive').then(
                                  () => {debugger;console.log("123");}
                                ,error => {console.error(error);});
                              }
                            },
                            {
                              text: '稍后安装',
                              handler: () => {
                                console.log("稍后安装");
                              }
                            }
                          ]
                        });
                        alert2.present();
                    },error => {console.error(error);});
this is successful of download,but open file is faild,and an error of 'exposed beyond app through Intent.getData()' in Android 7.0

**Comment by zengyufang** [comment]
fileTransfer.download(this.apkUrl, targetPath).then(
                      (result) => {
                        
                        uploading.dismiss();
                        let alert2 = this.alertCtrl.create({
                          title: '下载完成',
                          message: '是否安装',
                          buttons: [
                            {
                              text: '是',
                              handler: () => {
                                FileOpener.open(targetPath, 'application/vnd.android.package-archive').then(
                                  () => {debugger;console.log("123");}
                                ,error => {console.error(error);});
                              }
                            },
                            {
                              text: '稍后安装',
                              handler: () => {
                                console.log("稍后安装");
                              }
                            }
                          ]
                        });
                        alert2.present();
                    },error => {console.error(error);});
                  }

**Comment by pwlin** [comment]
There is a new version (`2.0.12`)
Can you please test if this problem still exists?

**Comment by zengyufang** [comment]
thank you！that problem was soveled,and use the version of 2.0.6 is ok

**Comment by pwlin** [comment]
ok glad to hear that good luck.
