### ISSUE TITLE
Missing sharing Button

### ISSUE THREAD

**Issue by andvis** [pwlin/cordova-plugin-file-opener2#106]
I'm using fileopener2 with android to open an image into device's gallery.
It works fine but when the image is opened, miss the share button.
I don't know if it is a normal behavior or if it is a strange issue.
I downloaded the image from remote location and then moved it in gallery using this plugin: cordova-plugin-save-image.  Instead, If I manually open the gallery and pick the downloaded image, the share button is present.
Can you help me?

P.s. the path of the image is in this form: /storage/emulated/0/Pictures/IMG_20170324_115451844.jpg and mime type is: 'image/jpeg'

**Comment by andvis** [comment]
P.s. the path of the image is in this form: /storage/emulated/0/Pictures/IMG_20170324_115451844.jpg and mime type is: 'image/jpeg'

**Comment by andvis** [comment]
Hallo, 
is it a wrong question or a stupid question? Nobody can help me?

**Comment by pwlin** [comment]
I am sorry I really don't know how to help. If I knew, I would without any hesitation. but I have no idea how to help. Maybe there are other Cordova plugins which talk directly with Android Gallery app and maybe you should use them instead of this plugin?
