### ISSUE TITLE
unable to open file on sd card

### ISSUE THREAD

**Issue by yshen65** [pwlin/cordova-plugin-file-opener2#108]
this issue regard Android 6 device (with sd card  not show as the default external device when retrieve with cordova-plugin-file  --- aka sd card show as /storage/XXXX-XXXX on device)
tested machine is acer iconia one 10 
same file open from local OK (include the emulated/0 folder)
same file open from sd card fail with undefined error
 e.status  return undefined 
e.message  return undefined 
[testcode.txt](https://github.com/pwlin/cordova-plugin-file-opener2/files/921457/testcode.txt)

**Comment by pwlin** [comment]
Convert `/storage/E8D7-9E71/XXXXX.mp4` path to a valid URI (`file://` or `cdv://`)

**Comment by pwlin** [comment]
Hopefully you've fixed your issue.
