### ISSUE TITLE
Can't open pdf document

### ISSUE THREAD

**Issue by jvhe123** [pwlin/cordova-plugin-file-opener2#114]
Hi I'm using following code to open a pdf-document : 

    var pathToFile = cordova.file.externalRootDirectory + '/Download/jvhe.pdf';
    window.resolveLocalFileSystemURL(pathToFile, function (entry) {
        cordova.plugins.fileOpener2.open(
            entry.toURL(),
            'application/pdf', {
             error: function (e) {
                 console.log('Error status: ' + e.status + ' - Error message: ' + e.message);
             },
             success: function () {
                 console.log('file opened successfully');
             }
        });
    }, function (e) {
       console.log('File Not Found');
    })

In the console I see message "File opened successfully". 
However the pdf-document does not open. It seems that the Acrobat-app opens, but return an error-message :  This file cannot be opened. Please check the location ....

Does anyone has experienced the same problem of knows the solution ?

**Comment by pwlin** [comment]
- Which Andorid Version are you using?
- What is the value of `entry.toURL()`?

**Comment by jvhe123** [comment]
Hi

- the android-version of my device =  6.0.1
- The value of entry.toUrl() = file:////storage/emulated/0/Download/jvhe.pdf
- here are some entries of config.xml

<engine name="android" spec="~6.1.0"/>
<preference name="android-minSdkVersion" value="16"/>
<access origin="*"/>
<allow-intent href="cdvfile:*" />
<allow-intent href="file:*" />
<plugin name="cordova-plugin-file" spec="~4.3.2" />
<plugin name="cordova-plugin-file-transfer" spec="~1.6.2" />
<plugin name="cordova-plugin-file-opener2" spec="~2.0.15" />

**Comment by pwlin** [comment]
What FileOpener2 version are you using?

**Comment by jvhe123** [comment]
Fileopener version 2.0.15

**Comment by pwlin** [comment]
I think there is a problem with directly opening files in main `Download` directory.

Can you copy the file inside your own app and open it from there?

Also, test if your files can be opened by using [InAppBrowser plugin](https://cordova.apache.org/docs/en/latest/reference/cordova-plugin-inappbrowser/)

**Comment by jvhe123** [comment]
Do you have any example how I can copy the file into the app-directory ?

**Comment by jvhe123** [comment]
I can open the same pdf-document via inAppBrowser

**Comment by pwlin** [comment]
If you just need to open simple pdf files, I suggest you use InAppBrowser, as it works and will save you a lot of headaches trying to find out why FileOpener2 is currently not working for you.

If you insist on using FileOpener2, try a couple of things:
- Include a test pdf on the same level as your `index.html` and use `cordova.file.applicationDirectory` to locate it. Test if you can open that file.

- connect your device to your pc and use `adb logcat` on command line to see what kind of errors are you getting

**Comment by jvhe123** [comment]
I think I will use inAppBrowser for now.
Thank you for your support.

**Comment by pwlin** [comment]
No problem. Good luck.
