### ISSUE TITLE
Feature request: showOpenWithDialog for Android

### ISSUE THREAD

**Issue by luckylooke** [pwlin/cordova-plugin-file-opener2#116]
Thank you for sharing this plugin with community. 👍 

I dont know if it is possible, but I would really welcome same feature showOpenWithDialog also for Android, not just iOS, many thanks ;)

**Comment by pwlin** [comment]
I'll be honest I am not going to promise you something I can't deliver. But I'll see what I can do. In the meantime you are welcome to send me a pull request.
