### ISSUE TITLE
Cant open PDF with fileOpener2 with ionic3 on Android 7

### ISSUE THREAD

**Issue by supryin** [pwlin/cordova-plugin-file-opener2#117]
Error:

DocService: Attempt to invoke virtual method 'android.content.res.XmlResourceParser android.content.pm.PackageItemInfo.loadXmlMetaData(android.content.pm.PackageManager, java.lang.String)' on a null object reference
Our code:

  this.fileOpener.open(storageLocation, 'application/pdf')
                .then(() => this.log.info('File is opened', this))
                .catch(error => {
                  this.log.info('Error openening file', this);
                  this.log.info(error, this);
                });
also see: http://stackoverflow.com/questions/38516646/fileprovider-error

Our code works on Android 5 und iOS. We have the error only on Android 7. We didn't test on Android 6.
storageLocation = 'file:///storage/emulated/0/download/mypdf.pdf'

Link: https://github.com/pwlin/cordova-plugin-file-opener21

We successfully download and save the file, but just fail to open it.
Any help it is appreciated, it is quite urgent. :slight_smile:
Thanks a lot in advance!

**Comment by pwlin** [comment]
How do you assign a value to `storageLocation` ? Can you post the code where you create this variable?

**Comment by supryin** [comment]
@pwlin 
let storageLocation = encodeURI(this.file.externalRootDirectory + "download/" + fileName);

**Comment by supryin** [comment]
@pwlin Why? We got permission to write to the external root directory and we are successfully downloading file there. We just fail at opening it:

this.file.checkDir(this.file.externalRootDirectory, "download")
                                    .then((success)=> {
                                                    this.storageDirectory = this.file.externalRootDirectory + "download/";
                                                    this.log.info(" is true storage dir = ", this);
                                                    this.log.info(this.storageDirectory, this);
                                                })
                                    .catch((error)=> {
                                                        this.storageDirectory = this.file.dataDirectory;
                                                        this.log.error("c error storage dir = ", this);
                                                        this.log.error(this.storageDirectory, this);
                                                        this.log.error(error, this);
                                                    }
                                     ).then(()=> {
                                                this.getFile(this.storageDirectory,fileName,fileLocation);
                                            });

**Comment by sweexxik** [comment]
I've experienced the same issue. Some information that I've found in web: [Link](https://inthecheesefactory.com/blog/how-to-share-access-to-file-with-fileprovider-on-android-nougat/en1).
Maybe it might help to find a solution.

**Comment by pwlin** [comment]
Hi @sweexxik  thank for the link. The article explains how to use file providers with Android and mentions creating a file (`provider_paths.xml`) and reference the paths you would like to work with. This is already implemented in FileOpener2 and the provider file is located at [src/android/res/xml/opener_paths.xml
](https://github.com/pwlin/cordova-plugin-file-opener2/blob/master/src/android/res/xml/opener_paths.xml)

So maybe playing with that file might be an option.

**Comment by pwlin** [comment]
Also please read [Cordova File Plugin Documentation](https://cordova.apache.org/docs/en/latest/reference/cordova-plugin-file/) and search for `toURL` and `resolveLocalFileSystemURL` functions. That is how you should build the path to the file you want to open. You might not need to change anything in `opener_paths.xml` after all.
