### ISSUE TITLE
$cordovaFileOpener2 can only open pdf file. i need to open docx,image,xl files

### ISSUE THREAD

**Issue by JYOTHISHPJ** [pwlin/cordova-plugin-file-opener2#119]
$cordovaFileOpener2.open(
                                 targetPath , // Any system location, you CAN'T use your appliaction assets folder
                                    'application/pdf'
                                ).then(function() {

                                    console.log('Success');
                                }, function(err) {
                                    console.log('An error occurred: ' + JSON.stringify(err));
                                });

sice it is application/pdf it can only open pdf.what can i do to open doc file with my default document viewer...
plz help

**Comment by pwlin** [comment]
Use an appropriate mime type to open other kind of files.
