### ISSUE TITLE
Question about support

### ISSUE THREAD

**Issue by OopDeveloper89** [pwlin/cordova-plugin-file-opener2#12]
Hello,

your plugin is nice and works well with pdf, if it not contains spaces (like "hello tom.pdf")...
Can you extend the plugin that it works with spaces too?

And another question:
Does this plugin work with jpg, png, txt as well?

Thank you very much.

**Comment by ravirajesh** [comment]
I have tried giving right path, mime types and app installed on my device for images and texthtml still they are not opening at all. Any idea? please suggest.

cordova.plugins.fileOpener2.open(
"file:///storage/emulated/0/Android/data/com.aws.myjobs2016_imr/MyJobs/User/TEST_WMT102/57005817-0010/19-02-2020-13-41-45-308-999-0000570058170050-TEST_WMT102-During Work.jpg",
                "image/jpeg",
                {
                    error: function (e) {
                       
                        opErrorMessage("Error opening file: " + e);
                    },
                    success: function () { }
                }
            );
