### ISSUE TITLE
Blank page after Done

### ISSUE THREAD

**Issue by bastianjoel** [pwlin/cordova-plugin-file-opener2#120]
When I open a PDF file on the iPad and then click on the "Done" button I'm getting a blank page.

**Comment by pwlin** [comment]
That's weird. Which iPad and which iOS version? Do you have the latest FileOpener2 version?

**Comment by bastianjoel** [comment]
Both the latest. Cordova also the latest.

**Comment by pwlin** [comment]
I see. There is also [Cordova InAppBrowser Plugin](https://github.com/apache/cordova-plugin-inappbrowser) for opening (among other things) pdf files. Have you tried that?

**Comment by bastianjoel** [comment]
Not yet, but I will have a look on it.
