### ISSUE TITLE
Blank space on right hand side of app after pdf viewer DONE on iOS iPad

### ISSUE THREAD

**Issue by joe-complete-grp** [pwlin/cordova-plugin-file-opener2#122]
After tapping DONE on the pdf viewer on iOS there is a white area a few hundred pixels width on the right hand side of the ipad screen. I have inspected in safari and its not a html element, its like a section of the screen is covered by a white box or a portion of the web view is no longer being rendered or the webview has reduced its overall width. Vaguely similar to the following issue https://github.com/pwlin/cordova-plugin-file-opener2/issues/120.

Any ideas?

**Comment by joe-complete-grp** [comment]
Update:  The webview is displaying in portrait mode after returning from the document viewer - hence the blank space on the right side. If rotate the device to portrait then back to landscape the full view is returned. I will report back on the fix when I work it out.

**Comment by joe-complete-grp** [comment]
Ok so it turned out to be related o the status bar plugin. I removed and re-added the status bar plugun and the issue is resolved.

**Comment by pwlin** [comment]
Ah! It's always good to test without any other plugin :smile:

**Comment by joe-complete-grp** [comment]
yep - my first phonegap project - will keep in mind for next time!

**Comment by pwlin** [comment]
well we all started from somewhere! Good luck with your project!
