### ISSUE TITLE
Status bar showing on Document viewer

### ISSUE THREAD

**Issue by joe-complete-grp** [pwlin/cordova-plugin-file-opener2#123]
On iOS the status bar appears when viewing the PDF regardless of if its set to hide in Cordova or xCode plist.

Add the following 2 lines to the documentInteractionControllerViewControllerForPreview method to fix the issue.

[[UIApplication sharedApplication] setStatusBarHidden:YES];
[[[[UIApplication sharedApplication] delegate] window] setWindowLevel:UIWindowLevelStatusBar];

**Comment by pwlin** [comment]
Hi @joe-complete-grp Thanks for the tips. Is this related to the other ticket (#122) you opened?

**Comment by joe-complete-grp** [comment]
Well I was having both issues but technically not related as the issues can happen independently.

**Comment by pwlin** [comment]
ok thanks for your finding, I will add this in the next release.

**Comment by joe-complete-grp** [comment]
Sweet- It would be awesome to have a js handler for the DONE action also.

**Comment by pwlin** [comment]
I don't think there is any way to control Done button from Cordova. 

But, there is also an official Plugin ([Cordova InAppBrowserPlugin](https://github.com/apache/cordova-plugin-inappbrowser)) for opening pdf files. I am not sure if it has a js event for Done button, but I think it's worth a try.

**Comment by joe-complete-grp** [comment]
in C# Is there not a way to listen for event thats fired when the user taps DONE - then bubble/dispatch that back to the cordova side of things?

**Comment by pwlin** [comment]
Try InAppBrowser plugin, maybe they have a workaround.
