### ISSUE TITLE
An error of 'exposed beyond app through Intent.getData()' in Android 7.0

### ISSUE THREAD

**Issue by kongdewen1994** [pwlin/cordova-plugin-file-opener2#125]
ionic2

download() {
    var _that = this;
    let url = 'http://112.126.82.220:8020/xiaoshubao.apk';
    var apkurl = this.file.externalDataDirectory + 'xiaoshubao.apk';
    this.fileTransfer.download(url, apkurl).then((entry) => {
      alert('download complete: ' + entry.toURL());
      //打开apk
      //window['install'].install(apkurl.replace("file://", ""));
      this.fileOpener.open(apkurl, 'application/vnd.android.package-archive')
        .then(() => console.log('File is opened'))
        .catch(e => alert('Error：' + e));

    }, (error) => {
      // handle error
    });

  }

**Comment by kongdewen1994** [comment]
use the version of 2.0.6 is ok, why Version: 2.0.15 is not working

**Comment by pwlin** [comment]
Android has changed the way you construct file URIs. Please read [Cordova File Plugin Documentation](https://cordova.apache.org/docs/en/latest/reference/cordova-plugin-file/) and search for `toURL` and `resolveLocalFileSystemURL` functions. That is how you should build the path to the file you want to open.

**Comment by kongdewen1994** [comment]
thanks

**Comment by kid1412621** [comment]
@pwlin 请问有具体 demo 吗? 还是不行.
 Demo required 
Android 8.0+ , version 2.0.19
