### ISSUE TITLE
"Class not found" error

### ISSUE THREAD

**Issue by brassier** [pwlin/cordova-plugin-file-opener2#126]
I'm doing a simple test using Ionic native, where I download a file then try to use this plugin to open it.  The download succeeds, but the open fails with the following error `Class not found`.  Any ideas?

    fileTransfer.download(pdfUrl, this.file.dataDirectory + "test.pdf", false)
	.then((entry) => {        
		this.loggingService.debug('File is downloaded: ' + this.file.dataDirectory + "test.pdf");        
		this.fileOpener.open(this.file.dataDirectory + "test.pdf", 'application/pdf')          
			.then(() => this.loggingService.debug('File is opened'))          
			.catch(e => {this.loggingService.error(`Trouble opening a pdf: ${pdfUrl}`, e); 
         });      
		}),
	(error) => { this.loggingService.error(`Trouble downloading a pdf: ${pdfUrl}`, error); 
        };

**Comment by pwlin** [comment]
Can you trace your code and see which `Class` it actually means?
