### ISSUE TITLE
open the file with the error 'exposed beyond app through Intent.getData()'

### ISSUE THREAD

**Issue by SamZSL** [pwlin/cordova-plugin-file-opener2#127]
hi, @pwlin，i used the plugin to download  an apk file, and it was successful. But when i try to open it, the system is always wrong with the error 'exposed beyond app through Intent.getData()', the version of plugin is 2.0.15.
 ` var folder = cordova.file.externalRootDirectory;
                // var folder = cordova.file.externalDataDirectory;
                window.resolveLocalFileSystemURL(folder, function(fileEntry) {
                  fileEntry.getDirectory("inspection", { create: true, exclusive: false }, function (fileEntry) {
                   
                    // console.log(fileEntry.toInternalURL());
                    var fileTransfer = new FileTransfer();
                    fileTransfer.download("http://120.26.105.20:8082/inspection.app.apk",
                        fileEntry.toInternalURL()+"inspection.app.apk", function(entry) {
                      
                      // console.log(entry.toURL());
                    
                      navigator.notification.progressStop();
                            cordova.plugins.fileOpener2.open(
                                fileEntry.toInternalURL()+'inspection.app.apk',
                                'application/vnd.android.package-archive', {
                                    error: function(err) {
                                        console.log(err);
                                    },
                                    success: function(res) {
                                        console.log(res)
                                    }
                                });`

**Comment by SamZSL** [comment]
ok!that problem was solved with the version(2.0.6)!But i still hope u to solve the problem  in the new version.@ @pwlin
thanks!

**Comment by pwlin** [comment]
Hi @SamZSL, can you please test with version `2.0.7`? Does that version work for you?

**Comment by SamZSL** [comment]
The version 2.0.7 has already been fine.
