### ISSUE TITLE
Android 7.0 open apk file is not working

### ISSUE THREAD

**Issue by liugogal** [pwlin/cordova-plugin-file-opener2#128]
I used this plugin on Android 7.0. But it can't open apk and no Exception.So I think the code will be like this:

```
if((Build.VERSION.SDK_INT >= 23 && !contentType.equals("application/vnd.android.package-archive")) || (Build.VERSION.SDK_INT == 24 && contentType.equals("application/vnd.android.package-archive"))){
      ....
}
```

**Comment by pwlin** [comment]
Hi @liugogal 
Thank you for the tip. I have modified the code and pushed a new version `2.0.15` to npm. Can you please upgrade your version and test and let me know if everything works correctly now? Thanks again.

**Comment by SamZSL** [comment]
the version 2.0.16  is ok; I can open apk and install it.   I have checked the version 2.0.6~2.0.15,and 2.0.14、2.0.15 are not work well，I cant open apk with them.But now ,the new version works. Thanks! @pwlin @liugogal

**Comment by pwlin** [comment]
Glad this issue is resolved. Thanks to both of you!
