### ISSUE TITLE
Opening an APK fails

### ISSUE THREAD

**Issue by mgsx** [pwlin/cordova-plugin-file-opener2#131]
Hi,

I can only open an APK ("application/vnd.android.package-archive") with version 2.0.13.
All the other versions do not work anymore. 

I have SDK 25 and an Android Device 7.2.1.

Can you please modify the condition again?
Why is the condition if(Build.VERSION.SDK_INT >= 23) not enough?

Thank you

**Comment by pwlin** [comment]
Can you please provide a bit more details than `All the other versions do not work anymore`?
Do you get any specific error? If so, what does it say?

**Comment by mgsx** [comment]
Version 2.0.14 - 20.0.17.

The problem is the condition in your code (Line 107 FileOpener2.java).

(Build.VERSION.SDK_INT == 24 && contentType.equals("application/vnd.android.package-archive")

I have SDK_INT 25. 

Error: ... exposed beyond app through Intent.getData().

**Comment by pwlin** [comment]
I have released a new version (`2.0.19`) which tries to fix this issue. Can you please upgrade and let me know if your problem is now solved? thanks
