### ISSUE TITLE
Constraint problem with showOpenWithDialog

### ISSUE THREAD

**Issue by allemattio** [pwlin/cordova-plugin-file-opener2#132]
Hi.
I'm trying to use the showOpenWithDialog method in my iOs app but the popup never comes out and in XCode I have this error regarding Constraint problems:

`
[LayoutConstraints] Unable to simultaneously satisfy constraints.
	Probably at least one of the constraints in the following list is one you don't want. 
	Try this: 
		(1) look at each constraint and try to figure out which you don't expect; 
		(2) find the code that added the unwanted constraint or constraints and fix it. 
(
    "<NSLayoutConstraint:0x1702918a0 H:|-(8)-[SFAirDropActiveIconView:0x12de3a590]   (active, names: '|':UIView:0x12de801b0 )>",
    "<NSLayoutConstraint:0x170292d90 H:[SFAirDropActiveIconView:0x12de3a590]-(15)-[UILabel:0x12de821c0'AirDrop. Share instantly ...']   (active)>",
    "<NSLayoutConstraint:0x170291580 UILabel:0x12de821c0'AirDrop. Share instantly ...'.trailing == UIView:0x12de801b0.trailing - 8   (active)>",
    "<NSLayoutConstraint:0x17428a1e0 'UIView-Encapsulated-Layout-Width' UIView:0x12de801b0.width == 19   (active)>"
)

Will attempt to recover by breaking constraint 
<NSLayoutConstraint:0x170292d90 H:[SFAirDropActiveIconView:0x12de3a590]-(15)-[UILabel:0x12de821c0'AirDrop. Share instantly ...']   (active)>
`

**Comment by pwlin** [comment]
Are you using "AutoLayout" with your `.xib` files?

**Comment by allemattio** [comment]
I'm using Cordova defaults. I've not modified any of the xib.

**Comment by pwlin** [comment]
There should be a setting in file inspector. A checkbox called "Use Autolayout". Can you untick that and try to rebuild your app to see if that works?

**Comment by allemattio** [comment]
yeah I could try. But I have a problem, I develop my app using Sencha Touch and the iOS release problem is pretty automized. If I have to put that thick all the process should be done manually. Since I'm not modifying cordova's xib at all and when I started using this plugin it all worked fine, I think this could be a bug introduced in one of the latter updates.

**Comment by pwlin** [comment]
First things first :) Let's try to see if unticking that option would actually solve your problem :) Then worry about your automated setup. So can you please do it once manually to see if my workaround actually works? Does unticking "Use AutoLayout" and rebuilding your app in XCode fix your problem?

**Comment by pwlin** [comment]
Did you have time to build your app without "Use AutoLayout" checked?

**Comment by pwlin** [comment]
I hope you've found a solution to this issue.
