### ISSUE TITLE
PDF not opening - "This path is not valid" - Android 5.0.2

### ISSUE THREAD

**Issue by bobalazek** [pwlin/cordova-plugin-file-opener2#133]
Like the title says, I'm trying to open a PDF file, which was saved to the local device `file:///data/data/{APP_ID}/files/{FILE}.pdf` on Android 5.0.2 and it always says "This path is not valid", when I try to open it with a PDF app. I've also tried to remove the "file://" part, but doesn't work either. Otherwise, I do have another Android device with 7.0, but it works fine there.
I use it via Ionic and I have the newest version installed `cordova-plugin-file-opener2 2.0.17 "File Opener2"`

EDIT: One more thing that I noticed is, that if I list the directory out, the file does exist. I'm also attaching the adb error log:
```
*when it shows the select your pdf opener app*
E/Vold    (  248): Failed to find mounted volume for /storage/extSdCard/Android/data/{APP_ID}/files/
E/Vold    (  248): Failed to find mounted volume for /storage/extSdCard/Android/data/{APP_ID}/files/
E/Vold    (  248): Failed to find mounted volume for /storage/extSdCard/Android/data/{APP_ID}/cache/

*after I select the PDF app -- Drive PDF Viewer*
E/DisplayData(28703): openFd: java.io.FileNotFoundException: Permission denied
E/PdfLoader(28703): Can't load file (doesn't open)  Display Data [PDF : {FILE}.pdf] +FileOpenable, uri: file:///data/data/{APP_ID}/files/{FILE}.pdf
E/chromium(26871): [ERROR:layer_tree_host_impl.cc(2233)] Forcing zero-copy tile initialization as worker context is missing

*nothing really shows up when I choose the adobe acrobat app, except the  "Error: The document path is not valid" alert*
```

**Comment by pwlin** [comment]
Newer Android versions have changed the way you construct a file path. You should create a `File` handler object and then use `toURL()` function. Be sure to read [cordova-plugin-file docs](https://cordova.apache.org/docs/en/latest/reference/cordova-plugin-file/)

**Comment by bobalazek** [comment]
Thanks for your answer!

I Actually have. I always push toURL() as a file path when opening... even, to make double sure, I've wrapped it into the `file.resolveLocalFileSystemUrl()` (which, nevertheless gives exact the same string). So here's my code:
```
openPdf(filePath) {
    console.log('Opening PDF. Path:');
    console.log(filePath);

    this.file.resolveLocalFilesystemUrl(filePath)
      .then((entry) => {
        console.log('Resolved entry:');
        console.log(entry);
        console.log('Entry URL:');
        console.log(entry.toURL());

        this.fileOpener.open(entry.toURL(), 'application/pdf')
          .then(() => {
            console.log('File is open.');
          })
          .catch((error) => {
            console.log('Error: ' + error);
          });
      })
      .catch((error) => {
        console.log('Error:');
        console.log(error);
      });
  }
```
The filePath and entry.toURL() are always exact the same. The problem seems to only be on older devices. On my devices, because on the newer Android 7.0 everything seems to work file.

**Comment by pwlin** [comment]
There is a `2.0.19` version now, try to see if that works. You also mentioned:

    *when it shows the select your pdf opener app*

Do you have more than one pdf viewer installed on that app?

Other thing is that in your error it says:

    E/Vold    (  248): Failed to find mounted volume for /storage/extSdCard/Android/data/{APP_ID}/files/

That means `/storage` is not mounted as a volume :)

**Comment by bobalazek** [comment]
No, sadly it still doesn't work with 2.0.19.

Yes, one is the preinstalled Drive PDF Viewer, but because that didn't work, I also installed Acrobat reader... doesn't work on either of them.

Yes, I currently don't have any SD card inside. Though I don't think it should interfere with the functionality since I'm saving on the device rather than on the SD, but just in case I gave the full log. :)

I've even listed out all the files and directories on the device inside the `file.listDir(dataDirectory)` and it does find the file inside.

**Comment by pwlin** [comment]
Have you tried [cordova-plugin-inappbrowser](https://cordova.apache.org/docs/en/latest/reference/cordova-plugin-inappbrowser/) to see if that plugin works for you?

**Comment by bobalazek** [comment]
Oh, that one actually crashes my both of my devices, but it's probably unrelated to this issue (some null pointer exception).

**Comment by pwlin** [comment]
Very strange, that's an "official" Cordova plugin with an army of people behind it. I would create a pretty basic app with just the FileOpener2 functionality, and try to make it work with inappbrowser. You can work your way up from there.

**Comment by pwlin** [comment]
Did you find a solution to this issue?

**Comment by bobalazek** [comment]
No, haven't had time yet. Or actually, I'll try to find if I have some more Android 5.0 somewhere, in case the issue would only be isolated to that one device.

**Comment by spyder86** [comment]
I was having same problem playing local video files!. I gave read storage permission to my app and VOILA!
Hope that helps :)

**Comment by bobalazek** [comment]
Hey, sorry for the late response, but which permission do you mean? I can only find the `READ_EXTERNAL_STORAGE` permission which is related to storage, but in my case, I'm saving the files to the internal storage.

**Comment by CuriousLayman** [comment]
I have this exact issue as well.

**Comment by camolin3** [comment]
Use `externalCacheDirectory`.

**Comment by J6ey** [comment]
I know this is a bit late, but the reason why Drive PDF Viewer and other pdf viewer apps refuse to open the file is permission related. 

Giving `READ_EXTERNAL_STORAGE ` and `WRITE_EXTERNAL_STORAGE` permissions to your app is one thing, but the pdf viewer app launched from your `ACTION_VIEW` intent must also be granted read permission to access the pdf file. Some apps upon launch will request for the read permission, others like Drive PDF Viewer seems to skip that, and I have no clue as to why.
