### ISSUE TITLE
Hi,in the ionic3,file opener can not open apk file

### ISSUE THREAD

**Issue by icantforget** [pwlin/cordova-plugin-file-opener2#134]
My android api level  is 25
it will get "file:///storage/emulated/0/54.zip exposed beyond app through Intent.getData()"]}  error,

I search a lot of article,but can't fix it. it should translate "file:///" to "content:///" in android 7.0+,but it didn't.

it's amazing ,if change the file extentsion to other like 'zip',it can be opened.

if there have a issue with the MIME  "application/vnd.android.package-archive"?

I try to use like resolveLocalFilesystemURL or externalRootDirectory still can not work.

Help me ,thanks!~~

**Comment by icantforget** [comment]
Hi ,there have a bug in the FileOpener.java  107 line,
if((Build.VERSION.SDK_INT >= 23 && !contentType.equals("application/vnd.android.package-archive")) || ((Build.VERSION.SDK_INT == 24||Build.VERSION.SDK_INT == 25) && contentType.equals("application/vnd.android.package-archive"))) {

if should add android api lastest level of 25,it will be fixed after change like this.

but I think it will replace like this is more better

if((Build.VERSION.SDK_INT >= 23 && !contentType.equals("application/vnd.android.package-archive")) || ((Build.VERSION.SDK_INT>24) && contentType.equals("application/vnd.android.package-archive"))) {

I don't know this business .I think you guys can update this .How do you think?

**Comment by pwlin** [comment]
I have released a new version (`2.0.19`) which tries to fix this issue. Can you please upgrade and let me know if your problem is now solved? thanks
