### ISSUE TITLE
The plugin return an empty file

### ISSUE THREAD

**Issue by damienld22** [pwlin/cordova-plugin-file-opener2#136]
Hello,

When I use your plugin to open a file (text), the plugin return me an empty file. I checked the file path and I manually open the file, everything is ok.

Have you an idea what the problem is ?

I use this plugin on an Ionic 2 application running on a Honor Huawei device.

Thank you

**Comment by pwlin** [comment]
I am not exactly sure how you open the file, but newer Android versions have changed the way you construct a file paths. You should create a `File` handler object and then use `toURL()` function. Be sure to read [cordova-plugin-file docs](https://cordova.apache.org/docs/en/latest/reference/cordova-plugin-file/)

**Comment by damienld22** [comment]
`this.fileOpener.open(this.file.externalDataDirectory + name, type).then((file) => console.log("File : ", file)).catch((err) => console.error("Error : ", err));`

I open my file like this. Now I will test your solution.

**Comment by pwlin** [comment]
what is the value of `this.file.externalDataDirectory + name`?

**Comment by damienld22** [comment]
This is  `file:///storage/emulated/0/Android/data/com.ionicframework.ionicapplicationweb2day169392/files/receipt.json`

**Comment by damienld22** [comment]
I tested your solution but the method `toURL()` return the same path as above.

I create the file like this : 
```
// Create and save the file
                    this.file.createFile(this.file.externalDataDirectory, 'receipt.json', true).then((msg) => {
                        this.file.writeExistingFile(this.file.externalDataDirectory, 'receipt.json', dataStr).then((msg) => {
```

**Comment by pwlin** [comment]
Did you find a solution to this issue?

**Comment by preservance717** [comment]
@pwlin Did you solve this problem?
