### ISSUE TITLE
Error while Opening the File - Different Issue

### ISSUE THREAD

**Issue by slack0129** [pwlin/cordova-plugin-file-opener2#137]
I know there was already a closed issue for Error while Opening the File #130 posted by jinuem and we have tried to implement the latest version 2.0.19 into our build and we are still receiving the same error that jinuem was receiving. We are not using any config.xml preferences for any persistent storage which was known to cause certain issues. Everything works perfectly fine on our test devices running Android 6.0 and lower.

Versions:
Cordova - 6.5.0
Android - 6.0 and higher

Devices:
Motorola Turbo 2 / Android: 7.0, XT1585
Google Pixel / Android 7.0

The last know execution before receiving an error on this is (note: OURAPPNAME is used in place of our actual APK file name here):

cordova.callbackFromNative('FileTransfer718411854',true,1,[{"isFile":true,"isDirectory":false,"name":"OURAPPNAME.apk","fullPath":"\/Download\/OURAPPNAME.apk","filesystemName":"sdcard","filesystem":1,"nativeURL":"file:\/\/\/storage\/emulated\/0\/Download\/OURAPPNAME.apk"}],false);

**Error Message captured**: "Attempt to invoke virtual method 'android.content.res.XmlResourceParser android.content.pm.PackageItemInfo.loadXmlMetaData(android.content.pm.PackageManager, java.lang.String)' on a null object reference"

**Sample Code**:
`window.requestFileSystem(LocalFileSystem.PERSISTENT, 5 * 1024 * 1024, function (fs) {
            //Show user that download is occurring
            $("#toast").dxToast({
                message: "Downloading please wait..",
                type: "warning",
                visible: true,
                displayTime: 20000
            });

            // we will save file in .. Download/OURAPPNAME.apk
            var filePath = cordova.file.externalRootDirectory + '/Download/' + "OURAPPNAME.apk";
            var fileTransfer = new FileTransfer();
            var uri = encodeURI(appDownloadURL);

            fileTransfer.download(uri, filePath, function (entry) {
                //Show user that download is occurring/show user install is about to happen
                $("#toast").dxToast({
                    message: "Download complete! Launching...",
                    type: "success",
                    visible: true,
                    displayTime: 2000
                });

                //Use pwlin's fileOpener2 plugin to let the system open the .apk
                cordova.plugins.fileOpener2.open(
                                entry.toURL(),
                                'application/vnd.android.package-archive'
                            );
            },
            function (error) {
                //Show user that download had an error
                $("#toast").dxToast({
                    message: error.code + " for " + url + "",
                    type: "error",
                    displayTime: 5000
                });
            },
            false);
        })`

Any insight into this would be awesome! Things worked perfectly fine even on Android devices running 6.0 or higher prior to our testing yesterday. I'm not sure why we are getting this error now.

**Comment by pwlin** [comment]
I am not exactly sure what caused this problem for you. Can you try to install previous versions to see which one works for you?

**Comment by slack0129** [comment]
We have attempted to dig back to a previous version that we would have been using, but honestly we haven't tracked versioning on this plugin because it has been great from the start and actually solved a problem for us where we couldn't use the cordova file plugin to open our downloaded apk. I would be guessing at best and that wouldn't lead to a productive conclusion. We've always used this in our config.xml:

<plugin name="cordova-plugin-file-opener2"/>

I did not mention above that our target SDK is set to 22 on this project and I am not sure how much that actually matters or not here since Android 6 and above can handle Target SDK levels of 22 just fine.

What can we provide, or what would you need from our end that will help in diagnosing this issue further and work toward a resolution?

**Comment by pwlin** [comment]
Try to find out which FileOpener2 version had worked for you previously.

**Comment by slack0129** [comment]
Solidly I can say at least version 2.0.9 was working for us tracking the dates of the commits on this project versus our check-ins. I have additional info here from our debugging yesterday as well.

It seems to be some kind of blow up in the cordova.js file when the FileOpener2 makes it's callback call:
**This is all from the internal cordova.js file caught while debugging, not our code**

file: cordova.js
function androidExec(success, fail, service, action, args) {
// argsJson - ["file:///storage/emulated/0/download/OURAPPNAME.apk","application/vnd.android.package-archive"]
//callbackId - FileOpener21362683899
//action - open
//service  FileOpener2
//bridgesecret - 1334209170

**We've traced the issue down to this bit of code as the problem**
`var msgs = nativeApiProvider.get().exec(bridgeSecret, service, action, callbackId, argsJson);
    // If argsJson was received by Java as null, try again with the PROMPT bridge mode.
    // This happens in rare circumstances, such as when certain Unicode characters are passed over the bridge on a Galaxy S2.  See CB-2666.
    if (jsToNativeBridgeMode == jsToNativeModes.JS_OBJECT && msgs === "@Null arguments.") {
        androidExec.setJsToNativeBridgeMode(jsToNativeModes.PROMPT);
        androidExec(success, fail, service, action, args);
        androidExec.setJsToNativeBridgeMode(jsToNativeModes.JS_OBJECT);
    } else if (msgs) {
        messagesFromNative.push(msgs);
        // Always process async to avoid exceptions messing up stack.
        nextTick(processMessages);
    }`

**var msgs - always comes back with this error on Android 6.0 or higher**
// msgs = "230 F09 FileOpener21362683899 sAttempt to invoke virtual method 'android.content.res.XmlResourceParser //android.content.pm.PackageItemInfo.loadXmlMetaData(android.content.pm.PackageManager, java.lang.String)' on a null object reference"

**Comment by pwlin** [comment]
I am genuinely sorry for not being able to help you here. Have you tried asking for help in StackOverflow? As you are using "we" for referring to yourself, my guess is that there is a team behind your app. Maybe an option would be to hire a Cordova/Android developer on freelance sites like UpWork for a hour to fix your issue. Those are usually very affordable.

**Comment by slack0129** [comment]
Yes this is a team project and we have posted to StackOverflow since last posting here, also, we have created a JIRA ticket with Apache Cordova since this seems to be an issue actually related to their code and essentially out of our control to fix. I will post here any updates or fixes that end up working out.  Thanks for your time, I was hoping this would be as simple as working something out with the plugin, but looks like the plugin is fine and it's an Apache Cordova issue to look into. Thanks for an awesome plugin!

**Comment by pwlin** [comment]
No problem at all. You are always welcome to report back your findings, I am sure it will be helpful for other users.

**Comment by slack0129** [comment]
pwlin, Apache got back to me and basically said the issue is with the plugin itself, cordova is handling everything as it should, the fileOpener2 plugin is failing on getUriForFile function call not on the Apache Cordova side. Please see the issue ticket I opened up with them: https://issues.apache.org/jira/browse/CB-12894

**Comment by ppann** [comment]
@slack0129 Try removing & adding the file opener plugin (by `cordova plugin rm` & `cordova plugin add` command) and then building your apk. No clue why, looking into it, but that works for me when I have that same error.

**Comment by sadikyalcin** [comment]
I'm currently having the same issue. Any news with this?

**Comment by ppann** [comment]
For me the issue was that my AndroidManifest.xml didn't have both these provides:

`<provider android:authorities="${applicationId}.provider" android:exported="false" android:grantUriPermissions="true" android:name="android.support.v4.content.FileProvider">
            <meta-data android:name="android.support.FILE_PROVIDER_PATHS" android:resource="@xml/provider_paths" />
        </provider>
        <provider android:authorities="${applicationId}.opener.provider" android:exported="false" android:grantUriPermissions="true" android:name="io.github.pwlin.cordova.plugins.fileopener2.FileProvider">
            <meta-data android:name="android.support.FILE_PROVIDER_PATHS" android:resource="@xml/opener_paths" />
        </provider>`

**Comment by sadikyalcin** [comment]
Re-adding the plugin solved the issue (on debug release as now) - I will confirm release later on.
