### ISSUE TITLE
Ability to remove the share option

### ISSUE THREAD

**Issue by nadakbar** [pwlin/cordova-plugin-file-opener2#139]
Can anyone provide some insight into how i can remove the share button in the bottom left for iOS we do not want to allow users to share the PDF outside of the Viewer

**Comment by pwlin** [comment]
I don't think this question has anything to do with this plugin. Try to ask it on StackOverflow.

**Comment by viktor-shmigol** [comment]
It would be awesome to have this option.

**Comment by nadakbar** [comment]
I agree, I don't really know why this issue was closed. I'm sure the share button in the bottom left is related to this plugin

**Comment by pwlin** [comment]
Believe me, there is no simple way to remove share button! Have you tried to ask a question on StackOverflow? If there is any lead on where to look, I'll be happy to try it out.

**Comment by mubasshir** [comment]
any resolution to this?
