### ISSUE TITLE
<framework src="com.android.support:support-v4:+" /> is breaking builds

### ISSUE THREAD

**Issue by dexterouschen** [pwlin/cordova-plugin-file-opener2#141]
Now 26 is released, a unchecked + will pull down the newest version, which could potentially break builds since not all plugins upgrade dependency to 26 yet.

Also 26 is still in alpha, it's not wise to use it now either.

I know it's pretty easy for any developer to modify plugin.xml but can you either

use `<framework src="com.android.support:support-v4:25.+" />`

or

at least document this issue in README.md so people are aware of it?

**Comment by pwlin** [comment]
Thanks for the heads up I will added to readme on the next release.
