### ISSUE TITLE
In this plugin image not open

### ISSUE THREAD

**Issue by Krishna25Vrinsoft** [pwlin/cordova-plugin-file-opener2#144]
I thing this plugin can't be open images. I am trying to open image with this plugin but its not work. also i am pass MIME type as "application/*" but its not work for image also. I want to open any type of file in my app like .png, .jpg, .pdf, .docx, .txt etc. Can we do this using this plugin?

**Comment by pwlin** [comment]
You need to specify the mime type of the image you want to open. Passing `application/*` will not work,

**Comment by umeshShindepatil** [comment]
HI @pwlin 

Also in my app image not opening, i have pass mime type for png(image/png). Image name is displaying in image preview. but image not opening. In android after select pdf reader giving error alert network issue.
below is my code - 

                   function filetransfer(download_link, fp) {
		    var fileTransfer = new FileTransfer();
		    //alert('111 download_link - ' + download_link);
		    //alert('222 fp - ' + fp);
			fileTransfer.download(download_link, fp,
				function (entry) {
				    //alert('333 URL decode - ' + decodeURI(entry.toURL()));
				    cordova.plugins.fileOpener2.open(
						decodeURI(entry.toURL()),
						fileMimeType,
						{
							error: function (e) {
								window.console.log('document shown');
								component.setState({ downloadingAttachment: false, isLoading: 
                      false, attachementError: 'Opener failed' });
								console.log('Error status: ' + e.status + ' - Error message: ' + 
                      e.message);
							},
							success: function () {
							    //alert('444 success - ');
								window.console.log('document shown');
								component.setState({ downloadingAttachment: false, isLoading: 
                       false, attachementError: '' });
								console.log('file opened successfully');
							}
						}
					);
				},
				function (error) {
				    component.setState({ downloadingAttachment: false, isLoading: false, 
                        attachementError: 'File download failed' });
				},true);
			}
