### ISSUE TITLE
Not working with live URL

### ISSUE THREAD

**Issue by Krishna25Vrinsoft** [pwlin/cordova-plugin-file-opener2#146]
When I am passing live URL of image or any document than its throwing me error as below
Error status: 9 - Error message: File not found.

Can you give me any solution for this.

**Comment by pwlin** [comment]
This plugin does not workURLs. You should save the file locally a then open it.

**Comment by aleksander351** [comment]
So how would you do that? Would you use another plugin to save the file temporarily and open it at the same time or are you planning on adding this functionality?
