### ISSUE TITLE
(Android) Allow save or download the image shown in the image viewer

### ISSUE THREAD

**Issue by danicomas** [pwlin/cordova-plugin-file-opener2#147]
We are not able to save the image in Android

**Comment by pwlin** [comment]
Can you please provide a little bit more information about what exactly you are trying to do? Which Android version? Which "image reader"?

**Comment by danicomas** [comment]
If I open an image with this plugin then It opens an image viewer. It is nice and I can share it. However, there is no button to save this image. (Android 6.X and 7.X)

**Comment by pwlin** [comment]
I have no idea how or shy "save" button does not show. If it opens the image, then I think it's safe to say that this plugin does its job.

**Comment by richardshergold** [comment]
@danicomas I have the same issue - did you manage to get around it?
