### ISSUE TITLE
file-opener2 : support remote open ?

### ISSUE THREAD

**Issue by prolog8** [pwlin/cordova-plugin-file-opener2#148]
Hi,

Does this plugin support remote access file ?

the code like that: 

   cordova.plugins.fileOpener2.open(
			'http://gicdev/app/fe/apk/888.apk',
			'application/vnd.android.package-archive',  { . . . } );

Willow

**Comment by pwlin** [comment]
This plugin does not support opening remote files. You should download the file locally then open it.

**Comment by mubasshir** [comment]
don't you think it should support it?
