### ISSUE TITLE
This plugin cannot open the file inside the HaWei mata9  phone

### ISSUE THREAD

**Issue by MoMoforjw** [pwlin/cordova-plugin-file-opener2#149]
In my project, this plugin can open any file, but only the HAWEImata9 phone model can't open，But the APK has been downloaded to the specified location. I have found it

**Comment by pwlin** [comment]
I am sorry but with this little information, I'm afraid there is no way for me to help you. Please try to provide more details.

**Comment by shnist** [comment]
hi @MoMoforjw, I'm going to close this issue for now. If you are still experiencing the same problem please feel free to reopen this issue and provide a code sample.
