### ISSUE TITLE
deprecated API

### ISSUE THREAD

**Issue by san0suke** [pwlin/cordova-plugin-file-opener2#152]
After adding the plugin, the following error occurs when try to run android:

Error: cmd: Command failed with exit code 1 Error output:
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
C:\Users\rob_c\Documents\Nanuv\Repositiorios\projetoMSI\platforms\android\AndroidManifest.xml:27:9-31 Error:
        Attribute meta-data#android.support.VERSION@value value=(25.3.1) from [com.android.support:appcompat-v7:25.3.1] AndroidManifest.xml:27:9-31
        is also present at [com.android.support:support-v4:26.0.0-alpha1] AndroidManifest.xml:27:9-38 value=(26.0.0-alpha1).
        Suggestion: add 'tools:replace="android:value"' to <meta-data> element at AndroidManifest.xml:25:5-27:34 to override.

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':processDebugManifest'.
> Manifest merger failed : Attribute meta-data#android.support.VERSION@value value=(25.3.1) from [com.android.support:appcompat-v7:25.3.1] AndroidManifest.xml:27:9-31
        is also present at [com.android.support:support-v4:26.0.0-alpha1] AndroidManifest.xml:27:9-38 value=(26.0.0-alpha1).
        Suggestion: add 'tools:replace="android:value"' to <meta-data> element at AndroidManifest.xml:25:5-27:34 to override.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

**Comment by pwlin** [comment]
You must modify `<framework src="com.android.support:support-v4:+" />` in `plugin.xml` to reflect your Android support version.

**Comment by sahyun1** [comment]
that doesn't help, still getting same error

**Comment by gigeos** [comment]
You can use this plugin:
`cordova plugin add cordova-android-support-gradle-release`

Be careful latest release is 26, but you are in 25.3.1 so do it:
`cordova plugin add cordova-android-support-gradle-release --variable ANDROID_SUPPORT_VERSION=25.+`
