### ISSUE TITLE
throwing error: Class not found

### ISSUE THREAD

**Issue by YasirPanjsheri** [pwlin/cordova-plugin-file-opener2#159]
I am using Ionic 3 , I even tried hardcoding the `path` and `mime` but it still throws error, class not found

```
open(){
    this.platform.ready().then(() => {
      this.fileOpener.open(this.path, this.mime).then(() => {
        console.log('file opened i guess')
      }, err => {
        console.log('error open file: ', err)
      });
    });
  }
```

path here is: file:///storage/emulated/0/Download/message.pdf
mime: application/pdf

I also tried this : path -> /storage/emulated/0/Download/message.pdf

**Comment by MatthiasBusch** [comment]
@YasirPanjsheri How did you solve the problem?

**Comment by aryalprakash** [comment]
@YasirPanjsheri  I got this error when I was running --livereload in my ionic app. Not running live reload solved the problem for me.

**Comment by outluch** [comment]
Actually problem solved for me not when I removed --livereload, but when I just restaerted command ionic cordova run .... I think it had to parse config.xml etc
