### ISSUE TITLE
Version >2.0.5 causes Phonegap Build to fail on Android

### ISSUE THREAD

**Issue by WeaponX86** [pwlin/cordova-plugin-file-opener2#161]
Tried Phonegap version cli-6.5.0 and cli-7.0.1.

What went wrong:
Execution failed for task ':processDebugManifest'.
> Manifest merger failed : Attribute meta-data#android.support.VERSION@value value=(25.3.1) from [com.android.support:appcompat-v7:25.3.1] AndroidManifest.xml:27:9-31
  	is also present at [com.android.support:support-v4:26.0.0-alpha1] AndroidManifest.xml:27:9-38 value=(26.0.0-alpha1).
  	Suggestion: add 'tools:replace="android:value"' to <meta-data> element at AndroidManifest.xml:25:5-27:34 to override.

**Comment by andycaoz4** [comment]
Not sure if you've ever figured this one out, but I had the exact same problem, and ended up fixing it by the following:

Check under /platform/android/project.properties for matching android support version. 
This is not accessible via Android Studio or my PHP Storm IDE, and must be edited via notepad.
Example of my own working project.properties:
> cordova.system.library.1=com.android.support:support-v4:25.3.1+
> cordova.gradle.include.1=urbanairship-cordova/myApp-build-extras.gradle
> cordova.system.library.2=com.android.support:appcompat-v7:25.3.1+

If I remember correctly, the failed build support-v4 and appcompat-v7 was something like 24+ or something else not matching

**Comment by omar10594** [comment]
You could use https://github.com/dpa99c/cordova-android-support-gradle-release to fix the error with this plugin or with other plugins.

**Comment by shnist** [comment]
hi @WeaponX86, thanks for raising this issue. We have released a new version of the plugin, 2.1.0, which now allows you to optionally specify the support version at run time. 
`cordova plugin add cordova-plugin-file-opener2  --variable ANDROID_SUPPORT_VERSION={required version}`

This should hopefully resolve all these issues.
