### ISSUE TITLE
File opens in iBooks but doesn't get attached to Mail

### ISSUE THREAD

**Issue by marcelmalitz** [pwlin/cordova-plugin-file-opener2#17]
When I open a PDF I am asked which application to use. If I choose iBooks it opens iBooks and I can view my PDF. In case I choose Mail in order to send an e-mail with the PDF attached it doesn't do anything. It doesn't even open the Mail app.

I tried file opener 2 in version 1.0.11 and I have an iPhone 6 running iOS 8.0 (12A365).

Is that a normal behaviour or do you reckon that it is related to this plugin?

**Comment by mbpmn** [comment]
Hi all,

Same problem as marcelmalitz, it opens correctly in iBooks but it is not attached to the email when opening with Mail app - only the file name in subject...
Any news about this problem?
Thank you.

**Comment by Mark-Leck** [comment]
@mbpmn I found that another plugin similar to this one, called:
cordova-bridge-open
https://github.com/cordova-bridge/open

This attaches the file correctly to everything I have tried it with.
Although it still doesn't solve my ongoing problem.

Hope that helps.

Hi all,

Same problem as marcelmalitz, it opens correctly in iBooks but it is not
attached to the email when opening with Mail app - only the file name in
subject...
Any news about this problem?
Thank you.

—
Reply to this email directly or view it on GitHub
<https://github.com/pwlin/cordova-plugin-file-opener2/issues/17#issuecomment-69186222>
.

**Comment by mbpmn** [comment]
@Mark-Leck 
Thank you so much, this plugin works perfectly on IOS and Android !

**Comment by Mark-Leck** [comment]
@mbpmn Hay no worries, glad it worked for you!

**Comment by marcelmalitz** [comment]
@Mark-Leck I tried the cordova-bridge-open plugin and it works very well. Thank you for this helpful advice.

@pwlin If you would like to get this working with your plugin it might be worth having a look into the cordova-bridge-open plugin code.

Thank you everyone for your help and contribution.

**Comment by pwlin** [comment]
Thank you very much @Mark-Leck and @marcelmalitz  I'm glad Cordova-Bridge worked for you. I will try to see its code and maybe I can fix File-Opener2
