### ISSUE TITLE
Open multiple files?

### ISSUE THREAD

**Issue by adrianomarquess** [pwlin/cordova-plugin-file-opener2#170]
Is it possible to open multiple files?
Otherwise, do you know any other way?

**Comment by shnist** [comment]
hi @adrianomarquess, thanks for raising this issue and sorry no one got back to you. It's not possible to open multiple files in a single command using this plugin. But you could open each file, one after the other. What were you trying to achieve?

**Comment by shnist** [comment]
closing this ticket due to inactivity. feel free to reopen if you still require assistance

**Comment by tho-masn** [comment]
I have the same requirement.
Let's say I have multiple files on a screen (images, pdfs) and I want to swipe though these images/files. As far as I know, this is not possible with this plugin, right? Closing an image/file and open another one seems a bit unhandy.
Are there any plans to support this?

Thanks for this awesome plugin by the way 🙌
