### ISSUE TITLE
Setup "framework" to prevent error on building

### ISSUE THREAD

**Issue by Takkuz** [pwlin/cordova-plugin-file-opener2#178]
As someone points out new version of Gradle breaks building process on Cordova version <6.3
This is the only plugin in my project with this line: `<framework src="com.android.support:support-v4:+" />`

This is the comment that I refer to: https://issues.apache.org/jira/browse/CB-13497?focusedCommentId=16224447&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-16224447

Locally I can set cordova-android to 6.3 but on PhoneGap:Build I'm unable to do it.

**Comment by shnist** [comment]
hi @Takkuz, thanks for raising this issue. This has been resolved in version 2.1.0 which allows you to fix this by installing the plugin in the following manner:
```
cordova plugin add cordova-plugin-file-opener2  --variable ANDROID_SUPPORT_VERSION={required version}
```
e.g. `cordova plugin add cordova-plugin-file-opener2 --variable ANDROID_SUPPORT_VERSION=27.+`
