### ISSUE TITLE
It works for sandbox but not for app directory

### ISSUE THREAD

**Issue by robertocappa** [pwlin/cordova-plugin-file-opener2#179]
This plugin works great if the file I try to open is located in the sandbox:

ex in iOS.  /var/mobile/containers/Data/Application/XXXXXXXX/Library/NoCloud/test.pdf

But it doesn't work inside the app folder:

ex in iOS. /var/containers/Bundle/Application/XXXXXXXX/YYYYYYYY/test.pdf

No error is thrown, simply nothing happens.

The same problem in Android.

Any idea?

Thanks

**Comment by robertocappa** [comment]
Any idea about this problem? Thanks.

**Comment by shnist** [comment]
hi @robertocappa, thanks for raising this issue and sorry no one got back to you. Would you be able to provide a code snippet from your project? This will help us diagnose the issue.

**Comment by shnist** [comment]
Going to close this ticket due to inactivity. If you still require assistance please feel free to reopen.
