### ISSUE TITLE
In Android 7 and higher versions, file.opener can't normally open the APK file

### ISSUE THREAD

**Issue by l-hwen** [pwlin/cordova-plugin-file-opener2#183]
Error openening file file:///storage/emulated/0/Android/data/io.ionic.starter/files/MyCloud/HelloWorld.apk exposed beyond app through Intent.getData()  
Show no permissions

**Comment by veronicabend** [comment]
Did you get any solution for this? I am experiencing the same problem. Thanks!

**Comment by FinlayDaG33k** [comment]
I am experiencing this issue as well
Android 8.0 using the latest code here on the git

**Comment by shnist** [comment]
hi @l-hwen, thanks for raising this issue and sorry that no one got back to you. There were some fixes around opening APK files that landed in version `2.1.0`. If you can please update to the latest version and see if the issue is resolved for you.

**Comment by shnist** [comment]
closing this ticket due to inactivity. I believe the issue was resolved in `2.1.0` anyway. Please feel free to reopen if you still require assistance.

**Comment by 1106991880** [comment]
i am sad , 提示：  file:///storage/emulated/0/test.txt exposed beyond app through Intent.getData()
