### ISSUE TITLE
Unable to open files on Android 5

### ISSUE THREAD

**Issue by Polm90** [pwlin/cordova-plugin-file-opener2#188]
Hi,
I'm using the 2.0.19 plugin version.
Cordova 7.0.1 and cordova-android 6.4.0.
I'm trying to download a remote file (image and/or pdf) and trying to open it.
I'm sure that the file I'm trying to open is currently on the device because I'm also trying to post it to a server and it arrives properly (I also checked with the Android Studio Device Explorer tool)
Using Android 6 or later all works properly.
When I use Android 5 (I haven't tried prior versions) the app cannot open the files.
The plugin says "Ok" and execs the successCallback, but the phone says that there is no image or that the pdf is corrupted (on an emulator, the image is blank without size).

Someone could help me?

Thank you!

**Comment by Polm90** [comment]
Resolved installing the plugin via git and not via npm
(cordova plugin add https://github.com/pwlin/cordova-plugin-file-opener2). The version number is the same but the code is not.

**Comment by wushaojun315** [comment]
Thanks a lot! I got the same problem, and fixed it with your solution.

**Comment by skar3** [comment]
I have this problem, tried installing from git, but nothin, any ideas?

**Comment by wushaojun315** [comment]
Sorry, no idea!


I get the right result by installing from git.


You can hava a check at the path your file, whether it is right or not!



 




------------------ 原始邮件 ------------------
发件人: "Pietro"<notifications@github.com>;
发送时间: 2018年3月5日(星期一) 晚上7:54
收件人: "pwlin/cordova-plugin-file-opener2"<cordova-plugin-file-opener2@noreply.github.com>;
抄送: "吴少军"<1113750080@qq.com>; "Comment"<comment@noreply.github.com>; 
主题: Re: [pwlin/cordova-plugin-file-opener2] Unable to open files onAndroid 5 (#188)




I have this problem, tried installing from git, but nothin, any ideas?

**Comment by cmartin81** [comment]
I also had the same problem.  Fixed by installing from git. It could be a good ide not to install the master branch but from the lates commit.

    cordova plugin add https://github.com/pwlin/cordova-plugin-file-opener2#681d39b140c9d4ae0d8c8f68000515e16ebb9eba

**Comment by krookten14** [comment]
For those who might be having issues when removing the other plugin and then adding the github one. I suggest you run this command:

`cordova plugin add https://github.com/pwlin/cordova-plugin-file-opener2 --save --force`

**Comment by shnist** [comment]
hi @Polm90, thanks for raising this issue. There were a number of fixes for android that were present in master, but had not been published in a new npm release. This has now been done and a new release, 2.1.0, now contains these fixes. If you update to this version your Android problems should hopefully now be resolved.
