### ISSUE TITLE
FileUriExposedException when opening a downloaded APK in Android 8 using version 2.0.19

### ISSUE THREAD

**Issue by veronicabend** [pwlin/cordova-plugin-file-opener2#189]
Hi,

I have installed this plugin to open an APK I download, but I am getting an error of FileUriExposedException. From other issues I read, this should not happen, maybe I am doing something wrong? 

This is from the log:

`01-10 17:29:03.430  7700  7789 E PluginManager: Uncaught exception from plugin
01-10 17:29:03.430  7700  7789 E PluginManager: android.os.FileUriExposedException: file:///storage/emulated/0/download/Myapp.apk exposed beyond app through Intent.getData()
01-10 17:29:03.430  7700  7789 E PluginManager: 	at android.os.StrictMode.onFileUriExposed(StrictMode.java:1958)
01-10 17:29:03.430  7700  7789 E PluginManager: 	at android.net.Uri.checkFileUriExposed(Uri.java:2348)
01-10 17:29:03.430  7700  7789 E PluginManager: 	at android.content.Intent.prepareToLeaveProcess(Intent.java:9766)
01-10 17:29:03.430  7700  7789 E PluginManager: 	at android.content.Intent.prepareToLeaveProcess(Intent.java:9720)
01-10 17:29:03.430  7700  7789 E PluginManager: 	at android.app.Instrumentation.execStartActivity(Instrumentation.java:1609)
01-10 17:29:03.430  7700  7789 E PluginManager: 	at android.app.Activity.startActivityForResult(Activity.java:4472)
01-10 17:29:03.430  7700  7789 E PluginManager: 	at org.apache.cordova.CordovaActivity.startActivityForResult(CordovaActivity.java:342)
01-10 17:29:03.430  7700  7789 E PluginManager: 	at android.app.Activity.startActivityForResult(Activity.java:4430)
01-10 17:29:03.430  7700  7789 E PluginManager: 	at android.app.Activity.startActivity(Activity.java:4791)
01-10 17:29:03.430  7700  7789 E PluginManager: 	at android.app.Activity.startActivity(Activity.java:4759)
01-10 17:29:03.430  7700  7789 E PluginManager: 	at io.github.pwlin.cordova.plugins.fileopener2.FileOpener2._open(FileOpener2.java:131)
01-10 17:29:03.430  7700  7789 E PluginManager: 	at io.github.pwlin.cordova.plugins.fileopener2.FileOpener2.execute(FileOpener2.java:67)
01-10 17:29:03.430  7700  7789 E PluginManager: 	at org.apache.cordova.CordovaPlugin.execute(CordovaPlugin.java:98)
01-10 17:29:03.430  7700  7789 E PluginManager: 	at org.apache.cordova.PluginManager.exec(PluginManager.java:132)
01-10 17:29:03.430  7700  7789 E PluginManager: 	at org.apache.cordova.CordovaBridge.jsExec(CordovaBridge.java:57)
01-10 17:29:03.430  7700  7789 E PluginManager: 	at org.apache.cordova.engine.SystemExposedJsApi.exec(SystemExposedJsApi.java:41)
01-10 17:29:03.430  7700  7789 E PluginManager: 	at org.chromium.base.SystemMessageHandler.nativeDoRunLoopOnce(Native Method)
01-10 17:29:03.430  7700  7789 E PluginManager: 	at org.chromium.base.SystemMessageHandler.handleMessage(SystemMessageHandler.java:41)
01-10 17:29:03.430  7700  7789 E PluginManager: 	at android.os.Handler.dispatchMessage(Handler.java:105)
01-10 17:29:03.430  7700  7789 E PluginManager: 	at android.os.Looper.loop(Looper.java:164)
01-10 17:29:03.430  7700  7789 E PluginManager: 	at android.os.HandlerThread.run(HandlerThread.java:65)
`

This is how I call the plugin:

`
cordova.plugins.fileOpener2.open(
 entry.toURL(),
 'application/vnd.android.package-archive',
 {
 error: function(e){
   console.log('Error status: ' + e.status + ' Error Message: ' + e.message);
   alert('Error launching the app update: ' + e.message);                                                                        
  },
  success: function(){
   console.log('Successfully opened file');
  }
}
);																			    			
`

The alert I get shows undefined for e.message

I have android-targetSdkVersion set to 26 in my config.xml and I am testing this in an emulator with Android 8.

Thanks for any help.

**Comment by zhang-weifu** [comment]
Hi @veronicabend 
I checked the code. found a bug about versions. you can change the code of line 107
`if((Build.VERSION.SDK_INT >= 23 && !contentType.equals("application/vnd.android.package-archive")) || (**(Build.VERSION.SDK_INT == 24 || Build.VERSION.SDK_INT == 25)** && contentType.equals("application/vnd.android.package-archive"))) `
to 
`if((Build.VERSION.SDK_INT >= 23 && !contentType.equals("application/vnd.android.package-archive")) || (**Build.VERSION.SDK_INT > Build.VERSION_CODES.N** && contentType.equals("application/vnd.android.package-archive"))) `

good luck

**Comment by veronicabend** [comment]
Thank you!

I didn't want to make changes in the plugin code myself, so I tried installing it directly from GitHub like this:

cordova plugin add https://github.com/pwlin/cordova-plugin-file-opener2

And it worked! I did this because I saw updated code at github, but when I installed the plugin normally using:

cordova plugin add cordova-plugin-file-opener2

it would have old code with the error as you mentioned. 

In both cases, it shows version installed as 2.0.19, but when installing from GitHub, there is no FileUriExposedException.

**Comment by coolara** [comment]
close 吧

**Comment by JuliBy** [comment]
Same problem here. The source (Android - FileOpener2.java) in the plugin is not equal with the source in the repository. Is it possible to fix the problem? 

Thanks and greetings

**Comment by fcamblor** [comment]
So much forks of the project on latest month, seeming to target this issue https://github.com/pwlin/cordova-plugin-file-opener2/network

... and nobody proposed a Pull Request :/

**Comment by Kevin4016** [comment]
> Thank you!
> 
> I didn't want to make changes in the plugin code myself, so I tried installing it directly from GitHub like this:
> 
> cordova plugin add https://github.com/pwlin/cordova-plugin-file-opener2
> 
> And it worked! I did this because I saw updated code at github, but when I installed the plugin normally using:
> 
> cordova plugin add cordova-plugin-file-opener2
> 
> it would have old code with the error as you mentioned.
> 
> In both cases, it shows version installed as 2.0.19, but when installing from GitHub, there is no FileUriExposedException.

work for me! help me a lot!

**Comment by Eduwardo** [comment]
> Thank you!
> 
> I didn't want to make changes in the plugin code myself, so I tried installing it directly from GitHub like this:
> 
> cordova plugin add https://github.com/pwlin/cordova-plugin-file-opener2
> 
> And it worked! I did this because I saw updated code at github, but when I installed the plugin normally using:
> 
> cordova plugin add cordova-plugin-file-opener2
> 
> it would have old code with the error as you mentioned.
> 
> In both cases, it shows version installed as 2.0.19, but when installing from GitHub, there is no FileUriExposedException.

Fixed too. Thanks!

**Comment by Kevin4016** [comment]
My pleasure~




------------------ 原始邮件 ------------------
发件人: "Eduardo Mihalache"<notifications@github.com>;
发送时间: 2018年11月6日(星期二) 下午4:52
收件人: "pwlin/cordova-plugin-file-opener2"<cordova-plugin-file-opener2@noreply.github.com>;
抄送: "米输入..."<401609910@qq.com>; "Comment"<comment@noreply.github.com>; 
主题: Re: [pwlin/cordova-plugin-file-opener2] FileUriExposedException whenopening a downloaded APK in Android 8 using version 2.0.19 (#189)



 
Thank you!
 
I didn't want to make changes in the plugin code myself, so I tried installing it directly from GitHub like this:
 
cordova plugin add https://github.com/pwlin/cordova-plugin-file-opener2
 
And it worked! I did this because I saw updated code at github, but when I installed the plugin normally using:
 
cordova plugin add cordova-plugin-file-opener2
 
it would have old code with the error as you mentioned.
 
In both cases, it shows version installed as 2.0.19, but when installing from GitHub, there is no FileUriExposedException.
  
Fixed too. Thanks!

**Comment by shnist** [comment]
the android fixes have now been released under version 2.1.0. Hopefully this should resolve the issues now. I'm going to close this issue but feel free to reopen if there are still problems.
