### ISSUE TITLE
Add a sample index

### ISSUE THREAD

**Issue by benmarte** [pwlin/cordova-plugin-file-opener2#19]
It would be nice if you included a simple index page that users can see how to get this to work, I've spent many hours trying to get this to work but have been unsuccessful (phonegap n00b here). 

Something simple like this: https://github.com/triceam/phonegap-plugins/blob/master/iOS/ExternalFileUtil/sample/www/index.html which is what I've been using just to get an idea how the plugin works.

Thanks.

**Comment by pwlin** [comment]
@benmarte Thanks for your suggestion, I will do this as soon as possible.

**Comment by shnist** [comment]
Going to close this issue for now as the README has been substantially modified with better examples.
