### ISSUE TITLE
add Tags to the Repository

### ISSUE THREAD

**Issue by BigJenson** [pwlin/cordova-plugin-file-opener2#191]
Hi, i just wanted to give you some feedback to this repository.
It would be really nice if you could add Tags for the Version you added to NPM, so one can see what exactly will be installed.
I for instance hat the problem that i needed the mimeType fix for IOS. (I thought i was fixed, but the fixed IOS source was not installed -> NPM Version is older than current master).
Maybe im wrong about this but i think it would be better if you set the current Version (master HEAD) to '2.0.19-M or -DEV' and add a Tag to the exact Commit where you added a Version to NPM

**Comment by shnist** [comment]
hi @BigJenson, thanks for the suggestion. I have created a release tag for the new version 2.1.0 and hopefully this will be continued moving forward. All the best
