### ISSUE TITLE
Cant open files on SD-Card

### ISSUE THREAD

**Issue by Yukuza** [pwlin/cordova-plugin-file-opener2#195]
I try to open a file on the inserted SD Card, but I get different errors. 
At first i tried to open `/sdcard/Android/data/{appname}/files/test.txt` and I get error code `9 - File not found`
Since Android 6.0+ its hard to even get the correct SD-Card path (looks like the path contains the serial number (?) ), but i managed to do that. Now i try to open with the "full" path that looks like this: 
`file:///storage/7EC0-0CEC/Android/data/{app-name}/files/`
The error i get now is (without Error Code etc.):
 `Failed to find configured root that contains /storage/7EC0-0CEC/Android/data/{app-name}/files/test.txt`

Any suggestions?

**Comment by iadimitriu** [comment]
Please check #206

**Comment by CarlosAyala** [comment]
I have the same problem. 
I fixed it moving the file to a another folder and opening it.

**Comment by shnist** [comment]
As per my explanation in https://github.com/pwlin/cordova-plugin-file-opener2/pull/206, there isn't a way to read files from the SD Card when it's under an external partition in Android. The best work around would be to copy the file elsewhere as per @CarlosAyala's suggestion. Going to close this issue for now.
