### ISSUE TITLE
Files not opening on iOS

### ISSUE THREAD

**Issue by scottdc** [pwlin/cordova-plugin-file-opener2#2]
Been trying to get this working for a bit now and am stumped. Files do not open but I also do not get an error or anything, nothing happens at all. I've got the event writing to the console and it appears to be firing correctly but I get neither a success or failure message.  I've got this same basic case for multiple file types (pdf, doc, etc.) based on extension and none of them work. 

case 'rtf':
       cordova.plugins.fileOpener2.open(fullPath, 'application/rtf', { 
            error : function(errorObj) { 
                console.log('error - ' + errorObj.status + '  - ' + errorObj.message); 
            },
            success : function () {
                console.log('sucess');  
            }
        });
break;

**Comment by pwlin** [comment]
Try to change plugin's ios source (FileOpener2.m) line:

fileURL  = [NSURL **URLWithString**:path]; 

to:

fileURL  = [NSURL **fileURLWithPath**:path]; 

Does that help?

**Comment by any2info** [comment]
I found the following lines in the FileOpener2.m file:
        //fileURL = [NSURL URLWithString:path];
        fileURL = [NSURL fileURLWithPath:path];

I tried enabling the first line (URLWithString) but this resulted in a crash of my app.

**Comment by pwlin** [comment]
What if you use `fileEntry.toURL()` in your javascript?

**Comment by any2info** [comment]
That solved it. Thank you very much.

**Comment by pwlin** [comment]
Ok great. I will add a note to README file about using `fileEntry.toURL()`

**Comment by ronyrun** [comment]
Hi,

Where to get the fileEntry.toURL()  ?
I don't understand. Do you have an example with fileEntry.toURL() ?

**Comment by elbidone** [comment]
@ronyrun check code below, and if you need more details about File API I recommend following post: [https://www.neontribe.co.uk/cordova-file-plugin-examples/)](https://www.neontribe.co.uk/cordova-file-plugin-examples/))
```javascript
window.resolveLocalFileSystemURL(
  path, 
  function (entry) {
    console.log(entry.toURL());
  }, 
  function (err) {
    $log.debug(err);
  }
);
```

**Comment by Belheni** [comment]
@pwlin and @any2info Can you send me a simple and complete version of opening pdf in ios Please? i really tested all the suggestions(changing in fileOpener, fileEntry.toURL(),fileEntry.toNativeURL()..) and the best version is that i have just a successful message of opening pdf without showing it..I really need a solution for that

**Comment by any2info** [comment]
I use the following helper instance to download and open all sort of files. 
I removed some code that applied to our internal netwerk but you should be able use this. 

I hope this helps anyone out there struggling with this

[download helper example.txt](https://github.com/pwlin/cordova-plugin-file-opener2/files/1421236/download.helper.example.txt)

**Comment by Belheni** [comment]
@any2info Thanks for your hel but i tested your solution carefully after checking if all plugins exist and nothing is showed.. This is my test really i don't know what's the problem..i will be veru thankful if you continue helping me..
[TestSolution.txt](https://github.com/pwlin/cordova-plugin-file-opener2/files/1421676/TestSolution.txt)

**Comment by any2info** [comment]
@Belheni I looked at the code snippet you added and this seems fine to me and should work.
The only thing i could find that is off is your invocation of openFile(entry.toURL()). Shouldn't this be OpenFile(entry.toURL())?

Also the false and headers parameter can be removed because you probably don't need them. Which should be the case if you are downloading directly from a web uri. In my case i needed them because we are no longer downloading files using uri's.

If this still doesn't solve anything, i would be happy to look at more of your code if needed.

**Comment by Belheni** [comment]
I will summarize the situation .. my application consists of an access to a website as webview and when I click on a well defined button, I get the filename and the fileURL through localStorage and I try to open the file pdf with fileOpener2..i always arrive at the message of the success but without displaying the pdf .. finally I found that it is necessary to completely close the window to display the pdf then to reopen the window .. the version in android works perfectly (the pdf is displayed on the window) .. Is there another solution in IOS? thank you so much

**Comment by Belheni** [comment]
@pwlin and @any2info i opened the file in ios but how to detect the click done on the file to close it?or how to detect the closing of the file? 
another question is that how to display file in ios on the window inappbrowser and not under the window inappbrowser (default)? Please help me

**Comment by any2info** [comment]
@Belheni When you want it to open in inappbrowser [this](https://gist.github.com/devgeeks/4982983) should work. Detecting close [this](https://stackoverflow.com/questions/33896026/cordova-ionic-download-file-from-inappbrowser) maybe

**Comment by Belheni** [comment]
@any2info  i work with inappbrowser (for the website) and fileopener2.. i open the PDF file using fileopener2 and it works fines.. my question is how to detect the click done on the file to close it? in android file is displayed on the window inappbrowser but in ios file is displayed under the window inappbrowser.. i want to detect close of PDF to show again the window inappbrowser.. i know that my problem is complicated and i wish that you have a solution

**Comment by any2info** [comment]
@Belheni I am afraid im can't help you with that. Maybe you should start stackoverflow item for that since this is no longer is related to files not opening on ios

**Comment by pyroxiano** [comment]
The issue I had was with the CGRect passed into presentOpenInMenuFromRect. Changing line 89 to: 

CGRect rect = CGRectMake( cont.view.bounds.size.width / 2, 20, 166, 235 );

Worked, and made the dialog appear slightly offset from the screen center.

**Comment by juansaa** [comment]
Hola estoy creando mi app online con PhonegapBuild.
Como agrego el plugin en el config.xml?

Hello, I am creating my online app with PhonegapBuild.
How do I add the plugin in the config.xml?
