### ISSUE TITLE
Additional method?

### ISSUE THREAD

**Issue by sikron** [pwlin/cordova-plugin-file-opener2#20]
Hi,
it would be great, if you could add an additional method to check, whether there is any app installed, which can open a file by mimetype. E.g. like "canOpenFile(...)" in "Smile-SA/cordova-plugin-fileopener".

Big thx for this plugin, it helped me a lot!

**Comment by pwlin** [comment]
Hi @sikron,
Thanks for your suggestion. The problem I am facing at the moment is that I don't own any iDevices, so any extra method I implement would be Android-only. I think this might be a problem in the long run, as normally PhoneGap/Cordova functions should be cross-platform. But on the other hand, I already have 2 Android-only functions (`uninstall` and `appIsInstalled`) so I really have some mix feelings about adding more Android-only functions.

What are your thought? Do you need this particular function cross-platform or only on Android?

**Comment by sikron** [comment]
Hi,
As this plugin also supports iOS i thought that you would also know how to implement it in iOS. 
I agree with you, that both platforms should support the whole functionality, so a further Android-specific version would not be in the cross-platform sense.
I actually would need it in Android and iOS of course :-) Maybe i can ask a iOS-dev-colleague for help. I will come back to you again.

bye!

**Comment by sikron** [comment]
Hi,
my colleague tells me, that on iOS this is not so straight-forward. On iOS you have this UIDocumentInteractionController, which accepts files and either opens them directly or shows a grey modal containing apps, which can open the file. But it does not provide a "canOpen" functionality unfortunately.

My actual use-case was to check, whether the device can open a file, so to know, whether to download it in the first place (and thus maybe save megabytes of data-traffic).

So from my point of view, no common denominator here, unfortunately. :-(
