### ISSUE TITLE
Cordova build fails due to "com.android.support:support-v4" version

### ISSUE THREAD

**Issue by prudnikovdbison** [pwlin/cordova-plugin-file-opener2#207]
Cordova build fails with exception:
`:processDebugResourcesERROR: In <declare-styleable> FontFamilyFont, unable to find attribute android:fontVariationSettings
ERROR: In <declare-styleable> FontFamilyFont, unable to find attribute android:ttcIndex`

This can be fixed in plugin.xml by upgrading 
`<framework src="com.android.support:support-v4:+" />`
to a higher version like 27.0.1 or downgrading to 23.+.

Examples (tested):
`<framework src="com.android.support:support-v4:27.0.1" />`
or
`<framework src="com.android.support:support-v4:23.+" />`

**Comment by roby65** [comment]
Use [this](https://github.com/dpa99c/cordova-android-support-gradle-release) cordova plugin to fix this problem
I forced version 27.0.0 and it works flawlessy:

`cordova plugin add cordova-android-support-gradle-release  --variable ANDROID_SUPPORT_VERSION=27.0.0`

**Comment by Fieel** [comment]
I don't know what happened but i managed to build even though i didn't touch my project. I think this is some kind of compatibility-issue and not a real bug - i'm happily using the plugin without any error now!

**Comment by sadikyalcin** [comment]
@roby65 That only solves half of the issue. Using that plugin keep crashes the app on launch. Only way to get it working is running via Android Studio.

Proper way to solve this is seen on this [answer](https://stackoverflow.com/questions/49162538/running-cordova-build-android-unable-to-find-attribute-androidfontvariation) on stack.

Create a `build-extras.gradle` file in `platforms/android` and add the following in that file.
 
```
configurations.all {
    resolutionStrategy {
        force 'com.android.support:support-v4:27.1.0'
    }
}
```

**Comment by AppwareDev** [comment]
I tried every suggestion to fix this but in the end simply updating ionic and cordova fixed it:
`npm install -g ionic cordova`

You might also need to remove and add the Android platform again:
`ionic cordova platform rm android`
`ionic cordova platform add android`

**Comment by mmfilesi** [comment]
cordova-android-support-gradle-release and build-extras.gradle conflicts with other plugins. Better not install this plugin.

**Comment by shnist** [comment]
version 2.1.0 should now resolve this issue as you can optionally set a compatible android_support_version at installation time, e.g. 
`cordova plugin add cordova-plugin-file-opener2  --variable ANDROID_SUPPORT_VERSION=27.+`
