### ISSUE TITLE
Cannot display files normally, such as pictures, pdf, doc

### ISSUE THREAD

**Issue by preservance717** [pwlin/cordova-plugin-file-opener2#209]
`
this.fileOpener.open((this.file.externalRootDirectory + 'quality/123.jpg'), 'image/jpeg')
      .then(() => { })
      .catch(e => {
      });
`
file has found, but can't display normally. 
The following figure shows the photo
![123](https://user-images.githubusercontent.com/18299850/38713721-32776afe-3f05-11e8-849b-b7747ced3270.png)

this is my **ionic info**
![ionic-info](https://user-images.githubusercontent.com/18299850/38713802-b9428c94-3f05-11e8-996e-4563b420f7f5.png)

i don't know why. i need help

**Comment by shnist** [comment]
hi @preservance717, thanks for raising this issue. Were you able to resolve your issue in the end?

**Comment by preservance717** [comment]
yes. i solve this .
first, i use `fileTransfer`, then use`fileOpener`.
![image](https://user-images.githubusercontent.com/18299850/50162880-4a2ce500-031a-11e9-9694-5df88f56e096.png)

**Comment by shnist** [comment]
great, glad you were able to resolve your issue.
