### ISSUE TITLE
After opening a file nothing happens

### ISSUE THREAD

**Issue by anurag0707** [pwlin/cordova-plugin-file-opener2#212]
Environment
iOS: 9
xCode: 9.3.1
cordova: 8.0.0
cordova-ios: 4.5.5

Plugin version:  
cordova-plugin-file-opener2 2.0.19 "File Opener2"
cordova-plugin-file-transfer 1.7.1 "File Transfer"

After opening a file the code executes fine but there is no provision to open it and even it doesn't show where it is getting downloaded

**Comment by darylldawn** [comment]
Try taking a look at issue [#145](https://github.com/pwlin/cordova-plugin-file-opener2/issues/145) if it is related.

**Comment by shnist** [comment]
hi @anurag0707, were are you able to resolve your issue?

**Comment by shnist** [comment]
Going to close this as a duplicate of https://github.com/pwlin/cordova-plugin-file-opener2/issues/67.
