### ISSUE TITLE
Unable to build, attribute 'android:appComponentFactory' not found

### ISSUE THREAD

**Issue by dturakhia** [pwlin/cordova-plugin-file-opener2#216]
When I add this plugin and build, I get the following error message while compiling.

 `error: No resource identifier found for attribute 'appComponentFactory' in package 'android'`

When I remove the plugin, it does not throw this error and compiles perfectly. Any idea what is going wrong?

My Project info is

Cordova-version : 7.1.0
Android-version : 6.3.0

**Comment by andrewsduarte3** [comment]
Same here

**Comment by andrewsduarte3** [comment]
Install this plugin: https://github.com/dpa99c/cordova-android-support-gradle-release
And you are good to go!

**Comment by jomendez** [comment]
@andrewsduarte3 Installing cordova-android-support-gradle-release solved the issue for me.
I ran the command:
cordova plugin add cordova-android-support-gradle-release
as indicated in the documentation, and everything is working now.
Thanks

**Comment by shnist** [comment]
hi @dturakhia, thanks for raising this issue. There is a fix that was released in version 2.1.0 that should resolve this issue. You can now optionally set the android version support at installation:

`cordova plugin add cordova-plugin-file-opener2  --variable ANDROID_SUPPORT_VERSION={required version}`

the build error on android should then disappear.
