### ISSUE TITLE
An error occurred while packaging:Tag <provider> attribute authorities has invalid character '$'.

### ISSUE THREAD

**Issue by 1308774130** [pwlin/cordova-plugin-file-opener2#217]
Hi. I'm trying to build cordova project and get the following error:

> [aapt] C:\Users\TNQD005\Desktop\JSDGJ update\ShortSightednessDoctor\platforms\android\ant-build\AndroidManifest.xml:78: Tag <provider> attribute authorities has invalid character '$'.
> BUILD FAILED
> C:\dev\sdk\tools\ant\build.xml:649: The following error occurred while executing this line:
> C:\dev\sdk\tools\ant\build.xml:694: null returned: 1
> Total time: 7 seconds
> C:\Users\TNQD005\Desktop\JSDGJ update\ShortSightednessDoctor\platforms\android\cordova\node_modules\q\q.js:126
>                    throw e;
>                          ^
> Error code 1 for command: cmd with args: /s,/c,ant,debug,-f,C:\Users\TNQD005\Desktop\JSDGJ update\ShortSightednessDoctor\platforms\android\build.xml,-Dout.dir=ant-build,-Dgen.absolute.dir=ant-gen
> Error: cmd: Command failed with exit code 8
>     at ChildProcess.whenDone (C:\dev\nodejs\node_global\node_modules\cordova\node_modules\cordova-lib\src\cordova\superspawn.js:135:23)
    at ChildProcess.emit (events.js:98:17)
    at maybeClose (child_process.js:756:16)
    at Process.ChildProcess._handle.onexit (child_process.js:823:5)

I have spent the past a whole day trying to find a solution for this problem.
if i add cordova-plugin-file-opener2 plugin, AndroidManifest.xml will be automatically add
> <provider android:authorities="${applicationId}.fileprovider" android:exported="false" android:grantUriPermissions="true" android:name="android.support.v4.content.FileProvider">
            <meta-data android:name="android.support.FILE_PROVIDER_PATHS" android:resource="@xml/file_paths" />
        </provider>
so when i pack it ,I got the error message above
How can I fix this problem?

**Comment by godoyrw** [comment]
I had the same error after updating the android SDK to the latest build tools.

The tools\ant\build.xml script does not contain any references for the tools.

This can be solved, by adding the tools to the build.xml and point to the correct path. For me this was build-tools\22.0.1

Please compare and update the tool section in build.xml

`
<property name="android.tools.dir" location="${sdk.dir}/tools" />
<property name="android.platform.tools.dir" location="${sdk.dir}/platform-tools" />

<property name="android.buildtools.dir" location="${sdk.dir}/build-tools/22.0.1" />

<condition property="exe" value=".exe" else=""><os family="windows" /></condition>
<condition property="bat" value=".bat" else=""><os family="windows" /></condition>
<property name="adb" location="${android.platform.tools.dir}/adb${exe}" />
<property name="lint" location="${android.tools.dir}/lint${bat}" />
<property name="zipalign" location="${android.buildtools.dir}/zipalign${exe}" />
<property name="aidl" location="${android.platform.tools.dir}/aidl${exe}" />
<property name="aapt" location="${android.buildtools.dir}/aapt${exe}" />
<property name="dx" location="${android.buildtools.dir}/dx${bat}" />
<property name="renderscript" location="${android.buildtools.dir}/llvm-rs-cc${exe}"/>
<property name="lint" location="${android.tools.dir}/lint${bat}" />`

**Comment by 1308774130** [comment]
@godoyrw thanks for your help,but my build.xml does not give me too much valid content,I didn't see such a sentence  so I don't know how to proceed
`
<?xml version="1.0" encoding="UTF-8"?>
<project name="CordovaApp" default="help">

    <property file="local.properties" />

    <property file="ant.properties" />

    <property environment="env" />
    <condition property="sdk.dir" value="${env.ANDROID_HOME}">
        <isset property="env.ANDROID_HOME" />
    </condition>
    <loadproperties srcFile="project.properties" />

    <fail
            message="sdk.dir is missing. Make sure to generate local.properties using 'android update project' or to inject it through the ANDROID_HOME environment variable."
            unless="sdk.dir"
    />

    <import file="custom_rules.xml" optional="true" />

    <import file="${sdk.dir}/tools/ant/build.xml" />

</project>

`
and i'm using android 4.4; Cordova 4.1.2;does this have something to do with my version?

**Comment by godoyrw** [comment]
Which version are you using Android build tools!?

**Comment by shnist** [comment]
hi @1308774130, thanks for raising this issue. Were you able to resolve it in the end?

**Comment by shnist** [comment]
After some investigation this appears to be an issue related to Eclipse, https://stackoverflow.com/questions/42040570/tag-provider-attribute-authorities-has-invalid-character-androidmanifest, which is no longer supported for Android development. I would advise using Android Studio instead, as per the comment on stackoverflow.
