### ISSUE TITLE
Publishing a new version

### ISSUE THREAD

**Issue by y-lohse** [pwlin/cordova-plugin-file-opener2#219]
Hi, and thanks for the plugin!

The version that is currently distributed doesn't have all the changes that are in `master` and some of them are important bugfixes. Would it be possible to release a new version of the plugin?

If there's anything I can do to help with that, let me know.

**Comment by shnist** [comment]
Hi @y-lohse,

A new version, 2.1.0 has now been published and includes the outstanding fixes that were present in `master`. Let me know if you have any issues with it!

**Comment by y-lohse** [comment]
Thanks!
