### ISSUE TITLE
Open PDF with Adobe not able provide full permission

### ISSUE THREAD

**Issue by subashdbc** [pwlin/cordova-plugin-file-opener2#222]
Hello,

I am using this code to open PDF file with Adobe Acrobat,  below code opens the file as expected. 

`this.cordova.plugins.fileOpener2.open(
	filePath, 
	'application/pdf', 
	 {
	    error : function(){ }, 
	    success : function(){ } 
	  } 
);`

But what is the issue is, I have a PDF file which can be edited through Adobe Acrobat. When I open the file stright away from the Adobe Acrobat app I can able to edit and when I press the back button it saves automatically. But when I open the PDF file from the cordova application it opens and I can also edit that, but it fails to save automatically. Do I need to set any extra permission or anyother way? 

Thanks in advance!

**Comment by Langstra** [comment]
Related to #221

**Comment by subashdbc** [comment]
Thanks for your help. It works like a charm :)
