### ISSUE TITLE
Build failed cordova 8

### ISSUE THREAD

**Issue by juanpablogd** [pwlin/cordova-plugin-file-opener2#227]
![captura](https://user-images.githubusercontent.com/2925728/45449445-d768f980-b69a-11e8-8f6c-4a77a3b48bdc.PNG)

**Comment by cikcoh** [comment]
hi @juanpablogd hv u solved this yet?

**Comment by juanpablogd** [comment]
Yes, install this plugin 

cordova plugin add cordova-android-support-gradle-release --variable 

regrads
