### ISSUE TITLE
File not opened in ios (ipad v 8.3)

### ISSUE THREAD

**Issue by aravintha** [pwlin/cordova-plugin-file-opener2#23]
I am using this file opener plugin for my phonegap application. PDF file is opened in android devices but in ios the file is not opened but alert show file opened successfully.

	var fileName = "file:///storage/emulated/0/sample/one/test.pdf";
	if(device.platform == "ios"){
	var iosDirectory = "file:///var/mobile/Containers/Data/Application/EC83E4C-338B-48BA-AE4974F6A407D2A0/Documents/";
	fileName = iosDirectory+"sample/one/test.pdf";
	}
        cordova.plugins.fileOpener2.open(fileName,
    'application/pdf', 
    { 
        error : function(e) { 
            alert('Error status: ' + e.status + ' - Error message: ' + e.message);
        },
        success : function () {
            alert('file opened successfully');                
        }
    }
    );

Please guide me to solve this issue.

**Comment by danicastanos** [comment]
@aravintha How did you solve it?

**Comment by aravintha** [comment]
i used the file system to get the correct path of the file and passed it to
the file opened plugin solved the issue.

Thanks
Aravin.A
