### ISSUE TITLE
Is this plugin supported by members ?

### ISSUE THREAD

**Issue by modimoni** [pwlin/cordova-plugin-file-opener2#231]
I am evaluating this plugin, but don't see any update for last 1 year from members.  Do we have some one actively looking at it.

Thanks
Modi

**Comment by pierresh** [comment]
Unfortunately no, the branch Master on Github contains critical bugfixes that are not published on npm...........

https://github.com/pwlin/cordova-plugin-file-opener2/issues/189

**Comment by shnist** [comment]
I will be helping to maintain this project. This will mostly be focused around maintenance.
