### ISSUE TITLE
Error: exec proxy not found for :: FileOpener2 :: open

### ISSUE THREAD

**Issue by krookten14** [pwlin/cordova-plugin-file-opener2#233]
I've tried so many methods to open my document file (pdf, xls, docx) and one method is using _cordova-plugin-file-opener2_
I've already tried adding the plugin where the link should be in github, but it still doesn't work. When I tried using it, It shows this error:
`Error: exec proxy not found for :: FileOpener2 :: open`
`Error status: undefined - Error message: undefined`

Am I missing something?

P.S. I've already tried _cordova-plugin-file_ and _cordova-plugin-file-transfer_ but still doesn't work. And I'm confident that the FileOpener2 is much more convenient than the other plugins to open a file.

**Comment by shnist** [comment]
Hi @krookten14 , what platform are you trying to use this on? Android or iOS? Usually you receive an error like that when you running the `browser` platform, which this plugin does not support.

**Comment by shnist** [comment]
Possible duplicate of https://github.com/pwlin/cordova-plugin-file-opener2/issues/205.

**Comment by krookten14** [comment]
> Hi @krookten14 , what platform are you trying to use this on? Android or iOS? Usually you receive an error like that when you running the `browser` platform, which this plugin does not supp

**Comment by konasunny** [comment]
> Hi @krookten14 , what platform are you trying to use this on? Android or iOS? Usually you receive an error like that when you running the `browser` platform, which this plugin does not support.

i too have the same issue.. but i run my app in browser, android and ios.. after installing the plugin my app is not loading. can we disable the plugin just in browser?
and also i am getting a warning message in browser
"DevTools failed to parse SourceMap: http://localhost:8001/plugins/cordova-plugin-file-opener2/src/browser/FileSaver.min.js.map"
