### ISSUE TITLE
Build failed in iOS for the latest code

### ISSUE THREAD

**Issue by fhls** [pwlin/cordova-plugin-file-opener2#236]
Not a problem with the released version 2.1.0. It is when build with the latest code from git the console will give the error below:

/Users/vsts/agent/2.142.1/work/4/s/platforms/ios/App/Plugins/cordova-plugin-file-opener2/FileOpener2.m:47:27: error: use of undeclared identifier 'cont'
rect = CGRectMake(0, 0, cont.view.bounds.size.width, cont.view.bounds.size.height);
                                     ^
/Users/vsts/agent/2.142.1/work/4/s/platforms/ios/App/Plugins/cordova-plugin-file-opener2/FileOpener2.m:47:56: error: use of undeclared identifier 'cont'
rect = CGRectMake(0, 0, cont.view.bounds.size.width, cont.view.bounds.size.height);

1 warning and 2 errors generated.

Regards

**Comment by videmort** [comment]
+1

**Comment by rpanadero** [comment]
+1

**Comment by shnist** [comment]
hi @fhls, thanks for raising this issue. Is there a reason why you are using the latest git version and not version 2.1.0? Only released versions are stable and should be used. Is it because you wish to use the new position option?

**Comment by shnist** [comment]
i've pushed a fix for this. You should no longer receive the compilation errors.

**Comment by fhls** [comment]
hi @shnist, thank you for your quick fix. Previously we use a url pointing to this plugin repository (because of this issue #204) and then we encounter this build error in our automated build. We already change to the stable released version.
