### ISSUE TITLE
Android build failed for cordova-plugin-file-opener2 giving Error - A plugin you are using requires a preference: ANDROID_SUPPORT_V4_VERSION

### ISSUE THREAD

**Issue by umeshShindepatil** [pwlin/cordova-plugin-file-opener2#238]
Android build failed for cordova-plugin-file-opener2 giving Error - A plugin you are using requires a preference: ANDROID_SUPPORT_V4_VERSION

Hi
Getting error for android build - Error - A plugin you are using requires a preference: ANDROID_SUPPORT_V4_VERSION.

below code is in my config -
<gap:plugin name="cordova-plugin-file-opener2" source="npm">

plz help.
Thanks!

**Comment by fer1994** [comment]
I have this line in config.xml and dont work.

<plugin name="cordova-plugin-file-opener2" spec="^2.1.0">
     <variablename="ANDROID_SUPPORT_V4_VERSION" value="27.+" />
</plugin>

**Comment by shnist** [comment]
hi @fer1994 , how are you building your project? With phonegap build? Or just on the command line?

**Comment by fer1994** [comment]
I build in command line, thats is the problem. I cant change manually the build.gradle

**Comment by shnist** [comment]
Hi @fer1994, if you could send me some more information about your project that would help me understand the issue you are having. Firstly can you show me the output of running this command in your project:

```bash
cordova info
```

and if you can also tell me what cordova command you are using when trying to build the app and the exact error that is being outputted that would be great.

**Comment by umeshShindepatil** [comment]
Hi All,
Thanks for the reply,
It's worked for me remove and add plugin in config xml.

removed - <gap:plugin name="cordova-plugin-file-opener2" source="npm" />
add - <plugin spec="https://github.com/neptsoft/cordova-plugin-file-opener2" source="git" />

**Comment by shnist** [comment]
@umeshShindepatil glad you solved your issue. @fer1994 can you send me a copy of the exact error you are getting.

**Comment by shnist** [comment]
@fer1994 i believe I have found the root cause of the issue https://github.com/phonegap/phonegap-plugin-barcodescanner/issues/616#issuecomment-372690215. 

Looks like Cordova 6 does not support the fix for the android support version build issue (https://github.com/pwlin/cordova-plugin-file-opener2/pull/234). 

If you can, try upgrading your Cordova CLI to at least version 7 `npm i cordova@latest -g`. That should hopefully resolve your issue. I'll also update the README

**Comment by shnist** [comment]
hi @fer1994, the link to the issue was just a reference to what I believed the issue to be. Can you run `cordova info` again and show me the output.

**Comment by fer1994** [comment]
>Node version: v6.9.2

Cordova version: 8.1.1

Config.xml file: 

<?xml version='1.0' encoding='utf-8'?>
<widget android-versionCode="24" id="com.tarjetanaranja.emisor.gestionCliente.appVentas" ios-CFBundleVersion="24" version="1.0.15" xmlns="http://www.w3.org/ns/widgets" xmlns:cdv="http://cordova.apache.org/ns/1.0">
    <name>EVen</name>
    <description>Evolucion de Vendedores Naranja.</description>
    <author email="informes@naranja.com.ar" href="https://www.naranja.com/">Naranja</author>
    <content src="index.html" />
    <access origin="*" />
    <allow-intent href="http://*/*" />
    <allow-intent href="https://*/*" />
    <allow-intent href="tel:*" />
    <allow-intent href="sms:*" />
    <allow-intent href="mailto:*" />
    <allow-intent href="geo:*" />
    <preference name="orientation" value="portrait" />
    <preference name="AutoHideSplashScreen" value="true" />
    <preference name="SplashScreen" value="screen" />
    <preference name="SplashScreenSpinnerColor" value="white" />
    <preference name="CordovaWebViewEngine" value="CDVUIWebViewEngine" />
    <platform name="android">
        <allow-intent href="market:*" />
        <resource-file src="google-services.json" target="app/google-services.json" />
        <icon src="res/icon/android/icon-192.png" />
        <splash src="res/splash/android/splash.png" />
        <preference name="loadUrlTimeoutValue" value="700000" />
        <preference name="disallowOverscroll" value="true" />
        <preference name="webviewbounce" value="false" />
    </platform>
    <platform name="ios">
        <allow-intent href="itms:*" />
        <allow-intent href="itms-apps:*" />
        <icon src="res/icon/ios/icon-180.png" />
        <splash height="480" src="res/splash/ios/splash-iphone.png" width="320" />
        <splash height="960" src="res/splash/ios/splash-iphone2x.png" width="640" />
        <splash height="1136" src="res/splash/ios/splash-568h2x.png" width="640" />
        <splash height="1334" src="res/splash/ios/splash-667h.png" width="752" />
        <splash height="1334" src="res/splash/ios/splash-667h.png" width="750" />
        <splash height="2208" src="res/splash/ios/splash-736h.png" width="1242" />
        <splash height="1920" src="res/splash/ios/splash-736h.png" width="1080" />
        <splash height="2048" src="res/splash/ios/splash-ipad2x.png" width="1536" />
        <splash height="1024" src="res/splash/ios/splash-ipad.png" width="768" />
        <preference name="DisallowOverscroll" value="true" />
        <preference name="WebViewBounce" value="false" />
        <preference name="StatusBarOverlaysWebView" value="false" />
        <preference name="StatusBarBackgroundColor" value="#ffffff" />
        <preference name="StatusBarStyle" value="default" />
        <preference name="KeyboardShrinksView " value="true" />
        <preference name="deployment-target" value="8.1" />
        <icon src="res/icon/ios/icon-57.png" />
    </platform>
    <feature name="CDVWKWebViewEngine">
        <param name="ios-package" value="CDVWKWebViewEngine" />
    </feature>
    <plugin name="cordova-plugin-firebase" spec="^2.0.5" />
    <plugin name="cordova-plugin-splashscreen" spec="^5.0.2" />
    <plugin name="cordova-plugin-keyboard" spec="^1.2.0" />
    <plugin name="cordova-plugin-camera-preview" spec="^0.10.0" />
    <plugin name="cordova-plugin-advanced-http" spec="^2.0.1" />
    <plugin name="cordova-plugin-whitelist" spec="^1.3.3" />
    <plugin name="cordova-plugin-device" spec="^2.0.2" />
    <plugin name="cordova-plugin-appversion" spec="^1.0.0" />
    <plugin name="cordova-sqlcipher-adapter" spec="^0.1.12-rc2" />
    <plugin name="cordova-plugin-network-information" spec="^2.0.1" />
    <plugin name="cordova-plugin-file" spec="^6.0.1" />
    <plugin name="cordova-android-support-gradle-release" spec="^2.0.1">
        <variable name="ANDROID_SUPPORT_VERSION" value="27.+" />
    </plugin>
    <plugin name="cordova-plugin-file-opener2" spec="~2.1.0">
        <variable name="ANDROID_SUPPORT_V4_VERSION" value="27.+" />
    </plugin>
    <engine name="android" spec="^7.1.4" />
    <engine name="ios" spec="^4.5.5" />
</widget>

**Comment by shnist** [comment]
@fer1994 try removing the `platforms` and `plugins` folders and try building it again.

**Comment by fer1994** [comment]
I update the GRADLE and it work!

**Comment by shnist** [comment]
great! glad it's working now.
