### ISSUE TITLE
ReferenceError: Can't find variable: callbackContext

### ISSUE THREAD

**Issue by fishbone1** [pwlin/cordova-plugin-file-opener2#241]
I'm getting "ReferenceError: Can't find variable: callbackContext" when calling `open()`. But it is not surprising, `open` tries to access this global variable instead of `options`:

https://github.com/pwlin/cordova-plugin-file-opener2/blob/cb09bea3c4c2ac602873c600ca8025b79f32ace1/www/plugins.FileOpener2.js#L32

Cordova 8.1.0
Cordova/iOS 4.5.5
cordova-plugin-file-opener2 2.1.1

**Comment by shnist** [comment]
@fishbone1, good catch, will release a patch now.

**Comment by shnist** [comment]
Patch `2.1.2` released with fix. Version `2.1.1` has been deprecated.
