### ISSUE TITLE
Open dialog hidden behind InAppBrowser

### ISSUE THREAD

**Issue by Bruno-bm** [pwlin/cordova-plugin-file-opener2#243]
When calling $cordovaFileOpener2.open() the dialog window is opened behind InAppBrowser.
The same problem ocurred on cordova-plugin-dialogs: https://issues.apache.org/jira/browse/CB-13555

Tests realized on iPhone X

#### Cordova CLI info

Here is the output:
<details>
  <summary>Click to expand</summary>
  Node version: v8.10.0

Cordova version: 8.0.0

Config.xml file:

<?xml version='1.0' encoding='utf-8'?>
<widget id="br.com.teste" version="0.0.5" xmlns="http://www.w3.org/ns/widgets" xmlns:cdv="http://cordova.apache.org/ns/1.0">
    <name></name>
    <description></description>
    <author email="desenv.mobile@teste.com.br" href="https://www.teste.com.br/"></author>
    <content src="index.html" />
    <preference name="webviewbounce" value="false" />
    <preference name="UIWebViewBounce" value="false" />
    <preference name="DisallowOverscroll" value="true" />
    <preference name="android-minSdkVersion" value="16" />
    <preference name="BackupWebStorage" value="none" />
    <preference name="SplashScreen" value="screen" />
    <preference name="SplashScreenDelay" value="3000" />
    <preference name="AutoHideSplashScreen" value="true" />
    <preference name="ShowSplashScreenSpinner" value="false" />
    <preference name="StatusBarOverlaysWebView" value="true" />
    <preference name="StatusBarBackgroundColor" value="#003366" />
    <preference name="StatusBarStyle" value="lightcontent" />
    <preference name="StatusBarDefaultScrollToTop" value="false" />
    <feature name="StatusBar">
        <param name="ios-package" onload="true" value="CDVStatusBar" />
    </feature>
    <preference name="AndroidPersistentFileLocation" value="Compatibility" />
    <preference name="AndroidExtraFilesystems" value="files,files-external,documents,sdcard,cache,cache-external,assets,root" />
    <icon src="resources/icon.png" />
    <splash src="resources/splash.png" />
    <allow-navigation href="*" />
    <allow-intent href="*" />
    <access origin="*" />
    <platform name="ios">
        <icon height="57" src="resources/ios/icon/icon.png" width="57" />
    </platform>
    <preference name="SplashShowOnlyFirstTime" value="false" />
    <platform name="android">
        <splash density="land-ldpi" src="resources/android/splash/drawable-land-ldpi-screen.png" />
    </platform>

    <plugin name="cordova-plugin-splashscreen" spec="~4.0.0" />
    <plugin name="cordova-plugin-vibration" spec="~2.1.1" />
    <plugin name="cordova-plugin-whitelist" spec="~1.2.2" />
    <plugin name="ionic-plugin-keyboard" spec="^2.2.1" />
    <plugin name="cordova-plugin-inappbrowser" spec="^1.7.2" />
    <plugin name="cordova-plugin-statusbar" spec="^2.4.2" />
    <plugin name="onesignal-cordova-plugin" spec="^2.4.1" />
    <plugin name="cordova-plugin-themeablebrowser" spec="^0.2.17" />
    <plugin name="cordova-plugin-file" spec="6.0.1" />
    <plugin name="cordova-plugin-file-transfer" spec="1.7.1" />
    <plugin name="cordova-plugin-device" spec="2.0.2" />
    <plugin name="cordova-plugin-file-opener2" spec="2.1.0">
        <variable name="ANDROID_SUPPORT_V4_VERSION" value="27.+" />
    </plugin>
    <plugin name="cordova-plugin-dialogs" spec="2.0.1" />
    <engine name="ios" spec="4.5.4" />
    <engine name="android" spec="7.1.4" />
</widget>

Plugins:

cordova-plugin-device,cordova-plugin-dialogs,cordova-plugin-file,cordova-plugin-file-opener2,cordova-plugin-file-transfer,cordova-plugin-inappbrowser,cordova-plugin-splashscreen,cordova-plugin-statusbar,cordova-plugin-themeablebrowser,cordova-plugin-vibration,cordova-plugin-whitelist,ionic-plugin-keyboard,onesignal-cordova-plugin

iOS platform:

Xcode 10.1

Build version 10B61
</details>

#### Plugin version

Here is the output:
cordova-plugin-file-opener2 2.1.0 "File Opener2"

**Comment by Bruno-bm** [comment]
Correction on pull request #244

**Comment by LeandroFChaves** [comment]
Good afternoon,

I have the same problem reported by Bruno. I have already visualized the correction of the same and I will apply.

Will it come in the official version?

Thank you.

**Comment by shnist** [comment]
@LeandroFChaves yes, will do a new release in the near future with this feature.

**Comment by shnist** [comment]
@Bruno-bm PR has been merged and new release `2.2.0` has been published.

**Comment by philipp-kuttner** [comment]
Hi. Sorry for the message on this old post.
But I have exactly the same problem, although the current versions of the plugins are used.
