### ISSUE TITLE
Using ANDROID_SUPPORT_V4_VERSION

### ISSUE THREAD

**Issue by WuglyakBolgoink** [pwlin/cordova-plugin-file-opener2#247]
Hallo!

What should I write in `ANDROID_SUPPORT_V4_VERSION` if I have something like this:

```xml
...
<platform name="android">
        <preference name="android-minSdkVersion" value="21"/>
</platform>
...
<plugin name="cordova-android-support-gradle-release" spec="1.4.4">
    <variable name="ANDROID_SUPPORT_VERSION" value="21.+"/>
</plugin>
...
```

By default plugin was installed as:

```xml
<plugin name="cordova-plugin-file-opener2" spec="^2.1.4">
        <variable name="ANDROID_SUPPORT_V4_VERSION" value="27.+" />
</plugin>
```

**Comment by shnist** [comment]
hi @WuglyakBolgoink, I think you should change it to 21.+

**Comment by shnist** [comment]
@WuglyakBolgoink did that solve your issue?

**Comment by WuglyakBolgoink** [comment]
Hallo @shnist 

I changed to "21.+"..

But actually Plugin should say, which version I must write on install.

```
--variable ANDROID_SUPPORT_V4_VERSION={required version}
```

for example hire https://github.com/phonegap/phonegap-plugin-barcodescanner#installation
it is not clear what should be written... Latest or min version?)
![image](https://user-images.githubusercontent.com/2271337/52653926-3ef8ce80-2ef1-11e9-9cc5-6052e813a074.png)

**Comment by shnist** [comment]
hi @WuglyakBolgoink, I understand what you're saying, I will update the README to be clearer.
