### ISSUE TITLE
How to open edit image with dialog

### ISSUE THREAD

**Issue by bismay4u** [pwlin/cordova-plugin-file-opener2#248]
Hi,

Can I open : edit image with dialog.

Thank you

**Comment by shnist** [comment]
hi @bismay4u, this plugin is designed to open a file in an application of your choice. there are known issue with attempting to open a file with the intention of editing and saving it out. See: https://github.com/pwlin/cordova-plugin-file-opener2/issues/164

**Comment by shnist** [comment]
closing the issue due to inactivity. If you require any more assistance, please feel free to reopen the issue.
