### ISSUE TITLE
iOS :: "success" callback happens too quickly

### ISSUE THREAD

**Issue by nickcmaynard** [pwlin/cordova-plugin-file-opener2#25]
This is called as soon as the _menu_ is opened - not when the file has been opened.

This makes it hard to clean up files, but also to know if a file was really opened or not.

Would it be possible to use [UIDocumentInteractionControllerDelegate](https://developer.apple.com/library/prerelease/ios/documentation/UIKit/Reference/UIDocumentInteractionControllerDelegate_protocol/index.html#//apple_ref/doc/uid/TP40009305) to get more information about what happened during the callout?

This could also be used to give more informative error conditions.

**Comment by pwlin** [comment]
@nickcmaynard  you are more than welcome to submit a pull request :)

**Comment by nickcmaynard** [comment]
I'd love to!  Unfortunately my ObjC foo isn't up to the task.  Apologies - my best way to help is by popping in requests.

**Comment by pwlin** [comment]
There has been a couple of new releases since then. Can you please upgrade and test if you still have issues? thanks
