### ISSUE TITLE
[ASK] Can it open pdf on link / online

### ISSUE THREAD

**Issue by maztam** [pwlin/cordova-plugin-file-opener2#254]
Can this plugin open pdf online from url ? like http://example.com/any.pdf

**Comment by stefanwilliam96** [comment]
i got same issue here

**Comment by shnist** [comment]
hi @maztam, this plugin cannot open files directly from URLs, but you can download it first using the file transfer plugin and then opening it locally
https://github.com/apache/cordova-plugin-file-transfer
