### ISSUE TITLE
Bump up to new version ?

### ISSUE THREAD

**Issue by abcfy2** [pwlin/cordova-plugin-file-opener2#263]
Since last `2.2.0`, some commits are not released yet. I think it's better to release a new version.

**Comment by shnist** [comment]
hi @abcfy2, afraid i've been pretty stacked at work, but will get round to cutting a new release soon.

**Comment by pwlin** [comment]
Would it help if I publish the HEAD to `npm`?

**Comment by pwlin** [comment]
Thanks @shnist for all the great work!
