### ISSUE TITLE
Opening local file (pdf) : “not found”.

### ISSUE THREAD

**Issue by MisterWP** [pwlin/cordova-plugin-file-opener2#28]
Hello,

Using [io.github.pwlin.cordova.plugins.fileopener2](https://github.com/pwlin/cordova-plugin-file-opener2), I can't open my local PDF file in Android.

Locally, I have a "/myapp/www/pdf/" folder with files (1.pdf,... to 6.pdf).

Here my PhoneGap config.xml 

```
<widget xmlns="http://www.w3.org/ns/widgets" xmlns:gap="http://phonegap.com/ns/1.0" id="app.example.com" version="1.0.0">
  <name><![CDATA[Example]]></name>
  <description>...</description>
  <author href="http://www.example.com" email="hello@example.com">Example</author>
  <content src="index.html"/>
  <preference name="permissions" value="none"/>
  <preference name="orientation" value="default"/>
  <preference name="target-device" value="universal"/>
  <preference name="fullscreen" value="true"/>
  <preference name="webviewbounce" value="false"/>
  <preference name="prerendered-icon" value="true"/>
  <preference name="stay-in-webview" value="false"/>
  <preference name="ios-statusbarstyle" value="black-opaque"/>
  <preference name="detect-data-types" value="true"/>
  <preference name="exit-on-suspend" value="false"/>
  <preference name="show-splash-screen-spinner" value="true"/>
  <preference name="auto-hide-splash-screen" value="true"/>
  <preference name="disable-cursor" value="false"/>
  <preference name="android-minSdkVersion" value="7"/>
  <preference name="android-installLocation" value="auto"/>
  <preference name="useBrowserHistory" value="true" />
  <gap:plugin name="org.apache.cordova.console"/>
  <gap:plugin name="org.apache.cordova.device"/>
  <gap:plugin name="org.apache.cordova.dialogs"/>
  <gap:plugin name="org.apache.cordova.file"/>
  <gap:plugin name="org.apache.cordova.file-transfer"/>
  <gap:plugin name="org.apache.cordova.inappbrowser"/>
  <gap:plugin name="org.apache.cordova.network-information"/>
  <gap:plugin name="io.github.pwlin.cordova.plugins.fileopener2" version="1.0.11" />
  <icon src="icon.png"/>
  <icon src="res/icon/android/icon-36-ldpi.png" gap:platform="android" gap:qualifier="ldpi"/>
  <icon src="res/icon/android/icon-48-mdpi.png" gap:platform="android" gap:qualifier="mdpi"/>
  <icon src="res/icon/android/icon-72-hdpi.png" gap:platform="android" gap:qualifier="hdpi"/>
  <icon src="res/icon/android/icon-96-xhdpi.png" gap:platform="android" gap:qualifier="xhdpi"/>
  <icon src="res/icon/ios/icon-57.png" gap:platform="ios" width="57" height="57"/>
  <icon src="res/icon/ios/icon-72.png" gap:platform="ios" width="72" height="72"/>
  <icon src="res/icon/ios/icon-57-2x.png" gap:platform="ios" width="114" height="114"/>
  <icon src="res/icon/ios/icon-72-2x.png" gap:platform="ios" width="144" height="144"/>
  <gap:splash src="res/screen/android/screen-ldpi-portrait.png" gap:platform="android" gap:qualifier="port-ldpi"/>
  <gap:splash src="res/screen/android/screen-mdpi-portrait.png" gap:platform="android" gap:qualifier="port-mdpi"/>
  <gap:splash src="res/screen/android/screen-hdpi-portrait.png" gap:platform="android" gap:qualifier="port-hdpi"/>
  <gap:splash src="res/screen/android/screen-xhdpi-portrait.png" gap:platform="android" gap:qualifier="port-xhdpi"/>
  <gap:splash src="res/screen/ios/screen-iphone-portrait.png" gap:platform="ios" width="320" height="480"/>
  <gap:splash src="res/screen/ios/screen-iphone-portrait-2x.png" gap:platform="ios" width="640" height="960"/>
  <gap:splash src="res/screen/ios/screen-iphone-portrait-568h-2x.png" gap:platform="ios" width="640" height="1136"/>
  <gap:splash src="res/screen/ios/screen-ipad-portrait.png" gap:platform="ios" width="768" height="1024"/>
  <gap:splash src="res/screen/ios/screen-ipad-landscape.png" gap:platform="ios" width="1024" height="768"/>
  <access origin="*"/>
  <plugin name="cordova-plugin-whitelist" version="1"/>
  <allow-intent href="http://*/*"/>
  <allow-intent href="https://*/*"/>
  <allow-intent href="tel:*"/>
  <allow-intent href="sms:*"/>
  <allow-intent href="mailto:*"/>
  <allow-intent href="geo:*"/>
  <platform name="android">
    <allow-intent href="market:*"/>
  </platform>
  <platform name="ios">
    <allow-intent href="itms:*"/>
    <allow-intent href="itms-apps:*"/>
  </platform>
  <feature name="http://api.phonegap.com/1.0/file"/>
</widget>
```

I already tried many things like that in my html files : 

```
<!-- openPDF is a personnal function... see next block -->
<a onClick="openPDF('pdf/1.pdf');">Open PDF</a>
```

My functions (js files) : 

```
var fs;

function fsSuccess(fileSystem)
{
    fs = fileSystem;
}

function fsFail(event)
{
    console.log(event.target.error.code);
}

function openPDF(file) {

    window.requestFileSystem  = window.requestFileSystem || window.webkitRequestFileSystem;
    window.requestFileSystem(LocalFileSystem.PERSISTENT, 0, fsSuccess, fsFail);     

    file = fs.root.toURL() + file;

    cordova.plugins.fileOpener2.open(
    file, // You can also use a Cordova-style file uri: cdvfile://localhost/persistent/Download/starwars.pdf
    'application/pdf', 
    { 
        error : function(e) { 
            console.log('Error status: ' + e.status + ' - Error message: ' + e.message);
            $('#errorpdf').html('Error status: ' + e.status + ' - Error message: ' + e.message+' - File : '+file);
        },
        success : function () {
            console.log('file opened successfully');          
            $('#errorpdf').html('file opened successfully');

        }
    }
);
}
```

All the time, Cordova returns me : **"Error status: 9 - Error message: File not found"**

Where am I wrong ? 

**EDIT** : my folders 
/storage/emulated/0/Android/data/com.example.app/files
/storage/emulated/0/Android/data/com.example.app/cache
obviously is empty and I don't know how to move local .pdf file to this folder.

**Comment by pwlin** [comment]
Try to put your pdf file in:

    /storage/emulated/0/1.pdf

and call your function as:
    
    openPDF('/storage/emulated/0/1.pdf');

Does that work?

**Comment by atukilham** [comment]
hi @pwlin , i try to open pdf from local storage with path from cordova file plugin.
here my code : 
```
var filePDF = 'tes.pdf';
cordova.plugins.fileOpener2.open(
     cordova.file.dataDirectory+filePDF, // path file:////data/data/<app-id>/files/tes.pdf
     'application/pdf', 
     { 
        error : function(e) { 
					alert('Error status: ' + e.status + ' - Error message: ' + e.message);
				    },
	success : function () {
					    alert('file opened successfully');                
					 }
				  }
);
```
It return"file opened successfully"
but from adobe pdf show alert that "The document path is not valid"
can you help me, please?
Thanks

**Comment by ekalavya2014** [comment]
Hi @pwlin, 

I tried opening pdf in my windows 8.1 phone. the file path is `//app-folder/slip-201432-1-2015.pdf` and also have adobe acrobat installed in my phone.
Whenever i click open pdf button it goes into error function and show `Error status: undefined - Error message: undefined`, any idea what would be reason?

Thanks in advance

**Comment by niyazafazl** [comment]
I am using the same code as this
var fs;

function fsSuccess(fileSystem)
{
    fs = fileSystem;
}

function fsFail(event)
{
    console.log(event.target.error.code);
}

function openPDF(file) {

    window.requestFileSystem  = window.requestFileSystem || window.webkitRequestFileSystem;
    window.requestFileSystem(LocalFileSystem.PERSISTENT, 0, fsSuccess, fsFail);     

  file = fs.root.toURL() + "pubs/2015/mypdf.pdf";

    cordova.plugins.fileOpener2.open(
    file, // You can also use a Cordova-style file uri: cdvfile://localhost/persistent/Download/starwars.pdf
    'application/pdf', 
    { 
        error : function(e) { 
            console.log('Error status: ' + e.status + ' - Error message: ' + e.message);
            $('#errorpdf').html('Error status: ' + e.status + ' - Error message: ' + e.message+' - File : '+file);
        },
        success : function () {
            console.log('file opened successfully');          
            $('#errorpdf').html('file opened successfully');

        }
    }
);
}

It throws me the error: LocalFileSystem is not defined

My path for the pdf files: video/www/pubs/2015/mypdf.pdf
My HTML file path: video/www/publications.html

Please advice me what wrong on this and how could I resolve it.

Thanks!

**Comment by niyazafazl** [comment]
Hi @pwlin,

Can you please brief me how I would do this
/*
Try to put your pdf file in:

/storage/emulated/0/1.pdf
and call your function as:

openPDF('/storage/emulated/0/1.pdf'); */
How I could put my local pdf file in  /storage/emulated path.
Thanks!

**Comment by onico0** [comment]
Finally, I did it like this, with 2 plugins : 

  <gap:plugin name="io.github.pwlin.cordova.plugins.fileopener2" version="1.0.11" />
  <gap:plugin name="com.gkcgautam.asset2sd" version="2.0.0" />

Here my whole code not cleaned (sorry), if you need it, you have tu remove some lines such as visual "feedbacks", etc.


    /* First of all... copy a directory to local storage */
    function copyPDF(file) {
    		
    	var timeNow = Math.floor(Date.now() / 1000);
    	var timeLastDataBaux = localStorage.getItem("bauxPDFDate");
    	
    	// Don't copy the PDF for 15 min., it will be faster
    	if(timeLastDataBaux > (timeNow-900)) // (60 * 15 = 900) 15 minutes de cache
    	{    		
    		if(localStorage.getItem("bauxPDFDate") !== null)
    		{
    			// Display buttons to open PDFs
    			$('#baux_page_loading').fadeOut('slow', function() {
    				$('#baux_page_loaded').fadeIn('fast');
    			});
    			return true;
    		}
    		else
    		{
    		// ?
    			console.log('First copy of files...');
    		}
    	} 
    	else 
    	{ 
    	// Else, we have no data, or too old ? normal way => we launch the copy etc. 
    		console.log('Files too old...');
    	}
    		
    		
    	asset2sd.copyDir({ 
    		  asset_directory: file, // 'www/pdf' 
    		  destination_directory: "MyDir" 
    		  },
    		  function(result) 
    		  {
    			// SUCCESS ! 
    			$('#baux_page_loading').html('<p>✓ Well loaded&nbsp;!</p>');
    			
    			var timestamp = Math.floor(Date.now() / 1000);
    		  	localStorage.setItem('bauxPDFDate', timestamp);
    			
    			// Display button to open PDFs
    			$('#baux_page_loading').fadeOut('slow', function() {
    				$('#baux_page_loaded').fadeIn('fast');
    			});
    			
    		  }, function() 
    		  {
    			// ERROR
    			$('#baux_page_loading').fadeOut('normal');
    		  	$('#errorpdf').html('<div class="error">Impossible to load PDF files on the internal storage space or SD card (erreur : '+file+' - '+result+'). Please see our website <a onclick="http://www.example.com" class="coloredTap">www.example.com</a>  to download its PDF.</div>');
    		  });  
    }
    
    /* Second, this is the way to open local file already copied with asset2sd */
    function openPDF(filename, btn) {
    	
    	window.requestFileSystem  = window.requestFileSystem || window.webkitRequestFileSystem;
    	window.requestFileSystem(LocalFileSystem.PERSISTENT, 0, fsSuccess, fsFail);
    		
    	file = fs.root.toURL() + filename;
    	
    	//$(btn).fadeOut('fast', function() { $(btn).fadeIn('fast'); });
    	$(btn).after( '<img src="images/loader.gif" align="absmiddle" id="littleLoader">' );
    	
    	cordova.plugins.fileOpener2.open(
    	file, // You can also use a Cordova-style file uri: cdvfile://localhost/persistent/Download/starwars.pdf
    	'application/pdf', 
    		{ 
    			error : function(e) { 
    				//console.log('Error status: ' + e.status + ' - Error message: ' + e.message);
    				$('#errorpdf3').html('<div class="error">Cannot open PDF in this path (erreur : ' + e.status + ' - msg : ' + e.message+' - chemin : '+file+'). Please see our website <a onclick="http://www.example.com" class="coloredTap">www.example.com</a> to download it.</div>');
    			},
    			success : function () {
    				//console.log('file opened successfully');  
    				  setTimeout(function(){ 
    						$('#littleLoader').fadeOut('normal');
    						$('#littleLoader').remove();
    					}, 1500);
    				//$('#errorpdf3').html('file opened successfully');
    	
    			}
    		}
    	); 
    	
    }

**Comment by niyazafazl** [comment]
Hi,
Thanks for your mail. In my app, all my pdfs are resided at my asset folder and the path is www/pdf/2015/mypdf.pdf
Since my pdf files are located in my local folder, I implemented the following code in my html page.(Is this the correct way am I using?)function openPDF(file) {
       var fs;

        function fsSuccess(fileSystem)
        {
            fs = fileSystem;
        }

        function fsFail(event)
        {
            console.log(event.target.error.code);
        }
        window.requestFileSystem  = window.requestFileSystem || window.webkitRequestFileSystem;
        window.requestFileSystem(LocalFileSystem.PERSISTENT, 0, fsSuccess, fsFail);

           file =  fs.root.toURL() + file;
            cordova.plugins.fileOpener2.open(
            file,
            'application/pdf',
            {
                error : function(e) {
                    console.log('Error status: ' + e.status + ' - Error message: ' + e.message + '- Error:' + JSON.stringify(e));
                  // $('#errorpdf').html('Error status: ' + e.status + ' - Error message: ' + e.message);
                },
                success : function () {
                alert("pass");
                    console.log('file opened successfully');
                 //   $('#errorpdf').html('file opened successfully');

                }
            }
        );
        }<body><p><button onclick="openPDF('/mypdf.pdf');">Play PDF on Android</button></p></body>For the above code, im getting the error, "can't call method root of undefined".
And also I have tried in this way:
cordova.plugins.fileOpener2.open('file:///android_asset/www/pdf/2015/mypdf.pdf','application/pdf',{error : function(e) {console.log('Error status: ' + e.status + ' - Error message: ' + e.message);},success : function () {console.log('file opened successfully');}});
It throws me "File not found" error.
What I did wrong in my both code? Please advice how I can fix this?
Thanks!Niyaza 


     On Monday, July 13, 2015 6:16 PM, onico0 <notifications@github.com> wrote:
   

 Finally, I did it like this, with 2 plugins : 
 Here my whole code not cleaned (sorry), if you need it, you have tu remove some lines such as visual "feedbacks", etc./* First of all... copy a directory to local storage */
function copyPDF(file) {

    var timeNow = Math.floor(Date.now() / 1000);
    var timeLastDataBaux = localStorage.getItem("bauxPDFDate");

    // Don't copy the PDF for 15 min., it will be faster
    if(timeLastDataBaux > (timeNow-900)) // (60 * 15 = 900) 15 minutes de cache
    {           
        if(localStorage.getItem("bauxPDFDate") !== null)
        {
            // Display buttons to open PDFs
            $('#baux_page_loading').fadeOut('slow', function() {
                $('#baux_page_loaded').fadeIn('fast');
            });
            return true;
        }
        else
        {
        // ?
            console.log('First copy of files...');
        }
    } 
    else 
    { 
    // Else, we have no data, or too old ? normal way => we launch the copy etc. 
        console.log('Files too old...');
    }


    asset2sd.copyDir({ 
          asset_directory: file, // 'www/pdf' 
          destination_directory: "MyDir" 
          },
          function(result) 
          {
            // SUCCESS ! 
            $('#baux_page_loading').html('<p>✓ Well loaded&nbsp;!</p>');

            var timestamp = Math.floor(Date.now() / 1000);
            localStorage.setItem('bauxPDFDate', timestamp);

            // Display button to open PDFs
            $('#baux_page_loading').fadeOut('slow', function() {
                $('#baux_page_loaded').fadeIn('fast');
            });

          }, function() 
          {
            // ERROR
            $('#baux_page_loading').fadeOut('normal');
            $('#errorpdf').html('<div class="error">Impossible to load PDF files on the internal storage space or SD card (erreur : '+file+' - '+result+'). Please see our website <a onclick="http://www.example.com" class="coloredTap">www.example.com</a>  to download its PDF.</div>');
          });  
}

/* Second, this is the way to open local file already copied with asset2sd */
function openPDF(filename, btn) {

    window.requestFileSystem  = window.requestFileSystem || window.webkitRequestFileSystem;
    window.requestFileSystem(LocalFileSystem.PERSISTENT, 0, fsSuccess, fsFail);

    file = fs.root.toURL() + filename;

    //$(btn).fadeOut('fast', function() { $(btn).fadeIn('fast'); });
    $(btn).after( '<img src="images/loader.gif" align="absmiddle" id="littleLoader">' );

    cordova.plugins.fileOpener2.open(
    file, // You can also use a Cordova-style file uri: cdvfile://localhost/persistent/Download/starwars.pdf
    'application/pdf', 
        { 
            error : function(e) { 
                //console.log('Error status: ' + e.status + ' - Error message: ' + e.message);
                $('#errorpdf3').html('<div class="error">Cannot open PDF in this path (erreur : ' + e.status + ' - msg : ' + e.message+' - chemin : '+file+'). Please see our website <a onclick="http://www.example.com" class="coloredTap">www.example.com</a> to download it.</div>');
            },
            success : function () {
                //console.log('file opened successfully');  
                  setTimeout(function(){ 
                        $('#littleLoader').fadeOut('normal');
                        $('#littleLoader').remove();
                    }, 1500);
                //$('#errorpdf3').html('file opened successfully');

            }
        }
    ); 

}

**Comment by niyazafazl** [comment]
Hi,

Thanks for your reply. In my app, all my pdfs are resided at my asset folder and the path is www/pdf/2015/mypdf.pdf

Since my pdf files are located in my local folder, I implemented the following code in my html page.
(Is this the correct way am I using?)
function openPDF(file) {
       var fs;

        function fsSuccess(fileSystem)
        {
            fs = fileSystem;
        }

        function fsFail(event)
        {
            console.log(event.target.error.code);
        }
        window.requestFileSystem  = window.requestFileSystem || window.webkitRequestFileSystem;
        window.requestFileSystem(LocalFileSystem.PERSISTENT, 0, fsSuccess, fsFail);

           file =  fs.root.toURL() + file;
            cordova.plugins.fileOpener2.open(
            file,
            'application/pdf',
            {
                error : function(e) {
                    console.log('Error status: ' + e.status + ' - Error message: ' + e.message + '- Error:' + JSON.stringify(e));
                  // $('#errorpdf').html('Error status: ' + e.status + ' - Error message: ' + e.message);
                },
                success : function () {
                alert("pass");
                    console.log('file opened successfully');
                 //   $('#errorpdf').html('file opened successfully');

                }
            }
        );
        }
<body>
<p><button onclick="openPDF('/mypdf.pdf');">Play PDF on Android</button></p>
</body>
For the above code, im getting the error, "can't call method root of undefined".

And also I have tried in this way:

cordova.plugins.fileOpener2.open(
'file:///android_asset/www/pdf/2015/mypdf.pdf',
'application/pdf',
{
error : function(e) {
console.log('Error status: ' + e.status + ' - Error message: ' + e.message);
},
success : function () {
console.log('file opened successfully');
}
}
);

It throws me "File not found" error.

What I did wrong in my both code? Please advice how I can fix this?

**Comment by niyazafazl** [comment]
Hi Nicolas,

I have implemented the code as follow yours


	/*First of all... copy a directory to local storage */
     function copyPDF() {
    var bauxPDFDate = Math.floor(Date.now());
    localStorage.setItem("bauxPDFDate", JSON.stringify(bauxPDFDate));
    var timeNow = Math.floor(Date.now() / 1000);
    var timeLastDataBaux = localStorage.getItem("bauxPDFDate");

         // Don't copy the PDF for 15 min., it will be faster
         if(timeLastDataBaux > (timeNow-900)) // (60 * 15 = 900) 15 minutes de cache
          {           
           if(localStorage.getItem("bauxPDFDate") !== null)
           {
            // Display buttons to open PDFs
            $('#baux_page_loading').fadeOut('slow', function() {
                $('#baux_page_loaded').fadeIn('fast');
            });
            return true;
        }
        else
        {
        // ?
            console.log('First copy of files...');
        }
    } 
    else 
    { 
    // Else, we have no data, or too old ? normal way => we launch the copy etc. 
        console.log('Files too old...');
    }


    asset2sd.copyDir({ 
          asset_directory: 'www/pdf',
          destination_directory: "MyPdfDir" 
          },
          function(result) 
          {
            // SUCCESS ! 
            $('#baux_page_loading').html('<p>✓ Well loaded&nbsp;!</p>');

            var timestamp = Math.floor(Date.now() / 1000);
            localStorage.setItem('bauxPDFDate', timestamp);

            // Display button to open PDFs
            $('#baux_page_loading').fadeOut('slow', function() {
                $('#baux_page_loaded').fadeIn('fast');
            });

          }, function() 
          {
            // ERROR
            $('#baux_page_loading').fadeOut('normal');
            $('#errorpdf').html('<div class="error">Impossible to load PDF files on the internal storage space or SD card (erreur : '+file+' - '+result+'). Please see our website <a onclick="http://www.example.com" class="coloredTap">www.example.com</a>  to download its PDF.</div>');
          });  
          }

        copyPDF();

	var fs;
	function openPDF(filename) {
        function fsSuccess(fileSystem)
        {
            fs = fileSystem;
         alert("fs==>" +fileSystem.name);
        }
        function fsFail(event)
        {
            console.log(event.target.error.code);
        }
        window.requestFileSystem  = window.requestFileSystem || window.webkitRequestFileSystem;
        window.requestFileSystem(LocalFileSystem.PERSISTENT, 0, fsSuccess, fsFail);

           file =  'file:///storage/sdcard0/MyPdfDir/' +filename;  /*If I use fs.root.toURL().filename, it returns this path - "file:///storage/sdcard0" and it still throw the error "File not found" and also shows "Cannot read property 'root' of undefined". */

            cordova.plugins.fileOpener2.open(
            file,
            'application/pdf',
            {
                error : function(e) {
                alert("Error:" + JSON.stringify(e));
                    console.log('Error status: ' + e.status + ' - Error message: ' + e.message + '- Error:' + JSON.stringify(e));
                   $('#errorpdf').html('Error status: ' + e.status + ' - Error message: ' + e.message);
                },
                success : function () {
                alert("pass");
                    console.log('file opened successfully');
                    $('#errorpdf').html('file opened successfully');

                }
            }
        );
        }

**Comment by bandhavya** [comment]
Im facing the same problem using this plugin.
How to resolve it

**Comment by johnramesh** [comment]
If any spaces in the path it will add %20.So the file is not found in that case.If in that case decode the path using javascript method "decodeURIComponent" .like decodeURIComponent(path);

**Comment by japostigo-atsistemas** [comment]
I had the same problem trying to open a PDF located in the www/ folder. So to open it in android: I copied it to the external data directory and then I opened the new file:

(_uri_ is _/www/path/to/file.pdf_)

    window.resolveLocalFileSystemURL(cordova.file.applicationDirectory +  uri, function(fileEntry) {

        window.resolveLocalFileSystemURL(cordova.file.externalDataDirectory, function(dirEntry) {

            fileEntry.copyTo(dirEntry, 'file.pdf', function(newFileEntry) {

                cordova.plugins.fileOpener2.open(newFileEntry.nativeURL,'application/pdf');
            });
        });
    });

**Comment by darylldawn** [comment]
After hours of trying to open a PDF in Android, @japostigo-atsistemas 's solution worked well for me. Thanks!

**Comment by shamaleyte** [comment]
@japostigo-atsistemas  +1 to your solution mate. Thanks

**Comment by brainwind-software** [comment]
Thanks to @japostigo-atsistemas solution!

I tweaked it a bit, here's what I recommend:

1) use `window.open` instead of `fileOpener2.open`
* no need to declare mimetype
* needs [cordova-plugin-inappbrowser](https://github.com/apache/cordova-plugin-inappbrowser) plugin instead of FileOpener2 plugin

2) use `uri.split('/').pop()` to keep the original filename when copying

```
window.resolveLocalFileSystemURL(cordova.file.applicationDirectory +  uri, function(fileEntry) {

    window.resolveLocalFileSystemURL(cordova.file.externalDataDirectory, function(dirEntry) {

        fileEntry.copyTo(dirEntry, uri.split('/').pop(), function(newFileEntry) {

            window.open(newFileEntry.nativeURL, '_system');
        });
    });
});

```

**Comment by Balaji-yogy** [comment]
Hi @japostigo-atsistemas,

I tried this coding with ionic and it doesn't work for me. can you me the detailed code so that i will keep that as reference for my project

**Comment by karanracca** [comment]
@Balaji-yogy I had the same issue. I changed from window.TEMPORARY to LocalFileSystem.PERSISTENT and it worked.

**Comment by sau017** [comment]
Hi expert,
I am also facing the same issue while open tiff image in android application using cordova   i am getting the same error as file not found error code 9 . i am attaching sample code here. Can you please help me the correct  solution as i am facing the issue since long time and not able to proceed `further.`
[cordovagetattachment.txt](https://github.com/pwlin/cordova-plugin-file-opener2/files/1294995/cordovagetattachment.txt)

Thanks&Regards,
Saurabh

**Comment by GeorgeAppleton** [comment]
@japostigo-atsistemas your solution wasn't working for me so I added a check for errors and it's throwing 

`DOMException: A URI supplied to the API was malformed, or the resulting Data URL has exceeded the URL length limitations for Data URLs`

Any ideas?

**Comment by timbru31** [comment]
@brainwind-software your approach does not work with Android 7 (API Level 7) anymore, so I suggest to stick with the file-opener way (see https://github.com/pwlin/cordova-plugin-file-opener2/issues/125)

**Comment by jcmag** [comment]
I have an ionic app in which I used inAppBrowser to open a PDF file (downloaded in cordova.file.externalDataDirectory).
Now with Android SDK > 24 I get a FileUriExposedException. 
And same error with FileOpener2...
What could I do ?

**Comment by jcmag** [comment]
I wonder if a special folder exists where app could store files and open them without throwing FileUriExposedException.... any idea?

**Comment by shamilp7** [comment]
> I had the same problem trying to open a PDF located in the www/ folder. So to open it in android: I copied it to the external data directory and then I opened the new file:
> 
> (_uri_ is _/www/path/to/file.pdf_)
> 
> ```
> window.resolveLocalFileSystemURL(cordova.file.applicationDirectory +  uri, function(fileEntry) {
> 
>     window.resolveLocalFileSystemURL(cordova.file.externalDataDirectory, function(dirEntry) {
> 
>         fileEntry.copyTo(dirEntry, 'file.pdf', function(newFileEntry) {
> 
>             cordova.plugins.fileOpener2.open(newFileEntry.nativeURL,'application/pdf');
>         });
>     });
> });
> ```
Isn't this correct sir?
But not working

<button onclick="window.resolveLocalFileSystemURL(cordova.file.applicationDirectory +  /www/18main.pdf, function(fileEntry) {

    window.resolveLocalFileSystemURL(cordova.file.externalDataDirectory, function(dirEntry) {

        fileEntry.copyTo(dirEntry, '18main.pdf', function(newFileEntry) {

            cordova.plugins.fileOpener2.open(newFileEntry.nativeURL,'application/pdf');
        });
    });
});">
        <img src="img/quran.png" />  <br>English</button></td>

**Comment by shamilp7** [comment]
> I had the same problem trying to open a PDF located in the www/ folder. So to open it in android: I copied it to the external data directory and then I opened the new file:
> 
> (_uri_ is _/www/path/to/file.pdf_)
> 
> ```
> window.resolveLocalFileSystemURL(cordova.file.applicationDirectory +  uri, function(fileEntry) {
> 
>     window.resolveLocalFileSystemURL(cordova.file.externalDataDirectory, function(dirEntry) {
> 
>         fileEntry.copyTo(dirEntry, 'file.pdf', function(newFileEntry) {
> 
>             cordova.plugins.fileOpener2.open(newFileEntry.nativeURL,'application/pdf');
>         });
>     });
> });
> ```

Not working for me sir
`<button onclick="window.resolveLocalFileSystemURL(cordova.file.applicationDirectory +  /www/18main.pdf, function(fileEntry) {

    window.resolveLocalFileSystemURL(cordova.file.externalDataDirectory, function(dirEntry) {

        fileEntry.copyTo(dirEntry, '18main.pdf', function(newFileEntry) {

            cordova.plugins.fileOpener2.open(newFileEntry.nativeURL,'application/pdf');
        });
    });
});">
        <img src="img/quran.png" />  <br>English</button></td>`

**Comment by shnist** [comment]
Going to close this issue as the person who opened the issue in the first place resolved it some time ago. If you are experiencing what you believe to be a related problem, please raise a related issue.
