### ISSUE TITLE
Can not display PDF (format invalid) on Android using filetransfer cordovaplugin

### ISSUE THREAD

**Issue by hathemi** [pwlin/cordova-plugin-file-opener2#288]
i get pdf file from web service and i want to download it and open it in my android device.
using this code

> 
> fileTransfer.download(url,this.file.externalDataDirectory+ filename).then((entry) => {
> this.localNotifications.schedule({
> text: ‘Téléchargement de fichier’+filename+’ est terminé !!’,
> led: ‘FF0000’,
> sound: null
> });
> 

download the pdf file but connot open it because it has been saved as “error :invalid format” !!!with size 0.
any solution or suggestion please!

**Comment by pawelzwronek** [comment]
For me looks like problem with filetransfer plugin. Try post as issue [here](https://github.com/apache/cordova-plugin-file-transfer/issues).

**Comment by pwlin** [comment]
@hathemi yes as pawelzwronek mentioned, this issue is related to `cordova-plugin-filetransfer`. And don't forget to add  [Cordova File Plugin](https://github.com/apache/cordova-plugin-file) to your project otherwise  `this.file.externalDataDirectory` will not work.
