### ISSUE TITLE
iOS, callback fired when opened system dialog

### ISSUE THREAD

**Issue by glebfeklistov** [pwlin/cordova-plugin-file-opener2#289]
Plugin fires success event when system dialog with variants to operate file. How can i understand when user pressed cancel or used one of the variant from opened dialog? Plese help us, we using your plugin in bank soft and our clients want show results ofter cossing dialog with cancel button.

**Comment by pwlin** [comment]
@glebfeklistov  I am sorry but currently there is no way to catch the cancel or close button. I am not sure where to add it. One thing you can do as a workaround is to implement some kind of a timer in your application and show the results you want.

**Comment by glebfeklistov** [comment]
Ty
