### ISSUE TITLE
how to open a image

### ISSUE THREAD

**Issue by navneetccna** [pwlin/cordova-plugin-file-opener2#29]
hi i want to open a image in default image viewer which can give me proper zoom in and out and also maintain the image quality .

it is possible to open image with this plugin

**Comment by Langstra** [comment]
Yes it is. You simply need to specify the type of the image and provide the path to the image. Then either the default viewer for that type of image will be opened or you will get a choice to which application you want to open for the file.

**Comment by pwlin** [comment]
As Langstra said, you can indeed open any file that you want, as long as there is an app installed on your phone which can handle that specific file type.
