### ISSUE TITLE
Please publish a tag and release notes for v3.0.1

### ISSUE THREAD

**Issue by timbru31** [pwlin/cordova-plugin-file-opener2#293]
Hi,

thanks for the 3.0.1 update! It would be awesome if you could create a GitHub release for this and add changelog for the bug fixes, as well as the corresponding git tag.
This makes upgrading way more smoothly for us.

**Comment by pwlin** [comment]
@timbru31 I created a GitHub release for 3.0.1 tag. Does that work for you?

**Comment by timbru31** [comment]
Great, thanks for that!
