### ISSUE TITLE
Not Opening .xlsx, .doc, .txt, .csv etc

### ISSUE THREAD

**Issue by santoshmohan35** [pwlin/cordova-plugin-file-opener2#304]
Tryting to open some excel and doc file after creating but unfortunately got error with "code":12,"message":"PATH_EXISTS_ERR"

Only able to Open .pdf files. The same path works in email composer to attach files but not working while opening.

#### Cordova CLI info

    cordova info

Here is the output:
 FileError: {"code":12,"message":"PATH_EXISTS_ERR"}

#### Plugin version

    cordova plugin version | grep cordova-plugin-file-opener2

Here is the output:

#### Sample Code that illustrates the problem
this.fileOpener.open(`file:///storage/emulated/0/Samson/${fileName}`, 'application/msword')
      .then(_ => console.log('Opened successfully')).
      catch(err => console.log('error while opening file', err));

#### Logs taken while reproducing problem
Run 

`adb logcat PluginManager:V CordovaPlugin:V CordovaLog:V chromium:V *:S` 

while testing the bug in your app to get some output from your error. This will help you to understand more about the nature of your problem.

**Comment by pwlin** [comment]
> Create one directory -> create a file -> write to the file -> Opening the same file
> FileError: {"code":12,"message":"PATH_EXISTS_ERR"}

I think the problem is that you are creating a directory with the same name.

Try to open a file without writing to a directory.

**Comment by santoshmohan35** [comment]
yaa that works... i need to check the dir if exist.
