### ISSUE TITLE
Plugin is not handling Cookies in React project

### ISSUE THREAD

**Issue by sterisdotnetteam** [pwlin/cordova-plugin-file-opener2#316]
Hello,

We have two mobile applications, one in ReactJS (15.6) and another in Sencha Touch (2.4.0). Both of them are using file opener2 to call server and download pdf file. 

Using sencha touch mobile app, we can able to successfully download file (Cookies are passing) but with this React app, cookies are not passing while using this plugin. 

Can you please assist with this?

**Comment by shnist** [comment]
hi @sterisdotnetteam, sorry that no one replied to you in a timely manner with your issue. This plugin is only lightly maintained. If you still require assistance please reopen the issue.
