### ISSUE TITLE
Add plugin to npm

### ISSUE THREAD

**Issue by opa-congrid** [pwlin/cordova-plugin-file-opener2#33]
Do you have plans of adding this plugin to npm in the near future?

**Comment by Langstra** [comment]
My question too.

**Comment by remcohaszing** [comment]
I would like to see this in npm as well.

**Comment by escolhatecnologia** [comment]
please  put the  new  version  to NPM 

+1

**Comment by pwlin** [comment]
Sorry if it took a long time. I have pushed the current version to npm.

https://www.npmjs.com/package/cordova-plugin-file-opener2

which supposedly you can use by issuing:

    cordova plugin add cordova-plugin-file-opener2

Please let me know if it doesn't work.

**Comment by escolhatecnologia** [comment]
@pwlin   Thanks!
