### ISSUE TITLE
There was a problem parsing the package for android install apk

### ISSUE THREAD

**Issue by 15399233911** [pwlin/cordova-plugin-file-opener2#335]
![微信图片_20221102223012](https://user-images.githubusercontent.com/14158161/199516578-087e2209-67f7-439f-9790-186d7b5f3533.jpg)
![微信图片_20221102223024](https://user-images.githubusercontent.com/14158161/199516599-805d68ae-a298-4eda-adb9-8c43e05182c7.jpg)
help me, thanks a lot.

**Comment by shnist** [comment]
Hi, 

When raising a bug please fill out it according to this [template](https://github.com/pwlin/cordova-plugin-file-opener2/blob/master/.github/ISSUE_TEMPLATE/bug_report.md).
