### ISSUE TITLE
Can't edit file

### ISSUE THREAD

**Issue by Kroberus** [pwlin/cordova-plugin-file-opener2#337]
when i open the file with cordova plugin open2 it can't edit the file but still the same file but open with the default app on ios it can be edited.

#### Cordova CLI info

    cordova ios 6.2.0

#### Plugin version
    cordova-plugin-file-opener2: 3.0.5
![IMG_1355](https://user-images.githubusercontent.com/118706956/208074610-3c0cdbb4-ee85-45a3-866a-1580748156f3.PNG)
![89357978-AE65-4270-B031-335C93EA1636](https://user-images.githubusercontent.com/118706956/208074617-9c40a567-4b62-441a-abb1-117c50f4f313.png)

**Comment by Kroberus** [comment]
@pwlin 
Please support me!
thanks!

**Comment by shnist** [comment]
hi @Kroberus,
Thanks for your message. The files are opened by apps that on the device / emulator. This file opener plugin has no control over the capabilities of those apps. This is likely a limitation of the android app that the file has been opened with.
