### ISSUE TITLE
Getting error after updating plugin to 4.0.0 on Android Studio

### ISSUE THREAD

**Issue by vinodkumar-shimpi** [pwlin/cordova-plugin-file-opener2#339]
Hello Team,

Was having an issue building for Android on ionic, I have updated plugin with latest version 4.0.0, it was working fine with 3.0.5.

I am using Android Studio Electric Eel | 2022.1.1 Patch 1 for ionic project.

error: package androidx.core.content does not exist
public class FileProvider extends androidx.core.content.FileProvider {
                                                       ^
Please someone help me.

**Comment by jwasnoggin** [comment]
Are you using an old version of cordova-android? Versions before 10 don't support androidx I believe.

**Comment by shnist** [comment]
hi, yes as per the [release notes ](https://github.com/pwlin/cordova-plugin-file-opener2/releases/tag/v4.0.0) you'll need to upgrade to cordova-android version 10 or higher to use version 4 of the plugin.
