### ISSUE TITLE
This plugin has a maintained forked repo now - please use and follow

### ISSUE THREAD

**Issue by EYALIN** [pwlin/cordova-plugin-file-opener2#342]
unfortunately, this plugin creator @pwlin , did fantastic work, and we highly appreciate him not maintaining this plugin anymore (not responding for a while).
we moved to a maintained plugin (which forked from this one) to here:
https://github.com/EYALIN/community-cordova-plugin-file-opener

you can install it as an npm package:
cordova plugin add community-cordova-plugin-file-opener --save

**Comment by pwlin** [comment]
@EYALIN  I have checked your fork and it's actually a couple of commits behind this repo. Is there anything you have added in a different repo?

**Comment by EYALIN** [comment]
@pwlin Sorry, I thought it was not maintained anymore, like many other plugins. because this is what you wrote in the readme. I file on your homepage.
unfortunately, most of the plugins are not maintained so I just forked a lot of them to maintain them. 

please close this post, it's not relevant to this plugin.

thanks.

**Comment by pwlin** [comment]
No it's fine I applaud and support your efforts to work further on this plugin :) It's just that I have not seen anything added to your fork and it is actually a couple of commits behind the main branch here. I will keep an eye on your fork and if you commit any changes, we can always see if we can merge them back here. Good luck!

**Comment by EYALIN** [comment]
excellent @pwlin thanks. I appreciate your work.

I wanted to donate to you but didn't see any sponsorship option on your page.
if you add please update me, and I will donate.

I highly appreciate plugin maintainers :-)
