### ISSUE TITLE
Wp8 -  doesnt work  in   phonegap build

### ISSUE THREAD

**Issue by escolhatecnologia** [pwlin/cordova-plugin-file-opener2#35]
Wp8 -  doesn't work in phonegap build

**Comment by pwlin** [comment]
Is there any specific error message?

**Comment by escolhatecnologia** [comment]
How  to  share  a  audio(mp3)  ?

your  code  only open  a  audio player:
  Windows.System.Launcher.LaunchFileAsync(file);  
https://github.com/pwlin/cordova-plugin-file-opener2/blob/master/src/wp8/FileOpener2.cs#L29

I  need  share  audio  with other  apps  like  whatsapp

**Comment by pwlin** [comment]
@escolhatecnologia 
I don't think what you are looking for is under the scope of this plugin. This plugin only tries to open a file with its appropriate application. Probably you should find another plugin for sharing your file with other apps?

**Comment by escolhatecnologia** [comment]
@pwlin    I need  use open  app chooser
not default application 

it's possible on wp8?

**Comment by pwlin** [comment]
@escolhatecnologia 
The WP8 portion of this plugin has been kindly contributed by @Gillardo as you can see on the commit logs of the file you mentioned. Maybe you can contact him and ask if he can make the changes you want?

**Comment by escolhatecnologia** [comment]
@pwlin   Thanks!

**Comment by pwlin** [comment]
@escolhatecnologia 
No problem at all! I am sorry for not being able to help you directly.

**Comment by Gillardo** [comment]
Whats up?  I have am using this plugin in a current plugin that is
working.  Is the version online not working?  If not, i can compare my
version to the one online

**Comment by pwlin** [comment]
Hey @Gillardo 
Good to see you back and thanks for trying to help @escolhatecnologia  :)
If you like to send me any pull request just let me know.
