### ISSUE TITLE
Open 'app chooser'  in  wp8

### ISSUE THREAD

**Issue by escolhatecnologia** [pwlin/cordova-plugin-file-opener2#36]
@Gillardo  
I need to open "app chooser"
not default application
Is it possible on wp8?

your code only open a default application
Windows.System.Launcher.LaunchFileAsync(file);
https://github.com/pwlin/cordova-plugin-file-opener2/blob/master/src/wp8/FileOpener2.cs#L29

**Comment by Gillardo** [comment]
Not too sure, i can have a look soon, but i use the windows version now
(windows 8.1) as that offers you this exact functionality

On Wed, Aug 12, 2015 at 3:27 PM, escolhatecnologia <notifications@github.com

**Comment by Gillardo** [comment]
You may want to have a look at the windows version and see if you can pass in a parameter like the windows version.

Windows allows you to supply options like so

```sh
var options = new Windows.System.LauncherOptions();
options.displayApplicationPicker = true;
```

Then you call it using this

```sh
Windows.System.Launcher.launchFileAsync(file, options)
```

**Comment by escolhatecnologia** [comment]
@Gillardo   i  need    open a audio,  then   "app chooser"  and   choose  WhatsApp

this doesn't  work on wp 8.1:
options.displayApplicationPicker = true;

with audio file this  opens  audio player app (default app)
doesn't open   "app chooser"

any suggestion? 
Thanks

**Comment by Gillardo** [comment]
Have u got more than 1 audio app installed on the device?

I use it with pdf files and it gives me options of all pdf viewers

**Comment by Gillardo** [comment]
What extension have the audio files got?  Are tey compatible with the audio apps you have installed?  Can you try it with a PDF file to confirm that you see the chooser then?

**Comment by Gillardo** [comment]
I believe that the WP8 version also requires the "whole" file path too. Maybe this is your issue?

**Comment by pwlin** [comment]
I think there is a misconception about what this plugin does here :)
This plugin launches a file you are trying to open in one of the applications already registered as player/opener/launcher of that particular file type. So the subsequent "App Chooser" dialog in different platforms is not an all-in dialog box to open any kind of file in any randomly selected app on the device. It only shows those apps which already registered themselves as being capable of opening/playing/launching that file type.

@escolhatecnologia is trying to open an audio file in Whatsapp. But Whatsapp is obviously not an audio player :)  That is why I really think you should look into other kind of plugins, something that can "send" or "share" your file with other apps. In Android world, it's called [`ACTION_SEND`](http://developer.android.com/reference/android/content/Intent.html#ACTION_SEND) intent which gives you a dialog like:

![](http://i.stack.imgur.com/cFYbk.png)

Is there any equivalent of Android's `ACTION_SEND` intent in WP8?
