### ISSUE TITLE
don't open dataurl

### ISSUE THREAD

**Issue by loverdrive** [pwlin/cordova-plugin-file-opener2#37]
Hi. This is my fileOpener2 function:

    cordova.plugins.fileOpener2.open(
            url,
            'application/pdf',
            { 
                error : function(e) { 
                    console.log('Error status: ' + e.status + ' - Error message: ' + e.message);
                },
                success : function () {
                    console.log('file opened successfully');                
                }
            }
        );

where 'url' is a variable containing a dataurl. The format of that is:

    data:application/pdf;base64,JVBERi0xLjMKJf////8KN .......

but it doesn't appear the "open with" popup. But if i insert a web url, it works.

Is the library don't supporting dataurl? Is there a way to solve this?

Thank you!

**Comment by pwlin** [comment]
In which platform are you having this problem? iOS, Android, or Windows?

**Comment by loverdrive** [comment]
iOS

**Comment by pwlin** [comment]
Unfortunately, I think you can't open base64 data uris directly in iOS. Try to locally save it as a binary file somewhere first, and then open that file.

**Comment by loverdrive** [comment]
Ok, thank you. So is it a problem of iOS system?

**Comment by pwlin** [comment]
I can't say it's a "problem". It's just the way iOS works :)
