### ISSUE TITLE
after update to iOS 9 plugin not  working

### ISSUE THREAD

**Issue by escolhatecnologia** [pwlin/cordova-plugin-file-opener2#40]
I can't  open   files   after update   to  iOS9  
plugin  not working anymore.

@pwlin   any  solution  for  iOS9?

Thanks!

**Comment by jksoftpro** [comment]
I confirm the same issue once updated to iOS9.

@pwlin Any chance to fix it soon, please?

**Comment by pwlin** [comment]
see #39
