### ISSUE TITLE
iOS 9 support

### ISSUE THREAD

**Issue by jmrezayi2** [pwlin/cordova-plugin-file-opener2#43]
Hello!

First of all, thank you so much for this awesome plugin. I have been using it since 2014.

The plugin fails on iOS 9, but it works perfectly in iOS 8 (even though files with special character names in them fail as well). I wanted to know if you plan to take a look into this, or if I can help with getting iOS 9 support for this plugin.

Thank you so much!

**Comment by pwlin** [comment]
Have you checked the latest version (2.0.0) either from Github or NPM? People were graciously fixing iOS 9 bugs and sent me a couple of pull requests. I have merged them all which should have fixed all the iOS 9 issues. Please test the latest version and let me know if you still have a problem.

**Comment by jmrezayi2** [comment]
Hey!

Not really, I have been using 1.11 and thought that is the latest version. I will look into it.

Thanks!

**Comment by jmrezayi2** [comment]
By the way, is it possible for you to submit it to phonegap plugins as well? can save a lot of confusion for people who are not that familiar with Cordova.

**Comment by pwlin** [comment]
An older version of this plugin is [already in Phonegap Build](https://build.phonegap.com/plugins/1117), but I can not update it because a couple of months back they changed their website and currently only paid customers can submit plugins. I marked the plugin as deprecated there and added the link to NPM repo, so hopefully users can be notified.

**Comment by jmrezayi2** [comment]
Hello!

Thank you for your information and marking it on deprecated.

I tried version 2.0.0 on iOS9 and it is working. However, there is this issue:

If one is trying to open a pdf file, in the window, choosing "Copy to iBooks" opens it fine.
However, if one chooses "Mail" as the opening app, it opens it in the mail app with attachment, but it gets frozen.

Do you think what could be the issue, or even prevent the iOS from showing "mail" as an option?

Thank you so much in advance!

**Comment by pwlin** [comment]
Yes that is a known problem and was discussed in issue #17 last year. Some users said that another Cordova plugin called [Cordova-Open](https://github.com/cordova-bridge/open) solved their problem, so maybe you can try that one?

**Comment by jmrezayi2** [comment]
Hey You are a life saver! It seems to be working fine on iOS 9. I need to check on older iOS versions as well. Since I am using phonegap build, it is called "com.disusered.open" there.

By the way I have a javascript that given the file extension, spits out the meme that your plugin needs. Do you think it is a good idea to combine it with your plugin so that the application type becomes an optional argument?

**Comment by pwlin** [comment]
Good to hear you solved your problem. I don't think making the MIME-type an optional argument is a good idea at the moment, it will over-complicate the code and will also limit the plugin to those MIME-types defined in the script. And let's be honest, if someone does not know the MIME-type of the file they are trying to open, they have a much larger problem don't they? :) But thanks for the offering.

**Comment by jmrezayi2** [comment]
Hey I see your point! But on the other hand most people are noobs 

Okay, So this issue is closed. Thank you so much for being such a cool developer! I wish I could meet you in person and have a talk!

**Comment by pwlin** [comment]
Hey thanks for your nice words! My email address is on my profile, you can always send me a mail and invite me to a coffee? ;)  

Yes you are right that this plugin should be more noob-friendly. I added a link to known MIME-types in `Notes` section of README.md file. It will help to find the correct MIME-type people are looking for.

**Comment by arathikundpur** [comment]
My app is getting re initialised  when i use this plugin to open pdf files. Any work arounds? PS: This is on IOS 9. Same issue with cordova-open and the cordova launcher plugin too

**Comment by pwlin** [comment]
@arathikundpur As the reinitialization also happens with other plugins, you would want to post a question in [Phonegap discussion group](https://groups.google.com/forum/#!forum/phonegap)

**Comment by arathikundpur** [comment]
Sorry for distracting you... fileopener2 is actually crashing on ios9 and
not reinitializing.

here...

#import <UIKit/UIKit.h>


int main(int argc, char* argv[])

{

    @autoreleasepool {

        *int retVal = UIApplicationMain(argc, argv, nil, @"AppDelegate");*

        return retVal;

    }

}

Arathi

**Comment by PedroJusto** [comment]
Same problem here! fileopener2 is not reinitializing.

**Comment by PedroJusto** [comment]
@arathikundpur did you solve the problem?

**Comment by pwlin** [comment]
I think this has something to do with the way your app is made, as other plugins cause the same problem.

try to put your `@autoreleasepool` inside a `try catch` and catch the error:

    @autoreleasepool {
        @try {
             // do your stuff
         }
        @catch (NSException *exception) {
            // handle the exception   
        }

What kind of exception are you getting?

**Comment by PedroJusto** [comment]
@pwlin can you confirm that in ios9 iPhone device works fine? in iPad works fine

**Comment by dickverweij** [comment]
Hi there, how to force npm to download the latest version of this plugin?

ionic CLI wont let me download version 2.0.1

**Comment by PedroJusto** [comment]
thank you @pwlin , at the time I'm using "com.disusered.open" plugin wich seems to work fine in ios9
