### ISSUE TITLE
Open a locally saved image on Windows 8.1 platform

### ISSUE THREAD

**Issue by Chirag-Chauhan** [pwlin/cordova-plugin-file-opener2#44]
Hi,

I have created a cordova based hybrid application for Windows 8.1 platform with fileopener2 plugin added. I am using Visual 2013 Update 4 IDE for development and testing. I have my image saved locally on device say "C:/image.jpg".

I have used following code to open the file:

            try {
                cordova.plugins.fileOpener2.open(
                    'C://image.jpg', 
                    'application/jpg', 
                    { 
                        error : function(e) { 
                            console.log('Error status: ' + e.status + ' - Error message: ' + e.message);
                        },
                        success : function () {
                            console.log('file opened successfully');                
                        }
                    }
                );
            }
            catch(e) {
                console.log(e);
            }

I am not able to see any errors and the image is also not displayed.

Any help will be much appreciated.

Thanks,
Chirag.

**Comment by pwlin** [comment]
I am sorry but the Windows version of this plugin was generously contributed by another user and I don't work with it. At first I see a couple of issues with your code:

`application/jpg` might be changed to `image/jpeg` or `image/jpg`

`C://image.jpg` might be changed to `file:///C://image.jpg`
