### ISSUE TITLE
Doesnot work on iOS8 anymore?

### ISSUE THREAD

**Issue by pwinkelm** [pwlin/cordova-plugin-file-opener2#46]
Hello,

I am working on a project and used the earlier version of this plugin within the developed App. All worked fine.
Because our customer updated some iPads to iOS9 I was testing this upgraded plugin, but on iOS8 it doesnot work anymore? The App loses focus and the 'Home page' of the iPad is shown. Am I forgetting something? Maybe I need to change something in the configuration?

I am not sure it works on iOS9, I did not test that yet.

**Comment by pwinkelm** [comment]
By the way, when I change back the changed line fileURL = [NSURL URLWithString:path]; to fileURL = [NSURL fileURLWithPath:path]; all seems to work again for iOS8.

**Comment by pwinkelm** [comment]
I am sorry, but on iOS9 it doesnot work for me as well.
The only thing I did, to get it work on iOS9 was building the App with the old plugin version again.

**Comment by pwlin** [comment]
Hi @pwinkelm 
Unfortunately I don't have an iDevice to test and the iOS 9 version was generously contributed by other users. Did you test the new plugin on a fresh, empty project? It might be a good idea to delete the old plugin completely and add the new version.

**Comment by pwinkelm** [comment]
Hello @pwlin, I donot know all ins and outs but I was able to test on several devices and there is nothing wrong with the 'old' version, but you need to rebuild your App using the correct XCode version before running on iOS9.
The [UIDocumentInteractionController  interactionControllerWithURL:fileURL] just needs this fileURLWithPath ([NSURL fileURLWithPath:path]) otherwise it will abort. As stated in comment 2: changing fileURL = [NSURL URLWithString:path]; to fileURL = [NSURL fileURLWithPath:path]; also solved the problem (and that was the only change made).

**Comment by chineseneo** [comment]
Hey @pwinkelm 

I met the same problem and I solved it by changing the file path from a `cdvfile://` to a `file://`, by using `fileEntry.toURL()`. I don't know whether this is also cause of your problem.  :blush:

**Comment by Gillardo** [comment]
Hey @pwinkelm .  I too am getting the same problem, as i pass in a file path to fileOpener which has worked in all versions up to now.  If i change the code to what you have suggested it works.  My question, if the above change works for iOS on all versions, can it not be changed to use that instead?

**Comment by pwinkelm** [comment]
@Gillardo, probably you are right but for now I stick to the old version because I have no time left to test furthermore (due to 'project'agreements :-)) and I don't wanna change the new version when I don't test it fully.
 
One additional remark ( @chineseneo ) : in 'my' code I get the file path from fileEntry.toURL and then even remove the "file://" from the path I got. Otherwise the "Copy to iBooks" (or "Copy to Adobe") did not work in iOS9. iOS8 handles this correctly as well but the link shows there "Open in iBooks".

**Comment by chineseneo** [comment]
@pwinkelm did you checkout the log on xcode about the problem?

**Comment by pwinkelm** [comment]
@chineseneo, no I did not.

**Comment by MrChris123** [comment]
First off - awesome plugin!
Can I just clarify what you mean by the fileEntry.toURL comment please as I am also experiencing iOS9 issues? I have the latest version (2.0.2) and there is no mention of it in the README. Also can I just point out that the README still says 2.0.1 even though the package.json says 2.0.2.
Thanks.

**Comment by pwlin** [comment]
`fileEntry.toURL` is the reference to your file when using [HTML5 FileSystem API ](http://www.html5rocks.com/en/tutorials/file/filesystem/) (the preferred way of manipulating files with Cordova)

Sorry for the version discrepancies. I'll bump the version in the README.

**Comment by davidzas** [comment]
Hi,

I'm having the same issue. I have the 2.0.2 version and it works on android but keep showing sharing options on IOS 9. I'm saving files with cordova.file.documentsDirectory path and file unique file name. Is there a formal solution to this?

**Comment by pwlin** [comment]
Hi david, I am really sorry but currently I haven't got any iDevices to test iOS issues.

**Comment by Narretz** [comment]
@pwlin You should probably put a note in the readme that this plugin has not been tested with iOs8 / iOs9. This is a pretty big issue. I understand that you cannot test everywhere, but you should at least make it clear to the users.

**Comment by pwlin** [comment]
@Narretz Is there anything in particular that is not working for you?

**Comment by vzharkov** [comment]
@pwlin I have the same issue on the IOS10. And I think that the #103 issue is about the same problem
