### ISSUE TITLE
 $cordovaFileOpener2.open - showing sharing options - IOS issue

### ISSUE THREAD

**Issue by ashishsingh16** [pwlin/cordova-plugin-file-opener2#47]
When I am trying to open an image file from IOS using  $cordovaFileOpener2.open it shows sharing options on ios (Message, Mail, Notes, iCloud Photo Sharing, Save to PDF to iBooks and more). And When i share file on eg. Message it show download file as attachment but it is not directly opening the file in Photo Viewer.

First I am downloading the file from server by using  $cordovaFileTransfer.download after this I trying to open the same file  $cordovaFileOpener2.open. In ios it start showing sharing options but in android it works perfectly.

I am testing on iOS 9.0.2

Please help.

Thanks

**Comment by pwlin** [comment]
Which version of plugin are you using? I recently upgraded the plugin to 2.0.0

Are you using the latest version?

**Comment by ashishsingh16** [comment]
I am using 
"name": "cordova-plugin-file-opener2",
"version": "2.0.0",

**Comment by abhinavgujjar** [comment]
I have the exact same issue. Could this be because all the cordova.file.* locations provided are private. Which means that while the image can be saved and shared, it cannot be directly opened. Sounds a bit weird, but hey - that's iOS most of the times.

**Comment by abhinavgujjar** [comment]
@ashishsingh16 - I have the exact same scenario and I've looked at a couple of options - one is using the inAppBrowser plugin (this guys works properly but the images gets scaled weirdly). 

The other option is simply to use HTML to display the image with a pinch to zoom option on the same page itself.

**Comment by TankOs** [comment]
Same issue here.

**Comment by pwlin** [comment]
Try to change plugin's ios source (FileOpener2.m) line:

fileURL  = [NSURL **URLWithString**:path]; 

to:

fileURL  = [NSURL **fileURLWithPath**:path]; 

Does that help?

**Comment by pwlin** [comment]
Otherwise, use `fileEntry.toURL()`. Does that solve your problem?

**Comment by barbax** [comment]
Same issue here. This is the snippet of code that used to work before iOS update:

```javascript
cordova.plugins.fileOpener2.open(
                filePath, 
                'application/pdf',
                {
                    error: function (e) {
                        console.log('Error status: ' + e.status + ' - Error message: ' + e.message);

                    },
                    success: function () {
                        console.log('file opened successfully');
                    }
                }
        );
```
any idea?

**Comment by pwlin** [comment]
What is the value of `filePath`?

**Comment by barbax** [comment]
filePath is like this:
```
file:///var/mobile/Containers/Data/Application/96AB1E9D-A011-46DD-B774-9AA572FBB80C/Library/NoCloud/(05)@motion_Luglio_2009.pdf
```

**Comment by pwlin** [comment]
Go to `FileOpener2.m` file and at line 50, change:

`fileURL = [NSURL URLWithString:path];`

to:

`fileURL = [NSURL fileURLWithPath:path];`

Does that help?

**Comment by barbax** [comment]
On my code the situation was the opposite than you described (since my plugin version is outdated).

In line 50 there was
```javascript
        fileURL = [NSURL fileURLWithPath:path];
```
that i changed to

```javascript
        fileURL = [NSURL URLWithString:path];
```
Now its working again.
I just noticed that i'm using version 1.0.11 (did't update for a while).

Now, i'll try tu upgrade and check what does happen.

**Comment by barbax** [comment]
i Update the plugin to the latest version (that is using fileURL = [NSURL URLWithString:path];), and everything works fine. Sorry for the confusion and thanks for your support.

**Comment by pwlin** [comment]
Ok glad you resolved your issue. good luck.

**Comment by Tobiaswk** [comment]
I'm experiencing the same problem. It does not matter whether I use [NSURL URLWithString:path] or [NSURL fileURLWithPath:path].

**Comment by davidzas** [comment]
@Tobiaswk I also tried both and the problem persists. Did you already find the solution?

**Comment by Tobiaswk** [comment]
@davidzas I did solve it. I did my own implementation; https://github.com/Tobiaswk/cordova-plugin-file-opener2

I differentiate between regular files and pdf. If the file passed is a pdf it will open it directly. I'm not sure it is what you want, but the most important thing is that it works for me now.

**Comment by pwlin** [comment]
If all you need is the ability to open a PDF document, you don't even need this plugin altogether :)
You can simply use `window.open("url_to_pdf_file.pdf")` to open up the PDF file. Current webkit releases have built-in capabilities for previewing a PDF document without needing any third party tool.

**Comment by Tobiaswk** [comment]
Sounds great but I can't that to work.

`Resource interpreted as Document but transferred with MIME type application/pdf`

**Comment by pwlin** [comment]
@Tobiaswk 
First try to use it like this:

```javascript
window.open('url_to_pdf_file.pdf', '_blank');
```
_(notice the `_blank` target);_

If that still doesn't work, use the [official `InAppBrowser` plugin](https://www.npmjs.com/package/cordova-plugin-inappbrowser) which is a drop-in replacement for `window.open` 

Add it to your project and then use it like:

```javascript   
//re-assign window.open at load:
document.addEventListener("deviceready", function() {
    window.open = cordova.InAppBrowser.open;
}, false);
// then call window.open normally in other parts of your app:
window.open('url_to_pdf_file.pdf', '_blank');
```
Previously it was a built-in plugin but it seems they split it now into its own repository. By the way, here is [the list of all official plugins](http://cordova.apache.org/docs/en/latest/cordova/plugins/pluginapis.html)
