### ISSUE TITLE
doesn't show up if inappwebbrowser is opened

### ISSUE THREAD

**Issue by seraj-ahmad** [pwlin/cordova-plugin-file-opener2#48]
I am trying to call this plugin and it works fine from webview. but it doesn't show up if inappwebbrowser is open.

**Comment by pwlin** [comment]
Can you explain a little bit more about what are you trying to do?

**Comment by seraj-ahmad** [comment]
I opened a document in a separate webview using inappbrowser plugin. Let's assume a pdf document. I added a share button in the webview toolbar. When toolbar button is pressed, I sent an event to JS. js responds by calling your plugin. However, webview is still open as a modal. Now since you are using 'cordova webview' as an argument to 'inView', which is currently inactive. hence the command doesn't show anything. If there is a  way to know if another view is currently active, and use that instead as an argument to 'inView' in presentOptionsMenuFromRect method, problem should be solved

**Comment by pwlin** [comment]
Can you use Cordova Webview as [explained here](http://cordova.apache.org/docs/en/latest/guide/platforms/android/webview.html)?
