### ISSUE TITLE
iOS plugin crash after second run

### ISSUE THREAD

**Issue by lvbeck** [pwlin/cordova-plugin-file-opener2#49]
my application generate a PDF file and try to open it in adobe reader, it did work for the first time, but if i press the button "back to my app" from adobe reader to my application, regenerate the PDF again and try to open it for the second time, the plugin crashes, here are the logs:

```
Warning: Attempt to present <_UIDocumentActivityViewController: 0x13e955800>  on <MainViewController: 0x13e538130> which is already presenting <_UIDocumentActivityViewController: 0x13e835400>
Assertion failure in -[_UIOpenWithAppActivity performActivity], /BuildRoot/Library/Caches/com.apple.xbs/Sources/UIKit/UIKit-3512.29.5/UIDocumentInteractionController.m:408
Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'UIDocumentInteractionController has gone away prematurely!'
First throw call stack:
(0x1837a0f48 0x1982eff80 0x1837a0e18 0x184694a1c 0x1893b2fe4 0x1895db320 0x189088ba4 0x18908bd9c 0x188e63668 0x188d6f240 0x188d6ed3c 0x188d6ebc4 0x188535c2c 0x10018dc68 0x100193710 0x1837581f8 0x183756060 0x183684ca0 0x18e6ec088 0x188d9cffc 0x1000bff24 0x198b328b8)
libc++abi.dylib: terminating with uncaught exception of type NSException
```

tested on iOS 9.1 using the master branch of plugin

**Comment by moesphemie** [comment]
having the same issue with html2pdf… whats going on here?!

**Comment by pwlin** [comment]
Can you please tell me which iOS version are you using? Is this an issue in iOS 8 or iOS 9?

**Comment by lvbeck** [comment]
@pwlin it's on iOS 9.1

**Comment by niuemperor** [comment]
have the same problem。is there everyone has some solutions？@pwlin

**Comment by rpc1910** [comment]
I'm having the same problem when opening PDF's in my application. Performed tests with iOS 8 and iOS 9.

Is there a solution to this problem?

**Comment by pwlin** [comment]
I am sorry, currently I have no access to an iDevice to do any test on this.

But if all you need to do is opening a PDF file in your app, you shouldn't need this plugin at all. Use Cordova's [InAppBrowser plugin](https://cordova.apache.org/docs/en/latest/reference/cordova-plugin-inappbrowser/index.html). It will open your PDF file in a separate window. Simple and easy.

**Comment by nicolastakashi** [comment]
Hello everyone.

I`ve the same issue today.
Is there a solution to this problem?

**Comment by greaterking** [comment]
same here? Seems like view the pdf a 2nd time some how invokes the keyboard "during" the animation of the window.

`0   CoreFoundation                      0x0000000112065d4b __exceptionPreprocess + 171
	1   libobjc.A.dylib                     0x0000000111ac721e objc_exception_throw + 48
	2   CoreFoundation                      0x00000001120cf2b5 +[NSException raise:format:] + 197
	3   Foundation                          0x000000010e8ab06c _AssertAutolayoutOnAllowedThreadsOnly + 180
	4   Foundation                          0x000000010e8aadb4 -[NSISEngine _optimizeWithoutRebuilding] + 61
	5   Foundation                          0x000000010e6d25dc -[NSISEngine optimize] + 91
	6   Foundation                          0x000000010e8a8cd4 -[NSISEngine performPendingChangeNotifications] + 84
	7   UIKit                               0x000000010ec867a6 -[UIView(Hierarchy) layoutBelowIfNeeded] + 1123
	8   UIKit                               0x000000010f646161 -[UIInputSetHostView layoutIfNeeded] + 105
	9   UIKit                               0x000000010f64cd60 __82-[UIInputWindowController updateToPlacement:withNormalAnimationsAndNotifications:]_block_invoke + 81
	10  UIKit                               0x000000010ec8d239 +[UIView(Animation) performWithoutAnimation:] + 90
	11  UIKit                               0x000000010f647440 -[UIInputWindowController performWithoutAppearanceCallbacks:] + 27
	12  UIKit                               0x000000010f64746b -[UIInputWindowController performWithoutCallbacksOrNotifications:] + 34
	13  UIKit                               0x000000010f64cd04 -[UIInputWindowController updateToPlacement:withNormalAnimationsAndNotifications:] + 212
	14  UIKit                               0x000000010f2c61d2 -[UIInputViewAnimationControllerBasic prepareAnimationWithHost:startPlacement:endPlacement:] + 33
	15  UIKit                               0x000000010f64bcc4 __77-[UIInputWindowController moveFromPlacement:toPlacement:starting:completion:]_block_invoke.859 + 62
	16  UIKit                               0x000000010f35f115 -[_UIRemoteKeyboards ignoreLayoutNotifications:] + 27`

**Comment by dermansi** [comment]
Same error here, too

**Comment by pwlin** [comment]
There has been a couple of new releases since then. Can you please upgrade and test if you still have issues? thanks
