### ISSUE TITLE
cordova.plugins.fileOpener2.open() wont work on Windows

### ISSUE THREAD

**Issue by zulalay** [pwlin/cordova-plugin-file-opener2#51]
I am using Apache Cordova in Visual Studion 2015 and running the project as WIndows project.

In the app, I download pdf file and then try to open it using

    cordova.plugins.fileOpener2.open(
            options.filePath,
            options.fileType,
            {
                success: function () {
                    console.log('[DEBUG] file opened successfully');
                },
                error: function (error) {
                    console.log('[ERROR] status: ' + error.status + ' - Error message: ' + error.message);
                }
            }
        );

where **options.filePath** is 'ms-appdata:///local//cache.pdf'
and **options.fileType** is 'application/pdf'

However i get : 
Exception is about to be caught by JavaScript library code at line 49, 
column 14 in ms-appx-web://<package_name>/www/plugins/cordova-plugin-file-opener2/src/windows/fileOpener2Proxy.js

0x80070057 - JavaScript runtime error: The parameter is incorrect.

Any ideas what can be wrong with my parameters?

Thanks

**Comment by pwlin** [comment]
Hi @Gillardo can you please take a look into this issue? Does this have something to do with the recent PR changes we merged into the master? Thanks very much.

**Comment by Eeems** [comment]
I'm also having this issue.

**Comment by Gillardo** [comment]
Sorry been bit busy. I will check this soon. The pr changes were done by
someone else but i can look still. I am using the plugin but i am using the
full device path and it works for me

**Comment by pwlin** [comment]
Thanks @Gillardo for looking into it. Maybe @ielcoro knows how to fix this?

**Comment by ielcoro** [comment]
I will look into it

**Comment by pwlin** [comment]
Thank you very much @ielcoro !

**Comment by zulalay** [comment]
Hey guys. I actually managed to move one step forward.
instead of options.filePath is 'ms-appdata:///local//cache.pdf',
i was using Windows.Storage.ApplicationData.current.localFolder to get the path to the appdata folder. 

Using path like that i managed to overcome that issue: JavaScript runtime error: The parameter is incorrect.

However i still couldnt open the pdf :) i got another error. It was in spanish something that it cant open such file. (but i know that this pdf is not corrupted or anything, and i dont have anything spanish related on my computed).

I ll write my situation in more details on monday

**Comment by zulalay** [comment]
Okay, so..
1)  
instead of "ms-appdata:///local/cache.pdf"
i use now "isostore:/cache.pdf"
This helped me to get rid of the error "0x80070057 - JavaScript runtime error: The parameter is incorrect."

(To check the actual path on your PC use: Windows.Storage.ApplicationData.current.localFolder.path

my value is "C:\Users\{username}\AppData\Local\Packages\com.smartday.touch_h35559jr9hy9m\LocalState" )
2) I am getting new exception:
Error abriendo el archivo
fileOpener2Proxy.js (58,14)

Why in spanish?? I am sure that my .pdf is correct.

any help with be highly appreciated. thanks

**Comment by zulalay** [comment]
i am using it with "ms-appdata:///local/cache.pdf" and it looks like it works!

**Comment by ielcoro** [comment]
@zulalay sure, the extra / is wrong, paths should use only one /.

I think that what you are sawing when calling Ext.device.filesystem.FileEntry is visual studio and .net escaping the value /, however under the hood it does not have two / at all, only one.
