### ISSUE TITLE
filename with spaces shows error: file not found 

### ISSUE THREAD

**Issue by zuna003** [pwlin/cordova-plugin-file-opener2#53]
Hi Good Day Everyone, I'm using fileopener2 version 2.0.2.If the filename consist of spaces it shows an error: file not found.Can someone give me an idea to fix this error? Thank you.

**Comment by pwlin** [comment]
Hi @zuna003,
Does this happen on iOS?

**Comment by zuna003** [comment]
Hello @pwlin yes it's not working on iOS. btw, this is my code on android, it worked but im not really sure if it's the right way. 
![code](https://cloud.githubusercontent.com/assets/8409364/11777628/8d692430-a28a-11e5-8d70-05cf16af5961.png)

**Comment by pwlin** [comment]
What is the value of `decodeURIComponent(entry.toURL())`?

**Comment by zuna003** [comment]
based on https://github.com/pwlin/cordova-plugin-file-opener2/issues/14 , someone recommend to use that.

**Comment by pwlin** [comment]
Yes exactly, so you problem should be fixed already. What iOS version are you using and what is the value of `decodeURIComponent(entry.toURL())`?

**Comment by pwlin** [comment]
So did you finally resolve your problem?

**Comment by zuna003** [comment]
I'm really sorry I forgot to inform you, yes it's working already, but I did not change my code and test it again and it worked..btw Thank you very much and Happy new year.

**Comment by pwlin** [comment]
Glad it works. good luck and happy new year to you too!

**Comment by mathiasconradt** [comment]
Above mentioned approach does not work for me. I'm on iOS 9.2.1, using plugin version 2.0.2.
In my case, the decoded uri is: `file:///var/mobile/Containers/Data/Application/9C554B7E-556C-4747-8572-07B01BA03EF3/Documents/mySORBADocuments/c978b393-bfa2-46ad-8eb1-86b6ec0c6907/Jan%20Becker%20Tickets.pdf`
I don't seem to be the only one. See https://github.com/pwlin/cordova-plugin-file-opener2/issues/14#issuecomment-183295881
