### ISSUE TITLE
iOS 9 File Edit Support

### ISSUE THREAD

**Issue by cmiagssh** [pwlin/cordova-plugin-file-opener2#54]
Hi

With iOs9 Apple has introduced mechanisms to not just open, but also edit files. I have searched a Codrova plugin that would provide this new way but have not found anything so far.

Do you have plans to change the file opener so it supports editing files?

Apple has provided me with information about what they call Document Provider
https://developer.apple.com/library/ios/documentation/General/Conceptual/ExtensibilityPG/FileProvider.html

Thank you for the great plugin
Simon

**Comment by pwlin** [comment]
Hi Simon, I am really sorry but I think editing files is a feature far beyond the capabilities of the current version of this plugin. Of course, any PR in this direction is greatly welcome. Happy 2016!
