### ISSUE TITLE
When I open an apk file, the screen become black

### ISSUE THREAD

**Issue by gogoreg** [pwlin/cordova-plugin-file-opener2#56]
When I open an apk file, the screen become black for a while after installing. but I open the apk directly, not via the plugin, everything is OK. I hope installed an app then I can see the application installed page, then I can choose Done or Open button as usual (not screen black). 
And I found the apk installed success even the screen is black.
Thank you.

**Comment by pwlin** [comment]
So if I understand correctly, there is a blank screen for a little while after installing the APK and that is irritating you? How long does the blank screen remain? And after the blank screen is gone , you do see the dialog with "Done" and "Open" buttons, right?

**Comment by gogoreg** [comment]
I want to update my application.
step 1. Add the plugin to my application
step 2. Download a new version application   myApp.apk    to local directory
step 3. Open  myApp.apk  via the plugin
step 4. Installing with android "Package installer"
step 5. The blank screen becoming, about 10 seconds
step 6.  Android "Package installer" has interrupt without any tips, NO "Done" OR "Open" buttons all the time
step 7. When I open the new application , I found it  has installed success.

The important thing is:
I found if I open other apk file, other application, not itself, not override (e.g. open yourApp.apk),    everything is going  well.

**Comment by pwlin** [comment]
`step 3. Open myApp.apk via the plugin`

Now wait around 1 second then quit your own application via Cordova:

    setTimeout(function() {
        navigator.app.exitApp();
    }, 1000);

Will this help?

**Comment by gogoreg** [comment]
Thank you. After adding exitApp(), It works pretty well now.

**Comment by pwlin** [comment]
Great! good luck!
