### ISSUE TITLE
Error: 404 Not Found: cordova-plugin-file-opener2

### ISSUE THREAD

**Issue by naatogmagithub** [pwlin/cordova-plugin-file-opener2#58]
I get 404 Not Found error when I tried to install the file-opener2 plugin via the cordova CLI.

**Comment by pwlin** [comment]
Maybe your internet connection is temporary down, because issuing 

`cordova plugin add cordova-plugin-file-opener2`

works for me, as seen by this screenshot:

![](http://i.imgur.com/H9QtgeS.png)

**Comment by naatogmagithub** [comment]
I have active internet connection and  I was able to install a similar plugin using the same internet connection: 
cordova plugin add de.sitewaerts.cordova.documentviewer.

This the error.
![eorr](https://cloud.githubusercontent.com/assets/9163155/12392120/714681f8-bda1-11e5-8da9-cf521902181b.png)

**Comment by pwlin** [comment]
I am sorry but I am not really sure what causes the error. Please wait a couple of hours and try later to see if the problem goes away by itself.

**Comment by naatogmagithub** [comment]
Ok. But I started it yesterday.

**Comment by naatogmagithub** [comment]
This worked for me.
cordova plugin add com.cordova.plugins.fileopener
In case somebody also face similar problem in the future.

**Comment by pwlin** [comment]
But that can not be the same plugin as this one!

Which Cordova version are you using? And which Node/NPM version?

**Comment by naatogmagithub** [comment]
Cordova 3.6.3.*
npm 2.14.12

**Comment by pwlin** [comment]
Can you please upgrade your Cordova to 4.* ? Maybe that solves your issue?

**Comment by naatogmagithub** [comment]
OK. Thanks Geek.

**Comment by pwlin** [comment]
So does it work now? Was the problem an older Cordova version?

**Comment by pwlin** [comment]
I am sorry, did you finally solve this issue?

**Comment by naatogmagithub** [comment]
Yes it is the version that was causing it.

**Comment by pwlin** [comment]
great, good luck.
