### ISSUE TITLE
Uncaught TypeError: Cannot call method 'open' of undefined 

### ISSUE THREAD

**Issue by naatogmagithub** [pwlin/cordova-plugin-file-opener2#59]
I installed this plugin and tried to open a pdf document located in img folder inside the www folder.
Here is my code

document.addEventListener("deviceready", function(){
	$("#readfile").on("click", function(){
		var source = buildAssetsUrl("img/lazy.pdf");
		
		cordova.plugins.fileOpener2.open(
		    source,
		    'application/pdf', 
		    { 
		        error : function(e) { 
		            console.log('Error status: ' + e.status + ' - Error message: ' + e.message);
		        },
		        success : function () {
		            console.log('file opened successfully');                
		        }
		    }
		);
	});
});

//methods
var baseUrl = location.href.replace("/index.html", ""); 
 function buildAssetsUrl(file) { 
 return baseUrl + "/" + file; 
}
Anything I did wrong?

**Comment by pwlin** [comment]
I think this issue was also related to the low Cordova version which you already fixed.
