### ISSUE TITLE
Open files from data/data/<app-id>/files

### ISSUE THREAD

**Issue by dmaus** [pwlin/cordova-plugin-file-opener2#61]
Is it possible to open files from the location 'data/data/app-id/files' (i used the [contentsync](https://github.com/phonegap/phonegap-plugin-contentsync) plugin to download a PDF) or do i have to copy the files to '/storage/emulated/0/'? Thx

**Comment by Nuajan** [comment]
+1 Same problem here. Unable to open a file on 'data/data/app-id/files'
Plugin reports as opened but associated app (in my case Acrobat Reader...) reports that cannot open such url even when is totally correct as noticed in via shell terminal (file really exists!).

**Comment by dmaus** [comment]
As far as i know now, you cant open files from that directory in external apps. So you have to copy the files to cordova.file.externalCacheDirectory and open it from there.

**Comment by Nuajan** [comment]
Thanks @dmaus Tested and working on Android. 
Just a last question: does it works the same way on IOS? i mean, is it impossible to open a file on dataDirectory?

**Comment by dmaus** [comment]
On iOS you can open files from dataDirectory. And you can show PDFs with the inappbrowser from in your app.

**Comment by Nuajan** [comment]
Oh! sure. Sorry, it was obvious.
Don't understand how cannot this be possible in Android nowadays... :|
Thanks again.
