### ISSUE TITLE
Open file from URL

### ISSUE THREAD

**Issue by Valkno** [pwlin/cordova-plugin-file-opener2#64]
It possible open file from url

It's possible open file from url, i try but doesn't work.

Example:

```
$cordovaFileOpener2.open(
    'http://example.com/file.pdf',
    'application/pdf'
    ).then(function() {
        console.log('Success');
    }, function(err) {
        console.log('An error occurred: ' + JSON.stringify(err));
    });
```

**Comment by sylfree9999** [comment]
+1
Will it possible to directly open file from url, not from local system?

**Comment by GaryTowers** [comment]
Does this library supports opening a PDF file from a URL?

**Comment by pwlin** [comment]
This plugin does not support opening URLs directly. Please save your files locally first.
