### ISSUE TITLE
iOS: File Transfer Download success but File not store in iBook or other App

### ISSUE THREAD

**Issue by hiniesta** [pwlin/cordova-plugin-file-opener2#65]
Hello:

Since few weeks, in iOS, the file download finishes succesfully, and after selecting iBooks or similar (dropbox, onedrive, etc ) app to open the file with, the Apps selector closed and the file is not storage in iBooks. Any idea?

If I log the plugin, I get:

Couldn't get file size for file:/var/mobile/Containers/Data/Application/ACD9EF91-CC5B-4031-9F9B-63AB428B332E/Documents/Filename.pdf -- file:///: Error Domain=NSCocoaErrorDomain Code=260 "The file “Filename.pdf” couldn’t be opened because there is no such file."

**Comment by pwlin** [comment]
There has been a couple of new releases since then. Can you please upgrade and test if you still have issues? thanks
