### ISSUE TITLE
IOS:File name containing spaces or Chinese characters shows error: file not found

### ISSUE THREAD

**Issue by aiaihuzi7** [pwlin/cordova-plugin-file-opener2#68]
Hi, everyone! 
I'm using fileopener2 version 2.0.2.
If the filename consist of spaces or Chinese characters it shows an error: file not found even though I use `decodeURIComponent()`.(Android is working properly,IOS show this error.)
Can someone give me an idea to fix this error? Thank you.

This is my code:

```
var filePath = '';
    if (ionic.Platform.isAndroid()) {
      filePath = cordova.file.externalDataDirectory;
    }
    if (ionic.Platform.isIOS()) {
      filePath = cordova.file.documentsDirectory;
    }

    $cordovaFile.writeFile(filePath, 'test test.txt', 'This is a test file!', true)
      .then(function (success) {
        return $cordovaFileOpener2.open(decodeURIComponent(success.target.localURL), 'text/plain');
      }, function (error) {
        //write file error
      }).then(function (success) {
        //success
      }, function (error) {
        //error
      });
```

**Comment by RobinBecker** [comment]
I just ran into the same problem, luckily not with Chinese letters but with the blank spaces. I just used the `.replace(' ', '_')` function to get the blank spaces inside my URI away. For Chinese letters this may not be that easy but i hope i kind of helped you with this.

**Comment by sweexxik** [comment]
@aiaihuzi7 Try to use decodeURIComponent() only for Andorid. It might be OK to use undecoded symbols for iOS.

**Comment by pwlin** [comment]
There has been a couple of new releases since then. Can you please upgrade and test if you still have this issues? thanks
