### ISSUE TITLE
About Open APK File.

### ISSUE THREAD

**Issue by berserker001** [pwlin/cordova-plugin-file-opener2#70]
Hey buddy, I have a problem.
When I using your plugin to open a APK file,I got a error message under **Android 5.0 & 6.0.**
It means the system can not analysis the APK file.
But I can sure it is a usable package.
Cause the same code and the same APK file,it was successfully installed in **Android 4.x.**
Please help me to resolve this problem.Tanks ~ ^_^.
PS:I already to try some solutions.Like exit the application after cordova.file.open()

**Comment by pan196** [comment]
Hi,

I can confirm that issue - when trying to upgrade one of my applications to newer version of Cordova the opening mechanism for .apk files does not work and throws an error - "There was a problem parsing the package". Will be happy if somebody can share more information about that.

Thanks.

**Comment by berserker001** [comment]
So,I think you are Chinese too.If you want a solution to fix that problem.You can contact me by Wechat.
Here is my wechat ID:blackaddress.

**Comment by pan196** [comment]
I am not a Chinese and does not have WeChat account, but can you share your solution here to be visible for all that face that problem in future. Or contact me on that email: peter.petrov@quezter.org

**Comment by berserker001** [comment]
I have two points for you.
1.Make sure the APK file is usable(Try the manual installation).
2.Make sure your APK file version is 0.0.2 or higher when the currently application version is 0.0.1.
You can feedback the result to me anytime in here.

**Comment by pan196** [comment]
I am testing now increasing android:versionCode as well as android:versionName which holds the version of the app but nothing changes. 

Actually, initially I found that bug trying to install app which does not exist on the current device (and does not has a version yet) which tells me that may be the android version does not play any role so far (maybe after that).

The packages are usable. Manually I am able to open them and this is possible also using Cordova v4.0.0 and down.

**Comment by berserker001** [comment]
Could you tell me your Android Version?

**Comment by pan196** [comment]
The latest test was made on Android 7.1.1. The installation of new packages (not existing on the current device) is tested on Android 5.1.1 as well.

**Comment by berserker001** [comment]
Can you confirm that the package is completely downloaded? Or you try to put this package directly to the SD card not by code. and then use cordova.file.open () to open.

**Comment by supermarioim** [comment]
same problem here, did you manage to resolve this issue anyhow?

**Comment by pan196** [comment]
Hi,

I changed only the download location to start with cordova.file.externalRootDirectory and after that the file opener worked as charm.
