### ISSUE TITLE
How to open an unknown format

### ISSUE THREAD

**Issue by tommarx69** [pwlin/cordova-plugin-file-opener2#71]
Hi,
I can open a specific type with this plugin (like PDF, PNG etc...), but how to open an file with its default app ?
Thx,
Tom

**Comment by elbidone** [comment]
Hi @tommarx69, if file have correct extension you should try [cordova-open](https://github.com/disusered/cordova-open) plugin.
For Android you could also use [cordova-plugin-inappbrowser](https://github.com/apache/cordova-plugin-inappbrowser) w/ target="_system" (doesn't work on iOS)
