### ISSUE TITLE
fileopener2 not working in Cordova

### ISSUE THREAD

**Issue by phdecloitre** [pwlin/cordova-plugin-file-opener2#74]
Hello,
I'm trying to have fileopener2 working for pdf files with this piece of code:

```
$('a[href$=\\.pdf]').click(
                                function() 
                                {
                                    var myuri = this.href ;
                                     alert(this.href);

  $cordovaFileOpener2a.open( decodeURIComponent(this.ref().substr(7)), extention).then( function() function(e) { alert("ok!"); alert('Error status: ' + e.status + ' - Error message: ' + e.message); } );
}); 
```

Unfortunalety it retunrs nothing, not even an error.
If I only use the following part I do get the url on the alert:

```
$('a[href$=\\.pdf]').click(
                                function() 
                                {
                                    var myuri = this.href ;
                                     alert(this.href);
```

But if I add the following piece, the whole script freezes.

`$cordovaFileOpener2a.open( decodeURIComponent(this.ref().substr(7)), extention).then( function() { $ionicLoading.hide(); }, function(e) { alert("ok!"); alert('Error status: ' + e.status + ' - Error message: ' + e.message); } );`
Can you tell me why?
Thank you

**Comment by piyush-v-n** [comment]
Hello,
i ma trying to work on fileopener2 plugin with the following below code:

var fileTransfer = new FileTransfer();
    var inputUri = encodeURI("http://nextwavesoftware.com/downloads/helloworld.pdf");
    var outputPath = "cdvfile://localhost/persistent/downloads/"+ "helloworld.pdf";
    // var outputPath = "/storage/emulated/0/Download/helloworld.pdf";
    console.log("Starting download to " + outputPath);
    fileTransfer.download(
          inputUri,
          outputPath,
        function (entry) {
            console.log("Download complete: " + entry.fullPath + ", URL=" + entry.toURL());
            cordova.plugins.fileOpener2.open(
                'cdvfile://localhost/persistent/Download/helloworld.pdf', // You can also use a Cordova-style file uri: cdvfile://localhost/persistent/Download/starwars.pdf
                'application/pdf',
                {
                    error: function (e) {
                        console.log('fileOpener2 error status: ' + e.status + ' - Error message: ' + e.message);
                    },
                    success: function () {
                        console.log('fileOpener2 file opened successfully');
                    }
                }
            );
        },
        function (error) {
            console.log("download error: source=" + error.source + ", target=" + error.target + ", error code=" + error.code);
        });

i am developing for windows 8.1 and windows 10.
But it doesn't work as it should be. 
Can you please help?

Thank you

**Comment by pwlin** [comment]
There has been a couple of new releases since then. Can you please upgrade and test if you still have this issues? thanks
