### ISSUE TITLE
The mail subject is not set after first opening

### ISSUE THREAD

**Issue by ungureanuliviu** [pwlin/cordova-plugin-file-opener2#76]
Hi,

I got a weird issue with attaching a pdf in Mailapp on iOS 9.3.3. 
First time when I "open" my file with Mailapp the file's name is set as mail subject. So far so good.
If I try to do the same thing again the subject is not set. I tried even with different files.
If I restart my app, the subject is set but only on first opening.

I know this might not be a bug in plugin but I don't understand how it works only the first time.
Just for testing I did
`self.controller.name = @"test"`
It works first time but on second opening the subject is empty as well.
Hope someone have some idea about what is happening.

Thank you. #

**Comment by pwlin** [comment]
There has been a couple of new releases since then. Can you please upgrade and test if you still have this issues? thanks
