### ISSUE TITLE
Open audio-book in iBook - MIME type

### ISSUE THREAD

**Issue by lync0056** [pwlin/cordova-plugin-file-opener2#77]
Hello,

Any comment would be fabulous. I can't solve.

Attempting to open an audio-book in iBook. Unfortunately no matter what MIME type I use, it won't give me the option to open the file in iBook.  Under eBook with epub format, I have no problem, and it will open in iBooks.

If I change the format of the audio-book from .mp3 to .epub, it will open in iBooks, however, it will not play because the file format is incorrect.

MIME type link - http://svn.apache.org/viewvc/httpd/httpd/trunk/docs/conf/mime.types?view=co

**Comment by pwlin** [comment]
There has been a couple of new releases since then. Can you please upgrade and test if you still have this issues? thanks
