### ISSUE TITLE
WP 8.1: opening files 

### ISSUE THREAD

**Issue by any2info** [pwlin/cordova-plugin-file-opener2#78]
Hello,

I'm currently working on a cordova based (cli 6.1.1) app using the file-opener2 plugin. I'm trying to get through the following steps:
- Download a document from a server to my device (using file-transfer) 
- After the downloaded has succeeded i want to open the file

For both android and ios this works perfectly. When i try this for windows phone 8.1 the download appears to be successfull and i try to open the file using the code:
`cordova.plugins.fileOpener2.open(
            filePath,
            FileTransferHelper.getMimeType(fileType),
            {
                error: function (e) {
                    onError("Error occurred");
                },
                success: function () {
                    onSuccess();
                }
            }
        );`
- The geMimetype helper resolves my file extenion from the server to a mimetype
- The filePath looks something like "ms-appdata:///local//myFile.pdf"

When running this the error callback is called but no error paramter is given so i cannot see what went wrong. 

Can anyone please point out what the problem is?

**Comment by J3r0M3D3V** [comment]
Hi,
I had problems on windows too and make a fix (at least for me). It's in pull request #83 (https://github.com/pwlin/cordova-plugin-file-opener2/pull/83), you can give it a try if you still have the problem or wait the merge.

**Comment by manoj529** [comment]
In my case I'm storing images in app data and trying to access it using the plugin and the file path looks something like '//PREDEFINEDDIRECTORY/2016-12-14-13-08-40.jpg'.
Either the plugin is not able find the path correctly or its not getting rights to access file.
**** Using it in wp8 ***
can someone help me regarding this issue.
Thanks in advance.

**Comment by J3r0M3D3V** [comment]
Hi,

Why I just got notified from this thread ? I did a pull request (merged) for Windows, not wp8.

Anyway, @any2info @manoj529  according to the [source code](https://github.com/pwlin/cordova-plugin-file-opener2/blob/master/src/wp8/FileOpener2.cs), wp8 only works with full file path (like "C:\Data\Users\DefApps\AppData\{ECCB0535-E89C-4C9B-A223-DD34591CDC5E}\local\file.txt").

ms-appdata:/// or cdfile:// are uri, not full path.
And a path starting with "//" seems incorrect to me.
You shouldn't needed rights to work with the application folder. 
The rights are managed from the .appxmanifest tab capabilities under Visual Studio without Visual Studio edit the file and add for example: <Capability Name="[picturesLibrary](https://msdn.microsoft.com/en-US/library/windows/apps/hh464936.aspx#pictureslibrary)" /> in the Capabilities tag.
(Microsoft specify [this](https://msdn.microsoft.com/library/windows/apps/jj206936(v=vs.105).aspx) for wp8 but my wp8 appxmanifest matches the previous link)

**Comment by manoj529** [comment]
@J3r0M3D3V  Really thank you the quick response.

I tried the options that you specified with no luck.
**Few points to add for additional information**.
- I'M using :
     window.requestFileSystem(LocalFileSystem.PERSISTENT, 0, function (fileSystem) {
            fileSystem.root.getFile(ImageCachedPath, null, function (fileEntry) {
                console.log('cached image stored at ' + fileEntry.nativeURL);
                window.resolveLocalFileSystemURL(fileEntry.nativeURL, copyPhoto, fail);
            }, fail);
    }, fail);

    window.requestFileSystem(LocalFileSystem.PERSISTENT, 0, function (fileSys) {
            fileSys.root.getDirectory("MYDIRECTORY", { create: true, exclusive: false }, function (dir) {
                var formattedDate = getFormattedCurrentDate(); // custom function to generate file name
                var fileName = fileEntry.name;
                var fileExtension = getFileExtentionByname(fileName);
                //console.log('File Extension Received from method getFileExtentionByname ' + fileExtension);
                var imgFilePath = formattedDate +'.' + fileExtension;
                //console.log('copyPhoto with details' + JSON.stringify(fileEntry));
                fileEntry.copyTo(dir, imgFilePath, onCopySuccess, fail);
             }, fail);
        }, fail);
    } catch (e) {
        console.log(e.message);
    }

Here in this case i'm getting 
Cached image path ::  /CapturedImagesCache/WP_20161217_006.jpg
Copied directory path : //TAGGEDIMAGES/2016-12-17-12-37-57.jpg


Point is I'm able to display images on the application page using the same image path. However unable open same images using the opener plugin in windows phone 8.1.

**Comment by J3r0M3D3V** [comment]
@manoj529 
Web apps (like cordova's ones) are sandboxed. => lot of restrictions.
Capabilities is not what you need here as you are already working in the app local folder.

From what I understand, roughly you are stuck on the full file path. Javascript (FileEntry) will never tell you the full path, at best you will get "C:\fakepath\file.txt". You need to use WinJS to go through this restriction.

But it's quite a bad idea .. Way better to work with uri on a webapp, but currently file-opener2 on wp8 doesn't work with uri. You should do a fork (+ pull request when it works) to add the uri support on wp8.
You can look to what I did on windows [here](https://github.com/pwlin/cordova-plugin-file-opener2/blob/master/src/windows/fileOpener2Proxy.js) , it's almost the same thing in C# (same namespaces)

**Comment by manoj529** [comment]
@J3r0M3D3V 
Again thank you for the reply.
I tried debugging the CS file and found that its unable to load file at this using url as "//TAGGEDIMAGES/2016-12-17-12-37-57.jpg"
StorageFile file = await Windows.Storage.StorageFile.GetFileFromPathAsync(args[0]);
Updated code to get the complete complete path as you said its like "C:\fakepath\img.jpg"
but still the error seems to be the same.
and im not receiving any error on console to figure out why its not able to get the image where i was easily able to display images on web application screen.

**Comment by J3r0M3D3V** [comment]
@manoj529 
Yep, as I said you won't get the full path in JS and currently the plugin only works with full path.
You need to add an URI support in C#.
Call in JS:
`cordova.plugins.fileOpener2.open( fileEntry.toURL(), mime, { error: function(e) { //stuff }, success: function() { //stuff } } );`

in C#:
`Windows.Storage.StorageFile.GetFileFromApplicationUriAsync(args[0])`
You might need to do some work on the args[0] as I did in the Windows part of the plugin due to bad uri representation (from FileEntry for Windows).
