### ISSUE TITLE
Can´t open jspdf blob in Android (Intel XDK)

### ISSUE THREAD

**Issue by hit2501** [pwlin/cordova-plugin-file-opener2#79]
Hi, I´m using jspdf  to generate a pdf and works fine but when I try to open the output directly (without save) in Android (Cordova-Intel XDK) nothing happens, I tried different FileOpener2 samples but all of them are pointed to save first and then open. I dont want to save in device because I saw that there is more complex save and open and I'm still learning (noob), also is not necessary for me to keep a copy. What I want is that once the pdf output is generated then proceed to open with the pdf default reader (Adobe Reader, Epson Iprint, etc). This is my code:

```
`function createPDF(){
    console.log("generating pdf...");
    var doc = new jsPDF();

    doc.text(20, 20, 'HELLO!');

    doc.setFont("courier");
    doc.setFontType("normal");
    doc.text(20, 30, 'This is a PDF document generated using JSPDF.');
    doc.text(20, 50, 'YES, Inside of cordova!');

    pdfOutput = doc.output();
    console.log(pdfOutput);
    alert("pdf successfully created");

    //TRYING TO OPEN THE BLOB (but nothing happens)
    var binaryData = [];
    binaryData.push(pdfOutput);
    var objt = window.URL.createObjectURL(new Blob(binaryData, {type: "application/pdf"}));
    window.open(objt, '_system', 'location=yes');
}`
```

The Intel XDK console never shows me a error and thats why I´m confused.

Can you help me to achieve it for Android?

Regards.

**Comment by pwlin** [comment]
You need to save first, then open.
