### ISSUE TITLE
Not compatible with Android api 24

### ISSUE THREAD

**Issue by kosssi** [pwlin/cordova-plugin-file-opener2#84]
Hello @pwlin 

Thanks for your plugin ;)
I use it on @Cozy [application mobile](https://github.com/cozy/cozy-mobile).
I'm update cordova with api 24 but your plugin return an error : 

```
"file:///storage/emulated/0/Android/data/blabla/20160630_bill.pdf exposed beyond app through Intent.getData()"
```

I test to resolve it.

Documentation :
- http://stackoverflow.com/questions/38200282/android-os-fileuriexposedexception-file-storage-emulated-0-test-txt-exposed
- https://inthecheesefactory.com/blog/how-to-share-access-to-file-with-fileprovider-on-android-nougat/en
- https://developer.android.com/reference/android/support/v4/content/FileProvider.html

**Comment by kosssi** [comment]
I resolve this issue with this commit : https://github.com/kosssi/cordova-plugin-file-opener2/commit/bbb8b4b817a61f0b61a470496cbc0f0612164783

@pwlin how can integrate it on your plugin ?

**Comment by pwlin** [comment]
Hi @kosssi thanks for finding a solution. Can you send a pull request so I can merge this?

But before that I have 2 questions:

1- Are your changes backward compatible? What will happen if someone targeting older Android versions uses this plugin?

2- you have hard-coded your app name in `src/android/res/xml/provider_paths.xml` 

    <external-cache-path name="cozy-download" path="cozy-downloads/" />

Can that be changed?

**Comment by kosssi** [comment]
@pwlin I don't forget you ;) but I want approve this solution before merge it. Today I found a bug with older version of Android N

**Comment by woonsan0619** [comment]
when my path download is storage/emulated/0/Download/201512_201091675103.pdf, what value i should put in at provider_paths.xml? 
Below is the correct path?
<external-path name="external_path" path="." />

**Comment by WuglyakBolgoink** [comment]
I think, i fixed this )

**Comment by dominik0711** [comment]
@WuglyakBolgoink Could you provide the fixed plugin version for running Android 24+? 

Thanks in advance 👍

**Comment by dominik0711** [comment]
@kosssi Do you have a working solution for Android 24+? Do I have to change file file URL from `file:///` to `content:///`?
With your implementation: kosssi@bbb8b4b I did get a **File not found error**.

Thanks in advance 👍

**Comment by kosssi** [comment]
@dominik0711 this commit have some specific code for Cozy App ([here](https://github.com/kosssi/cordova-plugin-file-opener2/blob/bbb8b4b817a61f0b61a470496cbc0f0612164783/plugin.xml#L27) and [here](https://github.com/kosssi/cordova-plugin-file-opener2/blob/bbb8b4b817a61f0b61a470496cbc0f0612164783/src/android/res/xml/provider_paths.xml#L3)).

You can read [this documentation](https://developer.android.com/reference/android/support/v4/content/FileProvider.html).

I have no time to create a good patch sorry.

**Comment by dominik0711** [comment]
@kosssi First of all, thanks for your help!
Could you give me a hint, why my ProviderInfo object in `FileProvider.java` always returns null?
Here some Screenshots of my implementation:

![screen shot 2017-01-27 at 10 52 00](https://cloud.githubusercontent.com/assets/1011188/22366886/282edd2a-e47f-11e6-8309-505520ced36f.png)

FileProviderInfo (line 581):

![screen shot 2017-01-27 at 10 54 04](https://cloud.githubusercontent.com/assets/1011188/22366899/343d5bf0-e47f-11e6-8873-377a0e8d7d4b.png)

Do I provide the wrong context? 
My context is: **Context context = cordova.getActivity();**

This is my AndroidManifest.xml:

```
<?xml version='1.0' encoding='utf-8'?>
<manifest android:hardwareAccelerated="true" android:versionCode="10700" android:versionName="1.7.0" package="com.artificialunit.arcwork" xmlns:android="http://schemas.android.com/apk/res/android">
    <supports-screens android:anyDensity="true" android:largeScreens="true" android:normalScreens="true" android:resizeable="true" android:smallScreens="true" android:xlargeScreens="true" />
    <uses-permission android:name="android.permission.INTERNET" />
    <application android:hardwareAccelerated="true" android:icon="@mipmap/icon" android:label="@string/app_name" android:supportsRtl="true">
        <activity android:configChanges="orientation|keyboardHidden|keyboard|screenSize|locale" android:label="@string/activity_name" android:launchMode="singleInstance" android:name="MainActivity" android:theme="@android:style/Theme.DeviceDefault.NoActionBar" android:windowSoftInputMode="adjustResize">
            <intent-filter android:label="@string/launcher_name">
                <action android:name="android.intent.action.MAIN" />
                <category android:name="android.intent.category.LAUNCHER" />
            </intent-filter>
        </activity>
    </application>
    <uses-sdk android:minSdkVersion="14" android:targetSdkVersion="25" />
    <provider android:authorities="${applicationId}.fileprovider" android:exported="false" android:grantUriPermissions="true" android:name="android.support.v4.content.FileProvider">
        <meta-data android:name="android.support.FILE_PROVIDER_PATHS" android:resource="@xml/provider_paths" />
    </provider>
    <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />
    <uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE" />
</manifest>
```

And this is my provider_paths.xml:

```
<?xml version="1.0" encoding="utf-8"?>
<paths>
    <external-path name="files_root" path="Android/data/${applicationId}/" />
    <files-path name="name" path="files/" />
    <external-files name="name" path="files/" />
    <external-files-path name="name" path="files/" />
</paths>
```

Is there something wrong with the provided file paths??? 

The path where the files are stored is as follow: **/storage/emulated/0/Android/data/com.artificialunit.arcwork/files/FILE-NAME.pdf**

Thanks in advance! 👍

**Comment by lincolnthree** [comment]
Hey guys. Cordova noob here but it seems I've hit this issue as well since upgrading to Android 24+. I'd love to help but not sure how.   Is there a known workaround for this, e.g. using a different location on the device? Trying to put the pieces of this thread together. Thanks!

**Comment by lincolnthree** [comment]
Alright, well. That was a relaxing afternoon.

https://github.com/pwlin/cordova-plugin-file-opener2/pull/89
