### ISSUE TITLE
how to add plugin in config.xml manually

### ISSUE THREAD

**Issue by mkjain554** [pwlin/cordova-plugin-file-opener2#86]
How to add this plugin in config.xml manually,I did not find the documentation to add directly to the config file.

Please suggest.

**Comment by Aggror** [comment]
<plugin name="cordova-plugin-file-opener2" spec="2.0.3" />

**Comment by WuglyakBolgoink** [comment]
Hi @mkjain554 

better reinstall it with `--save`

**Comment by juansaa** [comment]
What tag do I add in my config.xml? I'm using phonegap build

**Comment by shnist** [comment]
@juansaa please raise a separate ticket, commenting on closed tickets means I may forget about it because it's not in the list of open ones.
