### ISSUE TITLE
How to open the outlook msg file

### ISSUE THREAD

**Issue by Jager001** [pwlin/cordova-plugin-file-opener2#87]
How to open the outlook msg file? Does this plugin support the function?

Please suggest.

**Comment by WuglyakBolgoink** [comment]
Hi @Jager001 ,

Try this  https://www.quora.com/How-can-I-open-MSG-files-on-my-Samsung-Galaxy-Android-phone

with mimetype

**Comment by pwlin** [comment]
This plugin can open anything, as long as you have the appropriate viewer for that particular file you are trying to open already installed in your app.
