### ISSUE TITLE
Can this plugin open wps file？

### ISSUE THREAD

**Issue by cc18314552041** [pwlin/cordova-plugin-file-opener2#88]
I find MIME type of WPS in your readme file，but I can‘t open wps file with your plugin。’

**Comment by WuglyakBolgoink** [comment]
Hi @cc18314552041 ,

do you have WPS-Viewer on your phone?

**Comment by cc18314552041** [comment]
Sure, I also want to know can this open a file with url.. thank you - =

**Comment by cc18314552041** [comment]
@WuglyakBolgoink Sure, I also want to know can this open a file with url.. thank you - =

**Comment by pwlin** [comment]
This plugin can open anything, as long as you have the appropriate viewer for that particular file you are trying to open already installed in your app.

@WuglyakBolgoink I am sorry but you need to save your file locally before trying to open it.
