### ISSUE TITLE
Phonegap Build fails with version 2.0.4

### ISSUE THREAD

**Issue by WeaponX86** [pwlin/cordova-plugin-file-opener2#90]
It was working fine last week.

From the error log:

> :processDebugManifest/project/AndroidManifest.xml:16:9-18:20 Error:
> 	Element provider#android.support.v4.content.FileProvider at AndroidManifest.xml:16:9-18:20 duplicated with element declared at AndroidManifest.xml:13:9-15:20
> /project/AndroidManifest.xml Error:
> 	Validation failed, exiting

Phonegap version:
` <preference name="phonegap-version" value="cli-6.4.0" />`

Plugins:
```
  <plugin name="cordova-plugin-battery-status" />
  <plugin name="cordova-plugin-camera" />
  <plugin name="cordova-plugin-console"/>
  <plugin name="cordova-plugin-device" />
  <plugin name="cordova-plugin-device-orientation" />
  <plugin name="cordova-plugin-dialogs" />
  <plugin name="cordova-plugin-file" />
  <plugin name="cordova-plugin-geolocation" />
  <plugin name="cordova-plugin-globalization" />
  <plugin name="cordova-plugin-network-information" />
  <plugin name="cordova-plugin-splashscreen" />
  <plugin name="cordova-plugin-statusbar" spec="2.0.0"/>
  <plugin name="cordova-plugin-whitelist" />
  <plugin name="cordova-plugin-file-transfer" />
  <plugin name="cordova-plugin-inappbrowser" />
  <plugin name="cordova-plugin-file-opener2"/>
```

Found a possible fix here:
http://stackoverflow.com/questions/40746144/error-with-duplicated-fileprovider-in-manifest-xml-with-cordova

**Comment by cindyliu-yb** [comment]
Same here.

**Comment by cabaird** [comment]
I am seeing this issue as well.  It looks like it is an issue in the plugin.xml file.

https://github.com/pwlin/cordova-plugin-file-opener2/blob/master/plugin.xml#L29

For me, this duplicates another provider tag that is generated by the plugin.xml file in `cordova-plugin-camera`

https://github.com/apache/cordova-plugin-camera/blob/master/plugin.xml#L73

**Comment by pwlin** [comment]
Thanks everyone, I merged @rocco's fix and pushed a new version (`2.0.5`) to `npm`. Please upgrade and let me know if it works now.

**Comment by rocco** [comment]
thanks @pwlin. I am still testing this ;) my build runs but the app has some other trouble at the moment

**Comment by pwlin** [comment]
@rocco thank you too. You are also welcome to send your pull requests directly :)

**Comment by rocco** [comment]
I would have - you beat me to it

**Comment by pwlin** [comment]
@rocco @cabaird @cindyliu-yb @WeaponX86 , just a heads up: you should update to version `2.0.6`, as I just merged another PR (#91)

**Comment by cindyliu-yb** [comment]
It can build now. Thanks!

**Comment by cabaird** [comment]
Thanks @rocco and @pwlin for the quick fix!
