### ISSUE TITLE
Can parameter 'MIME' be omitted?

### ISSUE THREAD

**Issue by lovelyelfpop** [pwlin/cordova-plugin-file-opener2#92]
We can guess mime by using 
`String mime = URLConnection.guessContentTypeFromName(filePath);` for android;
`UTTypeCreatePreferredIdentifierForTag()` for ios.

**Comment by pwlin** [comment]
At the moment you need to specify a mime type for Android. (You can omit it For iOS). In one of the future releases I will make it also optional for Android.

**Comment by cmaart** [comment]
+1

**Comment by ramaguduri** [comment]
+1

**Comment by regnete** [comment]
+1

**Comment by lqixv** [comment]
here has a js code :
https://github.com/broofa/node-mime

just to import the js file

**Comment by shnist** [comment]
Going to close this issue as it was more a question that was answered.
