### ISSUE TITLE
File not open in Android 7 getting 'exposed beyond app through Intent.getData()' error for sdk 24 and above

### ISSUE THREAD

**Issue by kirandc** [pwlin/cordova-plugin-file-opener2#93]
Hi I am Using cordova-plugin-file-opener2  version 2.0.7 in my Ionic 2 application. 

When I am opening file then getting following error

file:///storage/emulated/0/Android/data/com.appname.app/files/tpn/Record-Prescription_41537_13012017040852.jpg exposed beyond app through Intent.getData()

here is my code

``
FileOpener.open(targetFileName, this.mimeType).then((success) => {
              console.log('Success', success)
            }, (error) => {
              loading.dismiss();
            });
``

same issue fixed in this pull request https://github.com/pwlin/cordova-plugin-file-opener2/pull/89 but still not work on Android 7.  Work on Android 6

MORE INFO: I was building my app in Android SDK 24. When I change to 23 It's work. So issue for building app in Android SDK 24 and above

**Comment by pwlin** [comment]
Have you tried googling the error you are getting?

**Comment by kirandc** [comment]
@pwlin yes I google then I found to build in sdk 23. But why not work in sdk 24 and above.

**Comment by zengyufang** [comment]
@pwlin I also encountered the same problem.I think this is a question of authority,but I don't how to solve

**Comment by jihuiwang** [comment]
@zengyufang you are right, i have the same issue when open files on Android 7 which worked on Android 5. After I swithed on the full trust on my app in Android Settings, it finally worked. you should try it.

**Comment by pwlin** [comment]
There has been a couple of new releases since then. Can you please upgrade and test if you still have issues?

**Comment by jihuiwang** [comment]
yes, after upgrade to 2.0.13, it finially worked, thanks @pwlin

**Comment by pwlin** [comment]
Ok good to hear that. Good luck.
