### ISSUE TITLE
Open PDF with bookmark

### ISSUE THREAD

**Issue by jvhe123** [pwlin/cordova-plugin-file-opener2#94]
I would like to open a PDF document en position the cursor to a given bookmark in the document.

Normally you would open the pdf document in the browser by adding the bookmarkname after a #

f.ex. : http://myserver.com/document.pdf#MYBOOKMARK

When I try to open document.pdf#MYBOOKMARK with fileopenener2, I get an error that the file is not found.

Is there any other way to open a pdf document with a bookmark ?

**Comment by pwlin** [comment]
Open your pdf with [cordova-plugin-inappbrowser](https://cordova.apache.org/docs/en/latest/reference/cordova-plugin-inappbrowser/) and check if that works.

    cordova.InAppBrowser.open('http://myserver.com/document.pdf#MYBOOKMARK', '_blank', '');

**Comment by jvhe123** [comment]
I tried inAppBrowser, but also in this case, the pdf won't open on the specified bookmark.
I also tried using "named destinations", without success.

Anyone would know a solution ?

**Comment by pwlin** [comment]
@jvhe123 have you found any workaround for this problem?

**Comment by jvhe123** [comment]
No, unfortunately not.

**Comment by pwlin** [comment]
That's indeed unfortunate. I'll still look around and keep the issue in mind. You can also let me know if you've found any example of how to do it.

**Comment by pwlin** [comment]
@jvhe123 have you tried to see if [cordova-plugin-document-viewer](https://github.com/sitewaerts/cordova-plugin-document-viewer) supports pdf bookmarks?
