### ISSUE TITLE
Open File raise an error when I change widget id 

### ISSUE THREAD

**Issue by nicolaslawdune** [pwlin/cordova-plugin-file-opener2#95]
Hello,

Everything works perfectly before I decided to change the widget Id in the config.xml.

After changing the Id, I get this error when I try to open file: 
`Attempt to invoke virtual method 'android.content.res.XmlResourceParser android.content.pm.PackageItemInfo.loadXmlMetaData(android.content.pm.PackageManager, java.lang.String)' on a null object reference`

So, if I use the previous widget id, I can open file without error.

What is the relation between the widget id and the open method.

Thank you for your help.

**Comment by pwlin** [comment]
Which widget id are you referring to?

**Comment by nicolaslawdune** [comment]
When you edit your config.xml, one of my root tag is "widget" and contains an "id" attribute.
Directory path (cordova.file.externalCacheDirectory/ cordova.file.cacheDirectory etc...) depends on widget id.
I think that after manipulating InAppBrowser/FileTransfer/FileOpener2 component, I probably change authorization of my directory folder, that's why the original folder using original widget id works.

After creating a new simulator, I got this issue, so this problem do not come from widget id.
I test my app on a device and it seems that it works without this error.

**Comment by nicolaslawdune** [comment]
For this problem, I think it's due to filename format, because it contains blank space and special caracters.

The real question is : why does it work with the previous widget id ?
With the previous "Id", I maintly focus on InAppBrowser to download file, and I probably accept authorization for current user. After that, when I replace InAppBrowser with FileOpener, there was no problem of authorization.

**Comment by pwlin** [comment]
That doesn't sound like a problem with this plugin, right? What if you don't change the widget id and leave it intact?

**Comment by nicolaslawdune** [comment]
Yes, I think that the problem occurs because it doesn't find any readers on my android simulator. If I deploy on real device, it works well.

**Comment by pwlin** [comment]
Ok great. Good luck.
